// packages/react/src/components/actions/toggle.tsx
"use client";
import type { ComponentProps, MouseEvent } from 'react';
import type { Size } from '@fewcompany/core';
import { Slot, Slottable } from '../../lib/slot.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';

export type ToggleVariant = 'primary' | 'secondary';

export interface ToggleProps extends ComponentProps<'button'> {
  asChild?: boolean;
  pressed?: boolean;
  defaultPressed?: boolean;
  onPressedChange?: (pressed: boolean) => void;
  size?: Size;
  variant?: ToggleVariant;
}

/** Botão de dois estados (pressionado/solto). `<Toggle pressed={bold} onPressedChange={setBold}>N</Toggle>` */
export function Toggle({ asChild, pressed: pressedProp, defaultPressed = false, onPressedChange, size = 'md', variant = 'secondary', disabled, className, type = 'button', onClick, children, ...props }: ToggleProps) {
  const [pressed, setPressed] = useControllableState({ value: pressedProp, defaultValue: defaultPressed, onChange: onPressedChange });
  const Comp = asChild ? Slot : 'button';
  function handleClick(event: MouseEvent<HTMLButtonElement>) {
    onClick?.(event);
    if (event.defaultPrevented || disabled) return;
    setPressed(!pressed);
  }
  return (
    <Comp
      {...props}
      type={type}
      aria-pressed={pressed}
      disabled={disabled}
      data-state={pressed ? 'on' : 'off'}
      data-disabled={dataAttr(disabled)}
      className={cx('few-toggle', `few-toggle--${variant}`, `few-toggle--${size}`, className)}
      onClick={handleClick}
    >
      <Slottable>{children}</Slottable>
    </Comp>
  );
}

// packages/angular/src/components/actions/toggle.ts
// Botão de dois estados (pressionado/solto), fora de um grupo. Fonte da verdade: packages/react/src/components/actions/toggle.tsx.
import { Directive, booleanAttribute, computed, input, model } from '@angular/core';
import type { Size } from '@fewcompany/core';
import { dataAttr } from '../../lib/attrs.js';

export type ToggleVariant = 'primary' | 'secondary';

/** `<button fewToggle [(pressed)]="bold">N</button>` */
@Directive({
  selector: '[fewToggle]',
  host: {
    class: 'few-toggle',
    '[class]': 'variantClasses()',
    type: 'button',
    '[attr.aria-pressed]': 'pressed()',
    '[attr.disabled]': 'disabled() ? "" : null',
    '[attr.data-state]': 'pressed() ? "on" : "off"',
    '[attr.data-disabled]': 'dataAttr(disabled())',
    '(click)': 'handleClick()',
  },
})
export class FewToggle {
  readonly pressed = model(false);
  readonly size = input<Size>('md');
  readonly variant = input<ToggleVariant>('secondary');
  readonly disabled = input(false, { transform: booleanAttribute });

  protected readonly variantClasses = computed(() => `few-toggle--${this.variant()} few-toggle--${this.size()}`);
  protected readonly dataAttr = dataAttr;

  protected handleClick() {
    if (this.disabled()) return;
    this.pressed.set(!this.pressed());
  }
}
