// packages/react/src/components/actions/toggle-group.tsx
"use client";
import { useLayoutEffect, useRef, useState, type ComponentProps, type FocusEvent, type KeyboardEvent, type MouseEvent } from 'react';
import type { Orientation, Size } from '@fewcompany/core';
import { toggleGroupValue, isToggleGroupItemSelected, type ToggleGroupType, type ToggleGroupValue } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';
import { moveFocus, focusableItems } from '../../lib/roving.js';
import type { ToggleVariant } from './toggle.js';

interface ToggleGroupContextValue {
  type: ToggleGroupType;
  isSelected: (value: string) => boolean;
  toggle: (value: string) => void;
  disabled?: boolean;
  variant?: ToggleVariant;
  size?: Size;
  orientation: Orientation;
  rovingFocus: boolean;
  activeValue: string | null;
  setActiveValue: (value: string) => void;
}
const [ToggleGroupProvider, useToggleGroup] = createContext<ToggleGroupContextValue>('ToggleGroup');

interface ToggleGroupSharedProps extends ComponentProps<'div'> {
  asChild?: boolean;
  orientation?: Orientation;
  disabled?: boolean;
  /** Setas movem e focam o item (roving tabindex). Padrão true. */
  rovingFocus?: boolean;
  loop?: boolean;
  size?: Size;
  variant?: ToggleVariant;
}
export type ToggleGroupProps = ToggleGroupSharedProps & (
  | { type: 'single'; value?: string; defaultValue?: string; onValueChange?: (value: string) => void }
  | { type: 'multiple'; value?: string[]; defaultValue?: string[]; onValueChange?: (value: string[]) => void }
);
type ToggleGroupInternalProps = ToggleGroupSharedProps & { type: ToggleGroupType; value?: ToggleGroupValue; defaultValue?: ToggleGroupValue; onValueChange?: (value: ToggleGroupValue) => void };

function ToggleGroupRoot(allProps: ToggleGroupProps) {
  const { asChild, type, orientation = 'horizontal', disabled, rovingFocus = true, loop = true, size, variant, className, value, defaultValue, onValueChange, onKeyDown, ...props } = allProps as ToggleGroupInternalProps;
  const empty: ToggleGroupValue = type === 'multiple' ? [] : '';
  const [current, setCurrent] = useControllableState<ToggleGroupValue>({ value, defaultValue: defaultValue ?? empty, onChange: onValueChange });
  const [activeValue, setActiveValue] = useState<string | null>(null);
  const ref = useRef<HTMLDivElement>(null);

  // Item selecionado é o padrão de foco; sem seleção, cai no primeiro item (roving focus).
  useLayoutEffect(() => {
    if (activeValue !== null) return;
    const items = focusableItems(ref.current, '[data-few-toggle-item]');
    const preferred = items.find(item => item.dataset.state === 'on') ?? items[0];
    if (preferred?.dataset.value !== undefined) setActiveValue(preferred.dataset.value);
  }, [activeValue]);

  function handleKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented || !rovingFocus) return;
    const target = moveFocus(ref.current, '[data-few-toggle-item]', event.key, { orientation, loop });
    if (target) event.preventDefault();
  }

  const Comp = asChild ? Slot : 'div';
  return (
    <ToggleGroupProvider value={{
      type, disabled, variant, size, orientation, rovingFocus, activeValue, setActiveValue,
      isSelected: itemValue => isToggleGroupItemSelected(type, current, itemValue),
      toggle: itemValue => setCurrent(toggleGroupValue(type, current, itemValue)),
    }}>
      <Comp
        {...props}
        ref={ref}
        role={type === 'single' ? 'radiogroup' : 'group'}
        aria-orientation={orientation}
        data-orientation={orientation}
        data-disabled={dataAttr(disabled)}
        className={cx('few-toggle-group', className)}
        onKeyDown={handleKeyDown}
      />
    </ToggleGroupProvider>
  );
}

export interface ToggleGroupItemProps extends ComponentProps<'button'> { asChild?: boolean; value: string }
function ToggleGroupItem({ asChild, value, disabled: itemDisabled, className, onClick, onFocus, ...props }: ToggleGroupItemProps) {
  const ctx = useToggleGroup('ToggleGroup.Item');
  const selected = ctx.isSelected(value);
  const disabled = ctx.disabled || itemDisabled;
  const tabbable = ctx.rovingFocus ? ctx.activeValue === value : true;
  const Comp = asChild ? Slot : 'button';

  function handleClick(event: MouseEvent<HTMLButtonElement>) {
    onClick?.(event);
    if (event.defaultPrevented || disabled) return;
    ctx.toggle(value);
    ctx.setActiveValue(value);
  }
  function handleFocus(event: FocusEvent<HTMLButtonElement>) {
    onFocus?.(event);
    if (ctx.rovingFocus) ctx.setActiveValue(value);
  }

  return (
    <Comp
      {...props}
      data-few-toggle-item=""
      type={asChild ? undefined : 'button'}
      role={ctx.type === 'single' ? 'radio' : undefined}
      aria-checked={ctx.type === 'single' ? selected : undefined}
      aria-pressed={ctx.type === 'multiple' ? selected : undefined}
      tabIndex={tabbable ? 0 : -1}
      disabled={disabled}
      data-state={selected ? 'on' : 'off'}
      data-disabled={dataAttr(disabled)}
      data-value={value}
      className={cx('few-toggle-group-item', ctx.variant && `few-toggle-group-item--${ctx.variant}`, ctx.size && `few-toggle-group-item--${ctx.size}`, className)}
      onClick={handleClick}
      onFocus={handleFocus}
    />
  );
}

/** Conjunto de opções alternáveis. single = radiogroup/radio, multiple = botões independentes com aria-pressed. Roving focus por setas. */
export const ToggleGroup = Object.assign(ToggleGroupRoot, { Root: ToggleGroupRoot, Item: ToggleGroupItem });
export { ToggleGroupRoot, ToggleGroupItem };

// packages/angular/src/components/actions/toggle-group.ts
// Conjunto de opções alternáveis. Fonte da verdade: packages/react/src/components/actions/toggle-group.tsx.
import { Directive, ElementRef, booleanAttribute, computed, effect, inject, input, model, signal } from '@angular/core';
import type { Orientation, Size, ToggleGroupType, ToggleGroupValue } from '@fewcompany/core';
import { isToggleGroupItemSelected, toggleGroupValue } from '@fewcompany/core';
import { dataAttr } from '../../lib/attrs.js';
import { focusableItems, moveFocus } from '../../lib/roving.js';
import type { ToggleVariant } from './toggle.js';

/**
 * Raiz: `<div fewToggleGroup type="single" [(value)]="align">…</div>`.
 * single = radiogroup/radio (`FewToggleGroupItem` alterna sozinho); multiple = group com aria-pressed independentes.
 * Roving focus por setas (Home/End); o item ativo é o selecionado ou, sem seleção, o primeiro.
 */
@Directive({
  selector: '[fewToggleGroup]',
  exportAs: 'fewToggleGroup',
  host: {
    class: 'few-toggle-group',
    '[attr.role]': 'type() === "single" ? "radiogroup" : "group"',
    '[attr.aria-orientation]': 'orientation()',
    '[attr.data-orientation]': 'orientation()',
    '[attr.data-disabled]': 'dataAttr(disabled())',
    '(keydown)': 'onKeydown($event)',
  },
})
export class FewToggleGroup {
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly activeValue = signal<string | null>(null);

  readonly type = input<ToggleGroupType>('single');
  readonly value = model<ToggleGroupValue>('');
  readonly orientation = input<Orientation>('horizontal');
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Setas movem e focam o item (roving tabindex). Padrão true. */
  readonly rovingFocus = input(true, { transform: booleanAttribute });
  readonly loop = input(true, { transform: booleanAttribute });
  readonly size = input<Size>();
  readonly variant = input<ToggleVariant>();

  protected readonly dataAttr = dataAttr;

  constructor() {
    // Item selecionado é o padrão de foco; sem seleção, cai no primeiro item (roving focus).
    effect(() => {
      if (typeof document === 'undefined' || this.activeValue() !== null) return;
      const items = focusableItems(this.host.nativeElement, '[data-few-toggle-item]');
      const preferred = items.find(item => item.dataset['state'] === 'on') ?? items[0];
      const preferredValue = preferred?.dataset['value'];
      if (preferredValue !== undefined) this.activeValue.set(preferredValue);
    });
  }

  isSelected(itemValue: string): boolean { return isToggleGroupItemSelected(this.type(), this.value(), itemValue); }
  toggle(itemValue: string) { this.value.set(toggleGroupValue(this.type(), this.value(), itemValue)); }
  isTabbable(itemValue: string): boolean { return this.rovingFocus() ? this.activeValue() === itemValue : true; }
  setActive(itemValue: string) { this.activeValue.set(itemValue); }

  protected onKeydown(event: KeyboardEvent) {
    if (event.defaultPrevented || !this.rovingFocus()) return;
    const target = moveFocus(this.host.nativeElement, '[data-few-toggle-item]', event.key, { orientation: this.orientation(), loop: this.loop() });
    if (target) event.preventDefault();
  }
}

/** Item: `<button fewToggleGroupItem value="left">Esquerda</button>`. */
@Directive({
  selector: '[fewToggleGroupItem]',
  host: {
    class: 'few-toggle-group-item',
    'data-few-toggle-item': '',
    type: 'button',
    '[class]': 'variantClasses()',
    '[attr.role]': 'role',
    '[attr.aria-checked]': 'ariaChecked',
    '[attr.aria-pressed]': 'ariaPressed',
    '[attr.tabindex]': 'tabbable() ? 0 : -1',
    '[attr.disabled]': 'isDisabled() ? "" : null',
    '[attr.data-state]': 'selected() ? "on" : "off"',
    '[attr.data-disabled]': 'dataAttr(isDisabled())',
    '[attr.data-value]': 'value()',
    '(click)': 'handleClick()',
    '(focus)': 'handleFocus()',
  },
})
export class FewToggleGroupItem {
  private readonly group = inject(FewToggleGroup);

  readonly value = input.required<string>();
  readonly disabled = input(false, { transform: booleanAttribute });

  protected readonly selected = computed(() => this.group.isSelected(this.value()));
  protected readonly isDisabled = computed(() => this.group.disabled() || this.disabled());
  protected readonly tabbable = computed(() => this.group.isTabbable(this.value()));
  protected readonly variantClasses = computed(() => {
    const variant = this.group.variant();
    const size = this.group.size();
    return [variant && `few-toggle-group-item--${variant}`, size && `few-toggle-group-item--${size}`].filter(Boolean).join(' ');
  });
  protected readonly dataAttr = dataAttr;

  protected get role(): string | null { return this.group.type() === 'single' ? 'radio' : null; }
  protected get ariaChecked(): boolean | null { return this.group.type() === 'single' ? this.selected() : null; }
  protected get ariaPressed(): boolean | null { return this.group.type() === 'multiple' ? this.selected() : null; }

  protected handleClick() {
    if (this.isDisabled()) return;
    this.group.toggle(this.value());
    this.group.setActive(this.value());
  }
  protected handleFocus() {
    if (this.group.rovingFocus()) this.group.setActive(this.value());
  }
}

/** Importe tudo de uma vez: `imports: [FEW_TOGGLE_GROUP]`. */
export const FEW_TOGGLE_GROUP = [FewToggleGroup, FewToggleGroupItem] as const;
