// packages/angular/src/components/pickers/combobox.ts
// Combobox: Input de texto que filtra opções (contains, sem acento) via filterOptions do core.
// O foco permanece no Input; a opção "ativa" é sinalizada por aria-activedescendant (não move foco real).
// Fonte da verdade: packages/react/src/components/pickers/combobox.tsx. Ver docs/composition-angular.md.
import {
  Component, Directive, DestroyRef, ElementRef, afterNextRender, booleanAttribute, computed, inject, input, model, signal,
} from '@angular/core';
import { filterOptions, nextIndex, type FloatingAlign, type FloatingSide } from '@fewcompany/core';
import { fewId } from '../../lib/ids.js';
import { setupDismiss } from '../../lib/dismiss.js';
import { setupPosition } from '../../lib/position.js';
import { setupTopLayer } from '../../lib/top-layer.js';
import { dataAttr, dataState } from '../../lib/attrs.js';

interface ComboboxItemData { value: string; label: string; disabled?: boolean }

/** Raiz: `<div fewCombobox [(value)]="valor" [(inputValue)]="texto">`. */
@Directive({ selector: '[fewCombobox]', exportAs: 'fewCombobox', host: { class: 'few-combobox', '[attr.data-disabled]': 'dataAttr(disabled())' } })
export class FewCombobox {
  readonly value = model<string>('');
  readonly inputValue = model<string>('');
  readonly open = model(false);
  readonly disabled = input(false, { transform: booleanAttribute });
  /** Permite confirmar (Enter) um texto que não corresponde a nenhuma opção. */
  readonly allowCustomValue = input(false, { transform: booleanAttribute });
  readonly baseId = fewId('combobox');
  protected readonly dataAttr = dataAttr;

  private readonly activeValueState = signal<string | null>(null);
  readonly activeValue = this.activeValueState.asReadonly();
  private readonly itemsState = signal<ComboboxItemData[]>([]);
  readonly items = this.itemsState.asReadonly();
  private readonly inputElementState = signal<HTMLInputElement | null>(null);
  readonly visibleValues = computed(() => new Set(filterOptions(this.items(), this.inputValue(), item => item.label).map(item => item.value)));

  get contentId(): string { return `${this.baseId}-content`; }
  get inputId(): string { return `${this.baseId}-input`; }
  setValue(value: string): void { this.value.set(value); }
  setInputValue(value: string): void { this.inputValue.set(value); }
  setOpen(open: boolean): void { this.open.set(open); }
  setActiveValue(value: string | null): void { this.activeValueState.set(value); }
  registerItem(item: ComboboxItemData): void { this.itemsState.update(prev => [...prev.filter(i => i.value !== item.value), item]); }
  unregisterItem(value: string): void { this.itemsState.update(prev => prev.filter(i => i.value !== value)); }
  setInputElement(element: HTMLInputElement): void { this.inputElementState.set(element); }
  inputElement(): HTMLInputElement | null { return this.inputElementState(); }
  focusInput(): void { this.inputElementState()?.focus(); }
}

@Directive({
  selector: 'input[fewComboboxInput]',
  host: {
    class: 'few-combobox-input', type: 'text', role: 'combobox', autocomplete: 'off',
    '[id]': 'combobox.inputId', '[attr.aria-autocomplete]': "'list'", '[attr.aria-expanded]': 'combobox.open()',
    '[attr.aria-controls]': 'combobox.contentId', '[attr.aria-activedescendant]': 'activeDescendant()',
    '[attr.disabled]': 'isDisabled() ? "" : null', '[value]': 'combobox.inputValue()', '[attr.data-state]': 'dataState(combobox.open())',
    '(focus)': 'onFocus()', '(input)': 'onInput($event)', '(keydown)': 'onKeydown($event)',
  },
})
export class FewComboboxInput {
  protected readonly combobox = inject(FewCombobox);
  private readonly el = inject<ElementRef<HTMLInputElement>>(ElementRef);
  /** Sobrepõe o `disabled` do Root quando definido. */
  readonly disabled = input<boolean>();
  protected readonly dataState = dataState;
  protected readonly isDisabled = computed(() => this.disabled() ?? this.combobox.disabled());
  protected readonly activeDescendant = computed(() => {
    const active = this.combobox.activeValue();
    return active ? `${this.combobox.baseId}-item-${active}` : null;
  });
  constructor() { this.combobox.setInputElement(this.el.nativeElement); }
  protected onFocus(): void { if (!this.isDisabled()) this.combobox.setOpen(true); }
  protected onInput(event: Event): void {
    this.combobox.setInputValue((event.target as HTMLInputElement).value);
    this.combobox.setOpen(true);
    this.combobox.setActiveValue(null);
  }
  protected onKeydown(event: KeyboardEvent): void {
    if (event.defaultPrevented || this.isDisabled()) return;
    const navigable = this.combobox.items().filter(item => this.combobox.visibleValues().has(item.value) && !item.disabled);
    const currentIndex = navigable.findIndex(item => item.value === this.combobox.activeValue());
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp' || event.key === 'Home' || event.key === 'End') {
      event.preventDefault();
      this.combobox.setOpen(true);
      const idx = nextIndex(event.key, currentIndex, navigable.length, { orientation: 'vertical', loop: false });
      if (idx !== null && navigable[idx]) this.combobox.setActiveValue(navigable[idx].value);
      return;
    }
    if (event.key === 'Enter') {
      event.preventDefault();
      const active = navigable.find(item => item.value === this.combobox.activeValue());
      if (active) { this.combobox.setValue(active.value); this.combobox.setInputValue(active.label); this.combobox.setOpen(false); }
      else if (this.combobox.allowCustomValue() && this.combobox.inputValue()) { this.combobox.setValue(this.combobox.inputValue()); this.combobox.setOpen(false); }
    }
  }
}

/** Botão decorativo que alterna o painel e devolve o foco ao Input; sem conteúdo projetado, mostra "▾". */
@Component({
  selector: '[fewComboboxTrigger]',
  host: { class: 'few-combobox-trigger', type: 'button', tabindex: '-1', 'aria-hidden': 'true', '[attr.disabled]': 'combobox.disabled() ? "" : null', '(click)': 'onClick()' },
  template: `<ng-content />@if (noContent()) {<span>▾</span>}`,
})
export class FewComboboxTrigger {
  protected readonly combobox = inject(FewCombobox);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  protected readonly noContent = signal(false);
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
  protected onClick(): void { this.combobox.setOpen(!this.combobox.open()); this.combobox.focusInput(); }
}

@Directive({
  selector: '[fewComboboxContent]',
  host: {
    class: 'few-combobox-content', role: 'listbox', popover: 'manual',
    '[id]': 'combobox.contentId', '[attr.aria-labelledby]': 'combobox.inputId',
    '[attr.data-state]': 'dataState(combobox.open())', '[attr.data-side]': 'position().side',
    '[style.position]': "'fixed'", '[style.top.px]': 'position().top', '[style.left.px]': 'position().left', '[style.width.px]': 'position().width',
  },
})
export class FewComboboxContent {
  protected readonly combobox = inject(FewCombobox);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly side = input<FloatingSide>('bottom');
  readonly align = input<FloatingAlign>('start');
  protected readonly dataState = dataState;
  protected readonly position = setupPosition(
    this.combobox.open, () => this.combobox.inputElement(), () => this.el.nativeElement,
    () => ({ side: this.side(), align: this.align(), matchWidth: true }),
  );
  constructor() {
    setupTopLayer(this.combobox.open, () => this.el.nativeElement);
    setupDismiss(this.combobox.open, () => this.combobox.setOpen(false), () => [this.combobox.inputElement(), this.el.nativeElement]);
  }
}

@Directive({ selector: '[fewComboboxGroup]', host: { class: 'few-combobox-group', role: 'group' } })
export class FewComboboxGroup {}

@Directive({ selector: '[fewComboboxLabel]', host: { class: 'few-combobox-label' } })
export class FewComboboxLabel {}

@Directive({
  selector: '[fewComboboxItem]',
  host: {
    class: 'few-combobox-item', role: 'option',
    '[id]': 'id', '[hidden]': '!visible()',
    '[attr.aria-selected]': 'selected()', '[attr.aria-disabled]': 'disabled() ? "true" : null',
    '[attr.data-state]': 'selected() ? "checked" : "unchecked"', '[attr.data-highlighted]': 'dataAttr(highlighted())', '[attr.data-disabled]': 'dataAttr(disabled())', '[attr.data-value]': 'value()',
    '(pointermove)': 'onPointerMove()', '(click)': 'onClick()',
  },
})
export class FewComboboxItem {
  private readonly combobox = inject(FewCombobox);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly value = input.required<string>();
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly textValue = input<string>();
  protected readonly dataAttr = dataAttr;
  readonly selected = computed(() => this.combobox.value() === this.value());
  protected readonly visible = computed(() => this.combobox.visibleValues().has(this.value()));
  protected readonly highlighted = computed(() => this.combobox.activeValue() === this.value());
  protected get id(): string { return `${this.combobox.baseId}-item-${this.value()}`; }

  constructor() {
    afterNextRender(() => this.combobox.registerItem({ value: this.value(), label: this.textValue() ?? this.el.nativeElement.textContent ?? this.value(), disabled: this.disabled() }));
    inject(DestroyRef).onDestroy(() => this.combobox.unregisterItem(this.value()));
  }

  protected onPointerMove(): void { if (!this.disabled()) this.combobox.setActiveValue(this.value()); }
  protected onClick(): void {
    if (this.disabled()) return;
    this.combobox.setValue(this.value());
    this.combobox.setInputValue(this.textValue() ?? this.el.nativeElement.textContent ?? this.value());
    this.combobox.setOpen(false);
    this.combobox.focusInput();
  }
}

@Directive({ selector: '[fewComboboxItemText]', host: { class: 'few-combobox-item-text' } })
export class FewComboboxItemText {}

/** Só visível quando o Item pai está selecionado, salvo `forceMount`. Sem conteúdo projetado, mostra "✓". */
@Component({
  selector: '[fewComboboxItemIndicator]',
  host: { class: 'few-combobox-item-indicator', 'aria-hidden': 'true', '[hidden]': '!item.selected() && !forceMount()' },
  template: `<ng-content />@if (noContent()) {<span>✓</span>}`,
})
export class FewComboboxItemIndicator {
  protected readonly item = inject(FewComboboxItem);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly forceMount = input(false, { transform: booleanAttribute });
  protected readonly noContent = signal(false);
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
}

/** Mensagem de nenhum resultado; fica oculta enquanto houver itens registrados e algum visível. */
@Directive({ selector: '[fewComboboxEmpty]', host: { class: 'few-combobox-empty', role: 'status', '[hidden]': 'hasVisibleItems()' } })
export class FewComboboxEmpty {
  private readonly combobox = inject(FewCombobox);
  protected readonly hasVisibleItems = computed(() => this.combobox.items().length > 0 && this.combobox.visibleValues().size > 0);
}

/** Importe tudo de uma vez: `imports: [FEW_COMBOBOX]`. */
export const FEW_COMBOBOX = [
  FewCombobox, FewComboboxInput, FewComboboxTrigger, FewComboboxContent,
  FewComboboxGroup, FewComboboxLabel, FewComboboxItem, FewComboboxItemText, FewComboboxItemIndicator, FewComboboxEmpty,
] as const;

// packages/react/src/components/pickers/combobox.tsx
"use client";
// Combobox: Input de texto que filtra opções (contains, sem acento) via filterOptions do core.
// O foco permanece no Input; a opção "ativa" é sinalizada por aria-activedescendant (não move foco real).
// Ver docs/composition.md.
import { useCallback, useEffect, useId, useMemo, useRef, useState, type ComponentProps, type RefObject } from 'react';
import { filterOptions, nextIndex } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';
import { useDismiss } from '../../lib/use-dismiss.js';
import { usePosition, type Side, type Align } from '../../lib/use-position.js';
import { useTopLayer } from '../../lib/use-top-layer.js';

interface ComboboxItemData { value: string; label: string; disabled?: boolean }
interface ComboboxContextValue {
  baseId: string;
  value: string; setValue: (value: string) => void;
  inputValue: string; setInputValue: (value: string) => void;
  open: boolean; setOpen: (open: boolean) => void;
  disabled?: boolean; allowCustomValue: boolean;
  activeValue: string | null; setActiveValue: (value: string | null) => void;
  items: ComboboxItemData[];
  registerItem: (item: ComboboxItemData) => void;
  unregisterItem: (value: string) => void;
  visibleValues: Set<string>;
  inputRef: RefObject<HTMLInputElement | null>;
  contentRef: RefObject<HTMLDivElement | null>;
}
const [ComboboxProvider, useCombobox] = createContext<ComboboxContextValue>('Combobox');
const [ComboboxItemProvider, useComboboxItemState] = createContext<{ selected: boolean; disabled?: boolean }>('Combobox.Item');

export interface ComboboxProps extends Omit<ComponentProps<'div'>, 'defaultValue' | 'onChange'> {
  asChild?: boolean;
  value?: string; defaultValue?: string; onValueChange?: (value: string) => void;
  inputValue?: string; defaultInputValue?: string; onInputValueChange?: (value: string) => void;
  open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
  /** Permite confirmar (Enter) um texto que não corresponde a nenhuma opção. */
  allowCustomValue?: boolean;
}
function ComboboxRoot({ asChild, value: valueProp, defaultValue = '', onValueChange, inputValue: inputValueProp, defaultInputValue = '', onInputValueChange, open: openProp, defaultOpen = false, onOpenChange, disabled, allowCustomValue = false, className, children, ...props }: ComboboxProps) {
  const baseId = useId();
  const [value, setValue] = useControllableState({ value: valueProp, defaultValue, onChange: onValueChange });
  const [inputValue, setInputValue] = useControllableState({ value: inputValueProp, defaultValue: defaultInputValue, onChange: onInputValueChange });
  const [open, setOpen] = useControllableState({ value: openProp, defaultValue: defaultOpen, onChange: onOpenChange });
  const [activeValue, setActiveValue] = useState<string | null>(null);
  const [items, setItems] = useState<ComboboxItemData[]>([]);
  const registerItem = useCallback((item: ComboboxItemData) => setItems(prev => [...prev.filter(i => i.value !== item.value), item]), []);
  const unregisterItem = useCallback((itemValue: string) => setItems(prev => prev.filter(i => i.value !== itemValue)), []);
  const inputRef = useRef<HTMLInputElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const visibleValues = useMemo(() => new Set(filterOptions(items, inputValue, item => item.label).map(item => item.value)), [items, inputValue]);
  const Comp = asChild ? Slot : 'div';
  return (
    <ComboboxProvider value={{ baseId, value, setValue, inputValue, setInputValue, open, setOpen, disabled, allowCustomValue, activeValue, setActiveValue, items, registerItem, unregisterItem, visibleValues, inputRef, contentRef }}>
      <Comp {...props} className={cx('few-combobox', className)} data-disabled={dataAttr(disabled)}>{children}</Comp>
    </ComboboxProvider>
  );
}

export interface ComboboxInputProps extends Omit<ComponentProps<'input'>, 'value' | 'defaultValue'> { asChild?: boolean }
function ComboboxInput({ asChild, className, onChange, onKeyDown, onFocus, disabled: disabledProp, ...props }: ComboboxInputProps) {
  const ctx = useCombobox('Combobox.Input');
  const disabled = disabledProp ?? ctx.disabled;
  const Comp = asChild ? Slot : 'input';
  return (
    <Comp {...props} ref={ctx.inputRef} type="text" role="combobox" id={`${ctx.baseId}-input`} autoComplete="off"
      aria-autocomplete="list" aria-expanded={ctx.open} aria-controls={`${ctx.baseId}-content`}
      aria-activedescendant={ctx.activeValue ? `${ctx.baseId}-item-${ctx.activeValue}` : undefined}
      disabled={disabled} value={ctx.inputValue} data-state={ctx.open ? 'open' : 'closed'}
      className={cx('few-combobox-input', className)}
      onFocus={(event) => { onFocus?.(event); if (!disabled) ctx.setOpen(true); }}
      onChange={(event) => {
        onChange?.(event);
        if (event.defaultPrevented) return;
        ctx.setInputValue(event.target.value);
        ctx.setOpen(true);
        ctx.setActiveValue(null);
      }}
      onKeyDown={(event) => {
        onKeyDown?.(event);
        if (event.defaultPrevented || disabled) return;
        const navigable = ctx.items.filter(item => ctx.visibleValues.has(item.value) && !item.disabled);
        const currentIndex = navigable.findIndex(item => item.value === ctx.activeValue);
        if (event.key === 'ArrowDown' || event.key === 'ArrowUp' || event.key === 'Home' || event.key === 'End') {
          event.preventDefault();
          ctx.setOpen(true);
          const idx = nextIndex(event.key, currentIndex, navigable.length, { orientation: 'vertical', loop: false });
          if (idx !== null && navigable[idx]) ctx.setActiveValue(navigable[idx].value);
          return;
        }
        if (event.key === 'Enter') {
          event.preventDefault();
          const active = navigable.find(item => item.value === ctx.activeValue);
          if (active) { ctx.setValue(active.value); ctx.setInputValue(active.label); ctx.setOpen(false); }
          else if (ctx.allowCustomValue && ctx.inputValue) { ctx.setValue(ctx.inputValue); ctx.setOpen(false); }
        }
      }} />
  );
}

export interface ComboboxTriggerProps extends ComponentProps<'button'> { asChild?: boolean }
function ComboboxTrigger({ asChild, className, onClick, ...props }: ComboboxTriggerProps) {
  const ctx = useCombobox('Combobox.Trigger');
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp {...props} type="button" tabIndex={-1} aria-hidden="true" disabled={ctx.disabled} className={cx('few-combobox-trigger', className)}
      onClick={(event) => { onClick?.(event); if (event.defaultPrevented) return; ctx.setOpen(!ctx.open); ctx.inputRef.current?.focus(); }}>
      {props.children ?? '▾'}
    </Comp>
  );
}

export interface ComboboxContentProps extends ComponentProps<'div'> { asChild?: boolean; side?: Side; align?: Align }
function ComboboxContent({ asChild, side = 'bottom', align = 'start', className, style, ...props }: ComboboxContentProps) {
  const ctx = useCombobox('Combobox.Content');
  const position = usePosition(ctx.inputRef, ctx.contentRef, { side, align, matchWidth: true, open: ctx.open });
  useTopLayer(ctx.contentRef, ctx.open);
  useDismiss(ctx.open, () => ctx.setOpen(false), [ctx.inputRef, ctx.contentRef]);
  const Comp = asChild ? Slot : 'div';
  return (
    <Comp {...props} ref={ctx.contentRef} popover="manual" role="listbox" id={`${ctx.baseId}-content`} aria-labelledby={`${ctx.baseId}-input`}
      data-state={ctx.open ? 'open' : 'closed'} data-side={position.side} className={cx('few-combobox-content', className)}
      style={{ ...position.style, ...style }} />
  );
}

export interface ComboboxGroupProps extends ComponentProps<'div'> { asChild?: boolean }
function ComboboxGroup({ asChild, className, ...props }: ComboboxGroupProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} role="group" className={cx('few-combobox-group', className)} />;
}

export interface ComboboxLabelProps extends ComponentProps<'div'> { asChild?: boolean }
function ComboboxLabel({ asChild, className, ...props }: ComboboxLabelProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} className={cx('few-combobox-label', className)} />;
}

export interface ComboboxItemProps extends ComponentProps<'div'> { asChild?: boolean; value: string; disabled?: boolean; textValue?: string }
function ComboboxItem({ asChild, value, disabled, textValue, className, children, onClick, onPointerMove, ...props }: ComboboxItemProps) {
  const ctx = useCombobox('Combobox.Item');
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    ctx.registerItem({ value, label: textValue ?? ref.current?.textContent ?? value, disabled });
    return () => ctx.unregisterItem(value);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value, textValue, disabled]);
  const visible = ctx.visibleValues.has(value);
  const selected = ctx.value === value;
  const highlighted = ctx.activeValue === value;
  const Comp = asChild ? Slot : 'div';
  if (!visible) return null;
  return (
    <ComboboxItemProvider value={{ selected, disabled }}>
      <Comp {...props} ref={ref} role="option" id={`${ctx.baseId}-item-${value}`} aria-selected={selected} aria-disabled={disabled}
        data-state={selected ? 'checked' : 'unchecked'} data-highlighted={dataAttr(highlighted)} data-disabled={dataAttr(disabled)} data-value={value}
        className={cx('few-combobox-item', className)}
        onPointerMove={(event) => { onPointerMove?.(event); if (!disabled) ctx.setActiveValue(value); }}
        onClick={(event) => {
          onClick?.(event);
          if (event.defaultPrevented || disabled) return;
          ctx.setValue(value);
          ctx.setInputValue(textValue ?? ref.current?.textContent ?? value);
          ctx.setOpen(false);
          ctx.inputRef.current?.focus();
        }}>
        {children}
      </Comp>
    </ComboboxItemProvider>
  );
}

export interface ComboboxItemTextProps extends ComponentProps<'span'> { asChild?: boolean }
function ComboboxItemText({ asChild, className, ...props }: ComboboxItemTextProps) {
  const Comp = asChild ? Slot : 'span';
  return <Comp {...props} className={cx('few-combobox-item-text', className)} />;
}

export interface ComboboxItemIndicatorProps extends ComponentProps<'span'> { asChild?: boolean; forceMount?: boolean }
function ComboboxItemIndicator({ asChild, forceMount, className, children, ...props }: ComboboxItemIndicatorProps) {
  const item = useComboboxItemState('Combobox.ItemIndicator');
  const Comp = asChild ? Slot : 'span';
  if (!item.selected && !forceMount) return null;
  return <Comp {...props} aria-hidden="true" className={cx('few-combobox-item-indicator', className)}>{children ?? '✓'}</Comp>;
}

export interface ComboboxEmptyProps extends ComponentProps<'div'> { asChild?: boolean }
function ComboboxEmpty({ asChild, className, ...props }: ComboboxEmptyProps) {
  const ctx = useCombobox('Combobox.Empty');
  const Comp = asChild ? Slot : 'div';
  if (ctx.items.length > 0 && ctx.visibleValues.size > 0) return null;
  return <Comp {...props} role="status" className={cx('few-combobox-empty', className)} />;
}

/** Combobox composto: <Combobox><Combobox.Input/><Combobox.Content><Combobox.Item value="a">A</Combobox.Item><Combobox.Empty>Nada encontrado</Combobox.Empty></Combobox.Content></Combobox> */
export const Combobox = Object.assign(ComboboxRoot, {
  Root: ComboboxRoot, Input: ComboboxInput, Trigger: ComboboxTrigger, Content: ComboboxContent,
  Item: ComboboxItem, ItemText: ComboboxItemText, ItemIndicator: ComboboxItemIndicator, Empty: ComboboxEmpty,
  Group: ComboboxGroup, Label: ComboboxLabel,
});
export {
  ComboboxRoot, ComboboxInput, ComboboxTrigger, ComboboxContent,
  ComboboxItem, ComboboxItemText, ComboboxItemIndicator, ComboboxEmpty, ComboboxGroup, ComboboxLabel,
};
