// packages/angular/src/components/feedback/alert.ts
// Alert (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/feedback/alert.tsx.
import { Component, Directive, computed, inject, input, output } from '@angular/core';
import type { Tone } from '@fewcompany/core';

export type AlertVariant = 'soft' | 'outline';

const DEFAULT_ICON: Record<Tone, string> = { neutral: '•', success: '✓', warning: '!', danger: '!', info: 'i' };

/** Raiz: `<div fewAlert tone="success" variant="soft">`. role="alert" em danger, "status" nas demais tones. */
@Directive({
  selector: '[fewAlert]',
  exportAs: 'fewAlert',
  host: {
    '[class]': 'classes()',
    '[attr.role]': 'role()',
    '[attr.data-tone]': 'tone()',
    '[attr.data-variant]': 'variant()',
  },
})
export class FewAlert {
  readonly tone = input<Tone>('info');
  readonly variant = input<AlertVariant>('soft');
  protected readonly role = computed(() => (this.tone() === 'danger' ? 'alert' : 'status'));
  protected readonly classes = computed(() => `few-alert few-tone--${this.tone()} few-alert--${this.variant()}`);
}

/** Ícone: `<span fewAlertIcon></span>`. Sem conteúdo projetado, cai no ícone padrão da tone. */
@Component({
  selector: '[fewAlertIcon]',
  host: { class: 'few-alert-icon', 'aria-hidden': 'true' },
  template: `<ng-content>{{ defaultIcon() }}</ng-content>`,
})
export class FewAlertIcon {
  private readonly alert = inject(FewAlert);
  protected readonly defaultIcon = computed(() => DEFAULT_ICON[this.alert.tone()]);
}

@Directive({ selector: '[fewAlertTitle]', host: { class: 'few-alert-title' } })
export class FewAlertTitle {}

@Directive({ selector: '[fewAlertDescription]', host: { class: 'few-alert-description' } })
export class FewAlertDescription {}

@Directive({ selector: '[fewAlertAction]', host: { class: 'few-alert-action' } })
export class FewAlertAction {}

/** Fechar: `<button fewAlertClose (dismiss)="...">`. Sem conteúdo projetado, cai no × padrão. */
@Component({
  selector: '[fewAlertClose]',
  host: {
    class: 'few-alert-close', type: 'button',
    '[attr.aria-label]': 'ariaLabel()',
    '(click)': 'dismiss.emit()',
  },
  template: `<ng-content><span aria-hidden="true">×</span></ng-content>`,
})
export class FewAlertClose {
  readonly ariaLabel = input('Fechar', { alias: 'aria-label' });
  readonly dismiss = output<void>();
}

/** Importe tudo de uma vez: `imports: [FEW_ALERT]`. */
export const FEW_ALERT = [FewAlert, FewAlertIcon, FewAlertTitle, FewAlertDescription, FewAlertAction, FewAlertClose] as const;

// packages/react/src/components/feedback/alert.tsx
"use client";
import type { ComponentProps } from 'react';
import type { Tone } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { cx } from '../../lib/cx.js';

export type AlertVariant = 'soft' | 'outline';
interface AlertContextValue { tone: Tone; variant: AlertVariant }
const [AlertProvider, useAlert] = createContext<AlertContextValue>('Alert');

const DEFAULT_ICON: Record<Tone, string> = { neutral: '•', success: '✓', warning: '!', danger: '!', info: 'i' };

export interface AlertProps extends ComponentProps<'div'> {
  asChild?: boolean;
  tone?: Tone;
  /** soft: fundo tintado. outline: só borda colorida. */
  variant?: AlertVariant;
}
function AlertRoot({ asChild, tone = 'info', variant = 'soft', className, ...props }: AlertProps) {
  const Comp = asChild ? Slot : 'div';
  return (
    <AlertProvider value={{ tone, variant }}>
      <Comp
        {...props}
        role={tone === 'danger' ? 'alert' : 'status'}
        className={cx('few-alert', `few-tone--${tone}`, `few-alert--${variant}`, className)}
        data-tone={tone}
        data-variant={variant}
      />
    </AlertProvider>
  );
}

export interface AlertIconProps extends ComponentProps<'span'> { asChild?: boolean }
function AlertIcon({ asChild, className, children, ...props }: AlertIconProps) {
  const { tone } = useAlert('Alert.Icon');
  const Comp = asChild ? Slot : 'span';
  return <Comp {...props} aria-hidden="true" className={cx('few-alert-icon', className)}>{children ?? DEFAULT_ICON[tone]}</Comp>;
}

export interface AlertTitleProps extends ComponentProps<'strong'> { asChild?: boolean }
function AlertTitle({ asChild, className, ...props }: AlertTitleProps) {
  const Comp = asChild ? Slot : 'strong';
  return <Comp {...props} className={cx('few-alert-title', className)} />;
}

export interface AlertDescriptionProps extends ComponentProps<'div'> { asChild?: boolean }
function AlertDescription({ asChild, className, ...props }: AlertDescriptionProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} className={cx('few-alert-description', className)} />;
}

export interface AlertActionProps extends ComponentProps<'div'> { asChild?: boolean }
function AlertAction({ asChild, className, ...props }: AlertActionProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} className={cx('few-alert-action', className)} />;
}

export interface AlertCloseProps extends ComponentProps<'button'> { asChild?: boolean; onDismiss?: () => void }
function AlertClose({ asChild, className, children, onClick, onDismiss, 'aria-label': ariaLabel = 'Fechar', ...props }: AlertCloseProps) {
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp
      {...props}
      type="button"
      aria-label={ariaLabel}
      className={cx('few-alert-close', className)}
      onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) onDismiss?.(); }}
    >
      {children ?? <span aria-hidden="true">×</span>}
    </Comp>
  );
}

/** Alert composto: <Alert tone="success"><Alert.Icon /><Alert.Title>Ok</Alert.Title><Alert.Description>…</Alert.Description><Alert.Close onDismiss={...} /></Alert> */
export const Alert = Object.assign(AlertRoot, { Root: AlertRoot, Icon: AlertIcon, Title: AlertTitle, Description: AlertDescription, Action: AlertAction, Close: AlertClose });
export { AlertRoot, AlertIcon, AlertTitle, AlertDescription, AlertAction, AlertClose };
