// packages/angular/src/components/feedback/skeleton.ts
// Skeleton (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/feedback/skeleton.tsx.
// O "asChild" do React aqui não é o Slot/troca-de-tag do resto da lib (que não existe no Angular): é um wrapper
// literal que reserva o layout do conteúdo real por baixo do esqueleto. Por isso o input equivalente chama-se
// `wrap`, não `asChild` — evita confundir com a convenção "asChild não existe" do restante dos componentes.
import { Component, booleanAttribute, computed, input, numberAttribute } from '@angular/core';

export type SkeletonVariant = 'text' | 'circle' | 'rect';

/** Número vira "px" (mesma convenção do CSSProperties do React); string passa direto. */
function toCssLength(value: string | number | undefined): string | undefined {
  if (value === undefined) return undefined;
  return typeof value === 'number' ? `${value}px` : value;
}

/**
 * Componente simples. `<span fewSkeleton variant="text" [lines]="3"></span>` ou
 * `<span fewSkeleton wrap><few-avatar /></span>` para reservar o layout do conteúdo projetado.
 */
@Component({
  selector: '[fewSkeleton]',
  host: {
    'aria-hidden': 'true',
    '[class]': 'hostClasses()',
    '[style.width]': 'hostWidth()',
    '[style.height]': 'hostHeight()',
  },
  template: `
    @if (wrap()) {
      <span class="few-skeleton-content"><ng-content /></span>
      <span [class]="overlayClasses()"></span>
    } @else if (isLines()) {
      @for (line of lineIndexes(); track line) {
        <span
          class="few-skeleton few-skeleton--text"
          [class.few-skeleton--static]="!animate()"
          [style.width]="line === lines() - 1 ? (lineWidth() ?? '70%') : lineWidth()"
          [style.height]="lineHeight()"
        ></span>
      }
    }
  `,
})
export class FewSkeleton {
  readonly variant = input<SkeletonVariant>('text');
  readonly width = input<string | number>();
  readonly height = input<string | number>();
  /** Repete linhas de texto (só variant="text"; ignorado com `wrap`). */
  readonly lines = input(1, { transform: numberAttribute });
  /** Anima o pulse. Desligue para um frame estático (ex.: captura de tela). */
  readonly animate = input(true, { transform: booleanAttribute });
  /** Envolve o conteúdo projetado: esconde-o (aria-hidden) e mostra o esqueleto por cima, no mesmo espaço. */
  readonly wrap = input(false, { transform: booleanAttribute });

  protected readonly isLines = computed(() => !this.wrap() && this.variant() === 'text' && this.lines() > 1);
  protected readonly lineIndexes = computed(() => Array.from({ length: this.lines() }, (_, index) => index));

  protected readonly hostClasses = computed(() => {
    if (this.wrap()) return 'few-skeleton-wrap';
    if (this.isLines()) return 'few-skeleton-lines';
    return `few-skeleton few-skeleton--${this.variant()}${this.animate() ? '' : ' few-skeleton--static'}`;
  });
  protected readonly overlayClasses = computed(() => `few-skeleton few-skeleton-overlay few-skeleton--${this.variant()}${this.animate() ? '' : ' few-skeleton--static'}`);
  protected readonly lineWidth = computed(() => toCssLength(this.width()));
  protected readonly lineHeight = computed(() => toCssLength(this.height()));
  protected readonly hostWidth = computed(() => (this.isLines() ? undefined : this.lineWidth()));
  protected readonly hostHeight = computed(() => (this.isLines() ? undefined : this.lineHeight()));
}

export const FEW_SKELETON = [FewSkeleton] as const;

// packages/react/src/components/feedback/skeleton.tsx
"use client";
import type { ComponentProps, CSSProperties } from 'react';
import { cx } from '../../lib/cx.js';

export type SkeletonVariant = 'text' | 'circle' | 'rect';

export interface SkeletonProps extends ComponentProps<'span'> {
  variant?: SkeletonVariant;
  width?: CSSProperties['width'];
  height?: CSSProperties['height'];
  /** Repete linhas de texto (só variant="text"; ignorado quando asChild). */
  lines?: number;
  /** Anima o pulse. Desligue para um frame estático (ex.: captura de tela). */
  animate?: boolean;
  /**
   * Envolve `children`: esconde o conteúdo real (aria-hidden) e mostra o esqueleto por cima,
   * no mesmo espaço do conteúdo. Não é o Slot/troca-de-tag do resto da biblioteca — aqui
   * "asChild" é literal: existe um wrapper, porque o objetivo é reservar o layout final.
   */
  asChild?: boolean;
}
/** Componente simples. `<Skeleton variant="text" lines={3} />` ou `<Skeleton asChild><Avatar /></Skeleton>`. */
export function Skeleton({ variant = 'text', width, height, lines = 1, animate = true, asChild, className, style, children, ...props }: SkeletonProps) {
  const baseStyle: CSSProperties = { width, height, ...style };

  if (asChild) {
    return (
      <span {...props} aria-hidden="true" className={cx('few-skeleton-wrap', className)} style={baseStyle}>
        <span className="few-skeleton-content">{children}</span>
        <span className={cx('few-skeleton', 'few-skeleton-overlay', `few-skeleton--${variant}`, !animate && 'few-skeleton--static')} />
      </span>
    );
  }

  if (variant === 'text' && lines > 1) {
    return (
      <span {...props} aria-hidden="true" className={cx('few-skeleton-lines', className)} style={style}>
        {Array.from({ length: lines }, (_, index) => (
          <span
            key={index}
            className={cx('few-skeleton', 'few-skeleton--text', !animate && 'few-skeleton--static')}
            style={index === lines - 1 ? { ...baseStyle, width: width ?? '70%' } : baseStyle}
          />
        ))}
      </span>
    );
  }

  return (
    <span
      {...props}
      aria-hidden="true"
      className={cx('few-skeleton', `few-skeleton--${variant}`, !animate && 'few-skeleton--static', className)}
      style={baseStyle}
    />
  );
}
