// packages/angular/src/components/feedback/spinner.ts
// Spinner (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/feedback/spinner.tsx.
import { Component, computed, input } from '@angular/core';
import type { Tone, Size } from '@fewcompany/core';
import { FewVisuallyHidden } from '../utilities/visually-hidden.js';

/** Componente simples: `<span fewSpinner label="Carregando pedidos"></span>`. role="status" já anuncia o label sr-only. */
@Component({
  selector: '[fewSpinner]',
  host: { '[class]': 'classes()', role: 'status' },
  imports: [FewVisuallyHidden],
  template: `<span class="few-spinner" aria-hidden="true"></span><span fewVisuallyHidden>{{ label() }}</span>`,
})
export class FewSpinner {
  readonly size = input<Size>('md');
  readonly tone = input<Tone>('neutral');
  /** Texto sr-only anunciado pelo leitor de tela. */
  readonly label = input('Carregando');
  protected readonly classes = computed(() => `few-spinner-root few-spinner-root--${this.size()} few-tone--${this.tone()}`);
}

export const FEW_SPINNER = [FewSpinner] as const;

// packages/react/src/components/feedback/spinner.tsx
"use client";
import type { ComponentProps } from 'react';
import type { Tone, Size } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { VisuallyHidden } from '../../lib/visually-hidden.js';
import { cx } from '../../lib/cx.js';

export interface SpinnerProps extends ComponentProps<'span'> {
  asChild?: boolean;
  size?: Size;
  tone?: Tone;
  /** Texto sr-only anunciado pelo leitor de tela. */
  label?: string;
}
/** Componente simples: <Spinner label="Carregando pedidos" />. role="status" já anuncia o label sr-only. */
export function Spinner({ asChild, size = 'md', tone = 'neutral', label = 'Carregando', className, ...props }: SpinnerProps) {
  const Comp = asChild ? Slot : 'span';
  return (
    <Comp {...props} role="status" className={cx('few-spinner-root', `few-spinner-root--${size}`, `few-tone--${tone}`, className)}>
      <span className="few-spinner" aria-hidden="true" />
      <VisuallyHidden>{label}</VisuallyHidden>
    </Comp>
  );
}
