// packages/angular/src/components/layout/aspect-ratio.ts
// AspectRatio: ver docs/composition-angular.md. Espelha packages/react/src/components/layout/aspect-ratio.tsx:
// wrapper externo fixo (padding-bottom) + conteúdo interno absoluto. @Component porque envolve o conteúdo com markup próprio.
import { Component, computed, input } from '@angular/core';

@Component({
  selector: '[fewAspectRatio]',
  template: `<div class="few-aspect-ratio-content" style="position:absolute;inset:0"><ng-content></ng-content></div>`,
  host: {
    class: 'few-aspect-ratio',
    '[style.position]': "'relative'",
    '[style.width]': "'100%'",
    '[style.padding-bottom.%]': 'paddingBottomPercent()',
  },
})
export class FewAspectRatio {
  /** Largura / altura. Padrão 16/9. */
  readonly ratio = input<number>(16 / 9);
  protected readonly paddingBottomPercent = computed(() => 100 / this.ratio());
}

export const FEW_ASPECT_RATIO = [FewAspectRatio] as const;

// packages/react/src/components/layout/aspect-ratio.tsx
"use client";
// AspectRatio: ver docs/composition.md. Padrão Radix: wrapper externo fixo (padding-bottom) + conteúdo absoluto asChild-ável.
import type { ComponentProps, CSSProperties } from 'react';
import { Slot } from '../../lib/slot.js';
import { cx } from '../../lib/cx.js';

export interface AspectRatioProps extends ComponentProps<'div'> {
  asChild?: boolean;
  /** Largura / altura. Padrão 16/9. */
  ratio?: number;
}
function AspectRatio({ asChild, ratio = 16 / 9, style, className, children, ...props }: AspectRatioProps) {
  const Comp = asChild ? Slot : 'div';
  return (
    <div className="few-aspect-ratio" style={{ position: 'relative', width: '100%', paddingBottom: `${100 / ratio}%` }}>
      <Comp {...props} className={cx('few-aspect-ratio-content', className)} style={{ ...style, position: 'absolute', inset: 0 } as CSSProperties}>
        {children}
      </Comp>
    </div>
  );
}

export { AspectRatio };
