// packages/angular/src/components/layout/scroll-area.ts
// ScrollArea: ver docs/composition-angular.md. Espelha packages/react/src/components/layout/scroll-area.tsx.
// Rola nativamente; Scrollbar/Thumb do React só existem por compatibilidade (renderizam null) e não têm equivalente aqui.
import { DestroyRef, Directive, ElementRef, afterNextRender, inject, input } from '@angular/core';
import type { Orientation } from '@fewcompany/core';

type ScrollAreaType = 'auto' | 'always' | 'scroll' | 'hover';

/** Raiz: `<div fewScrollArea type="hover">`. Só guarda type/orientation para data-* — sem lógica de scroll. */
@Directive({
  selector: '[fewScrollArea]',
  exportAs: 'fewScrollArea',
  host: { class: 'few-scroll-area', '[attr.data-type]': 'type()', '[attr.data-orientation]': 'orientation()' },
})
export class FewScrollArea {
  readonly type = input<ScrollAreaType>('hover');
  readonly orientation = input<Orientation | 'both'>('vertical');
}

/**
 * Viewport: overflow nativo, tabIndex 0 + role="region". Marca data-overflow-top/bottom conforme o scroll
 * (sombras de borda via CSS). Listener registrado em afterNextRender (só client, sem SSR).
 */
@Directive({
  selector: '[fewScrollAreaViewport]',
  host: { class: 'few-scroll-area-viewport', role: 'region', tabindex: '0', '[attr.aria-label]': 'label()' },
})
export class FewScrollAreaViewport {
  /** Injeção só para garantir que o Viewport está dentro de um fewScrollArea (paridade com useScrollArea do React). */
  private readonly scrollArea = inject(FewScrollArea);
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  /** aria-label da região rolável (obrigatório: viewport tem tabIndex=0 e role="region"). */
  readonly label = input.required<string>();

  constructor() {
    const destroyRef = inject(DestroyRef);
    afterNextRender(() => {
      const el = this.host.nativeElement;
      const update = () => {
        const top = el.scrollTop > 1;
        const bottom = el.scrollTop + el.clientHeight < el.scrollHeight - 1;
        if (top) el.dataset['overflowTop'] = ''; else delete el.dataset['overflowTop'];
        if (bottom) el.dataset['overflowBottom'] = ''; else delete el.dataset['overflowBottom'];
      };
      update();
      el.addEventListener('scroll', update);
      const observer = typeof ResizeObserver !== 'undefined' ? new ResizeObserver(update) : null;
      observer?.observe(el);
      destroyRef.onDestroy(() => { el.removeEventListener('scroll', update); observer?.disconnect(); });
    });
  }
}

/** Importe tudo de uma vez: `imports: [FEW_SCROLL_AREA]`. */
export const FEW_SCROLL_AREA = [FewScrollArea, FewScrollAreaViewport] as const;

// packages/react/src/components/layout/scroll-area.tsx
"use client";
// ScrollArea: ver docs/composition.md. Rola nativamente; Scrollbar/Thumb existem só por compatibilidade de API (renderizam null).
import { useEffect, useRef, type ComponentProps } from 'react';
import type { Orientation } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { cx } from '../../lib/cx.js';

type ScrollAreaType = 'auto' | 'always' | 'scroll' | 'hover';
interface ScrollAreaContextValue { type: ScrollAreaType; orientation: Orientation | 'both' }
const [ScrollAreaProvider, useScrollArea] = createContext<ScrollAreaContextValue>('ScrollArea');

export interface ScrollAreaProps extends ComponentProps<'div'> { asChild?: boolean; type?: ScrollAreaType; orientation?: Orientation | 'both' }
function ScrollAreaRoot({ asChild, type = 'hover', orientation = 'vertical', className, ...props }: ScrollAreaProps) {
  const Comp = asChild ? Slot : 'div';
  return (
    <ScrollAreaProvider value={{ type, orientation }}>
      <Comp {...props} className={cx('few-scroll-area', className)} data-type={type} data-orientation={orientation} />
    </ScrollAreaProvider>
  );
}

export interface ScrollAreaViewportProps extends ComponentProps<'div'> {
  asChild?: boolean;
  /** aria-label da região rolável (obrigatório: viewport tem tabIndex=0 e role="region"). */
  label: string;
}
/** Viewport: overflow nativo. Marca data-overflow-top/bottom conforme o scroll, para sombras de borda via CSS. */
function ScrollAreaViewport({ asChild, label, className, ...props }: ScrollAreaViewportProps) {
  useScrollArea('ScrollArea.Viewport');
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const update = () => {
      const top = el.scrollTop > 1;
      const bottom = el.scrollTop + el.clientHeight < el.scrollHeight - 1;
      if (top) el.dataset.overflowTop = ''; else delete el.dataset.overflowTop;
      if (bottom) el.dataset.overflowBottom = ''; else delete el.dataset.overflowBottom;
    };
    update();
    el.addEventListener('scroll', update);
    const observer = typeof ResizeObserver !== 'undefined' ? new ResizeObserver(update) : null;
    observer?.observe(el);
    return () => { el.removeEventListener('scroll', update); observer?.disconnect(); };
  }, []);
  const Comp = asChild ? Slot : 'div';
  return <Comp ref={ref} {...props} tabIndex={0} role="region" aria-label={label} className={cx('few-scroll-area-viewport', className)} />;
}

export interface ScrollAreaScrollbarProps extends ComponentProps<'div'> { orientation?: Orientation }
/** Existe só por compatibilidade de API com Radix: a barra é a nativa, estilizada via CSS (scrollbar-width/color + ::-webkit-scrollbar). */
function ScrollAreaScrollbar(_props: ScrollAreaScrollbarProps) { return null; }

export type ScrollAreaThumbProps = ComponentProps<'div'>;
function ScrollAreaThumb(_props: ScrollAreaThumbProps) { return null; }

/** ScrollArea composto: <ScrollArea type="hover"><ScrollArea.Viewport label="Lista">…</ScrollArea.Viewport></ScrollArea> */
export const ScrollArea = Object.assign(ScrollAreaRoot, { Root: ScrollAreaRoot, Viewport: ScrollAreaViewport, Scrollbar: ScrollAreaScrollbar, Thumb: ScrollAreaThumb });
export { ScrollAreaRoot, ScrollAreaViewport, ScrollAreaScrollbar, ScrollAreaThumb };
