// packages/angular/src/components/layout/separator.ts
// Separator: ver docs/composition-angular.md. Espelha packages/react/src/components/layout/separator.tsx.
// Com `label`, a estrutura vira linha+rótulo+linha (por isso @Component com <ng-content> em vez de @Directive).
import { Component, booleanAttribute, input } from '@angular/core';
import type { Orientation } from '@fewcompany/core';

@Component({
  selector: '[fewSeparator]',
  template: `
    @if (label() !== undefined) {
      <span class="few-separator-line" aria-hidden="true"></span>
      <span class="few-separator-label">{{ label() }}<ng-content></ng-content></span>
      <span class="few-separator-line" aria-hidden="true"></span>
    } @else {
      <ng-content></ng-content>
    }
  `,
  host: {
    class: 'few-separator',
    '[class.few-separator-labeled]': 'label() !== undefined',
    '[attr.data-orientation]': 'orientation()',
    '[attr.role]': "decorative() ? 'none' : 'separator'",
    '[attr.aria-orientation]': "!decorative() && orientation() === 'vertical' ? 'vertical' : null",
  },
})
export class FewSeparator {
  readonly orientation = input<Orientation>('horizontal');
  /** Puramente visual (role="none"): use quando já existe separação semântica por outro elemento. */
  readonly decorative = input(false, { transform: booleanAttribute });
  /** Rótulo centralizado (ex.: "ou"), projetado via <ng-content>. Presente => vira linha+rótulo+linha. */
  readonly label = input<string | undefined>(undefined);
}

export const FEW_SEPARATOR = [FewSeparator] as const;

// packages/react/src/components/layout/separator.tsx
"use client";
// Separator: ver docs/composition.md. Componente simples (sem contexto), como Badge/Kbd.
import type { ComponentProps, ReactNode } from 'react';
import type { Orientation } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { cx } from '../../lib/cx.js';

export interface SeparatorProps extends ComponentProps<'div'> {
  asChild?: boolean;
  orientation?: Orientation;
  /** Puramente visual (role="none"): use quando já existe separação semântica por outro elemento (ex.: <hr> dentro de <ul>). */
  decorative?: boolean;
  /** Rótulo centralizado (ex.: "ou"). Quando presente, ignora `asChild` — a estrutura vira linha+rótulo+linha. */
  label?: ReactNode;
}
function Separator({ asChild, orientation = 'horizontal', decorative = false, label, className, ...props }: SeparatorProps) {
  const a11yProps = decorative
    ? { role: 'none' as const }
    : { role: 'separator' as const, 'aria-orientation': orientation === 'vertical' ? ('vertical' as const) : undefined };
  if (label !== undefined) {
    return (
      <div {...props} className={cx('few-separator few-separator-labeled', className)} data-orientation={orientation} {...a11yProps}>
        <span className="few-separator-line" aria-hidden="true" />
        <span className="few-separator-label">{label}</span>
        <span className="few-separator-line" aria-hidden="true" />
      </div>
    );
  }
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} className={cx('few-separator', className)} data-orientation={orientation} {...a11yProps} />;
}

export { Separator };
