// packages/react/src/components/forms/file-upload.tsx
"use client";
import { useRef, useState, type ComponentProps, type DragEvent, type RefObject } from 'react';
import { formatFileSize, validateFile } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';

interface FileUploadContextValue {
  files: File[]; setFiles: (files: File[]) => void; addFiles: (list: FileList | File[]) => void;
  accept?: string; multiple?: boolean; maxSize?: number; disabled?: boolean;
  dragging: boolean; setDragging: (dragging: boolean) => void;
  inputRef: RefObject<HTMLInputElement | null>;
}
const [FileUploadProvider, useFileUpload] = createContext<FileUploadContextValue>('FileUpload');

export interface FileUploadProps extends Omit<ComponentProps<'div'>, 'onChange'> {
  asChild?: boolean;
  files?: File[]; defaultFiles?: File[]; onFilesChange?: (files: File[]) => void;
  accept?: string; multiple?: boolean; maxSize?: number; disabled?: boolean;
  /** Chamado para cada arquivo rejeitado por tipo ou tamanho (accept/maxSize). */
  onFileError?: (file: File, message: string) => void;
}
function FileUploadRoot({ asChild, files, defaultFiles = [], onFilesChange, accept, multiple = true, maxSize, disabled, onFileError, className, ...props }: FileUploadProps) {
  const [current, setCurrent] = useControllableState<File[]>({ value: files, defaultValue: defaultFiles, onChange: onFilesChange });
  const [dragging, setDragging] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  function addFiles(list: FileList | File[]) {
    if (disabled) return;
    const incoming = Array.from(list);
    const accepted: File[] = [];
    for (const file of incoming) {
      const error = validateFile(file, { accept, maxSize });
      if (error) onFileError?.(file, error); else accepted.push(file);
    }
    setCurrent(multiple ? [...current, ...accepted] : accepted.slice(0, 1));
  }
  const Comp = asChild ? Slot : 'div';
  return (
    <FileUploadProvider value={{ files: current, setFiles: setCurrent, addFiles, accept, multiple, maxSize, disabled, dragging, setDragging, inputRef }}>
      <Comp {...props} data-disabled={dataAttr(disabled)} className={cx('few-file-upload', className)} />
    </FileUploadProvider>
  );
}

export interface FileUploadDropzoneProps extends ComponentProps<'div'> { asChild?: boolean }
function FileUploadDropzone({ asChild, className, onDragOver, onDragLeave, onDrop, ...props }: FileUploadDropzoneProps) {
  const { addFiles, disabled, dragging, setDragging } = useFileUpload('FileUpload.Dropzone');
  function handleDragOver(event: DragEvent<HTMLDivElement>) { onDragOver?.(event); if (disabled) return; event.preventDefault(); setDragging(true); }
  function handleDragLeave(event: DragEvent<HTMLDivElement>) { onDragLeave?.(event); setDragging(false); }
  function handleDrop(event: DragEvent<HTMLDivElement>) {
    onDrop?.(event);
    if (disabled) return;
    event.preventDefault();
    setDragging(false);
    addFiles(event.dataTransfer.files);
  }
  const Comp = asChild ? Slot : 'div';
  return (
    <Comp {...props} data-dragging={dataAttr(dragging)} data-disabled={dataAttr(disabled)} className={cx('few-file-upload-dropzone', className)}
      onDragOver={handleDragOver} onDragLeave={handleDragLeave} onDrop={handleDrop} />
  );
}

export interface FileUploadTriggerProps extends ComponentProps<'button'> { asChild?: boolean }
function FileUploadTrigger({ asChild, className, onClick, ...props }: FileUploadTriggerProps) {
  const { inputRef, disabled } = useFileUpload('FileUpload.Trigger');
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp {...props} type="button" disabled={disabled} className={cx('few-file-upload-trigger', className)}
      onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) inputRef.current?.click(); }} />
  );
}

export interface FileUploadHiddenInputProps extends Omit<ComponentProps<'input'>, 'type' | 'onChange'> {}
function FileUploadHiddenInput({ className, ...props }: FileUploadHiddenInputProps) {
  const { inputRef, accept, multiple, disabled, addFiles } = useFileUpload('FileUpload.HiddenInput');
  return (
    <input
      {...props}
      ref={inputRef}
      type="file"
      accept={accept}
      multiple={multiple}
      disabled={disabled}
      className={cx('few-sr-only', className)}
      onChange={(event) => { if (event.currentTarget.files) addFiles(event.currentTarget.files); event.currentTarget.value = ''; }}
    />
  );
}

export interface FileUploadListProps extends ComponentProps<'ul'> { asChild?: boolean }
function FileUploadList({ asChild, className, ...props }: FileUploadListProps) {
  const Comp = asChild ? Slot : 'ul';
  return <Comp {...props} className={cx('few-file-upload-list', className)} />;
}

interface FileItemContextValue { file: File; index: number }
const [FileItemProvider, useFileItem] = createContext<FileItemContextValue>('FileUpload.Item');

export interface FileUploadItemProps extends ComponentProps<'li'> { asChild?: boolean; index: number }
function FileUploadItem({ asChild, index, className, ...props }: FileUploadItemProps) {
  const { files } = useFileUpload('FileUpload.Item');
  const file = files[index];
  if (!file) return null;
  const Comp = asChild ? Slot : 'li';
  return (
    <FileItemProvider value={{ file, index }}>
      <Comp {...props} className={cx('few-file-upload-item', className)} />
    </FileItemProvider>
  );
}

export interface FileUploadItemNameProps extends ComponentProps<'span'> { asChild?: boolean }
function FileUploadItemName({ asChild, className, children, ...props }: FileUploadItemNameProps) {
  const { file } = useFileItem('FileUpload.ItemName');
  const Comp = asChild ? Slot : 'span';
  return <Comp {...props} className={cx('few-file-upload-item-name', className)}>{children ?? file.name}</Comp>;
}

export interface FileUploadItemSizeProps extends ComponentProps<'span'> { asChild?: boolean }
function FileUploadItemSize({ asChild, className, children, ...props }: FileUploadItemSizeProps) {
  const { file } = useFileItem('FileUpload.ItemSize');
  const Comp = asChild ? Slot : 'span';
  return <Comp {...props} className={cx('few-file-upload-item-size', 'few-muted', className)}>{children ?? formatFileSize(file.size)}</Comp>;
}

export interface FileUploadItemDeleteProps extends ComponentProps<'button'> { asChild?: boolean }
function FileUploadItemDelete({ asChild, className, onClick, children, ...props }: FileUploadItemDeleteProps) {
  const { index, file } = useFileItem('FileUpload.ItemDelete');
  const { files, setFiles } = useFileUpload('FileUpload.ItemDelete');
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp {...props} type="button" aria-label={props['aria-label'] ?? `Remover ${file.name}`} className={cx('few-file-upload-item-delete', className)}
      onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) setFiles(files.filter((_, i) => i !== index)); }}>
      {children ?? '×'}
    </Comp>
  );
}

/** FileUpload composto: Root > Dropzone(Trigger, HiddenInput) + List(Item(ItemName, ItemSize, ItemDelete)). */
export const FileUpload = Object.assign(FileUploadRoot, {
  Root: FileUploadRoot, Dropzone: FileUploadDropzone, Trigger: FileUploadTrigger, HiddenInput: FileUploadHiddenInput,
  List: FileUploadList, Item: FileUploadItem, ItemName: FileUploadItemName, ItemSize: FileUploadItemSize, ItemDelete: FileUploadItemDelete,
});
export { FileUploadRoot, FileUploadDropzone, FileUploadTrigger, FileUploadHiddenInput, FileUploadList, FileUploadItem, FileUploadItemName, FileUploadItemSize, FileUploadItemDelete };

// packages/angular/src/components/forms/file-upload.ts
// FileUpload (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/forms/file-upload.tsx.
// Adaptação documentada: o input real (`fewFileUploadHiddenInput`) se registra no Root (`registerInput`) em vez
// de o Root guardar uma ref — equivalente ao `inputRef` do React, só que escrito de dentro para fora.
import { Component, Directive, ElementRef, booleanAttribute, computed, inject, input, model, output, signal } from '@angular/core';
import { formatFileSize, validateFile } from '@fewcompany/core';
import { dataAttr } from '../../lib/attrs.js';

export interface FewFileError { file: File; message: string }

/** Raiz: `<div fewFileUpload [(files)]="files" accept="image/*" (fileError)="onError($event)">…</div>`. */
@Directive({
  selector: '[fewFileUpload]',
  exportAs: 'fewFileUpload',
  host: { class: 'few-file-upload', '[attr.data-disabled]': 'dataAttr(disabled())' },
})
export class FewFileUpload {
  readonly files = model<File[]>([]);
  readonly accept = input<string>();
  readonly multiple = input(true, { transform: booleanAttribute });
  readonly maxSize = input<number>();
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly fileError = output<FewFileError>();
  /** Estado interno (não é prop no React): plain signal, igual ao `count` do Carousel. */
  readonly dragging = signal(false);
  protected readonly dataAttr = dataAttr;
  private inputEl: HTMLInputElement | null = null;

  registerInput(el: HTMLInputElement) { this.inputEl = el; }
  openPicker() { this.inputEl?.click(); }
  addFiles(list: FileList | File[]) {
    if (this.disabled()) return;
    const incoming = Array.from(list);
    const accepted: File[] = [];
    for (const file of incoming) {
      const error = validateFile(file, { accept: this.accept(), maxSize: this.maxSize() });
      if (error) this.fileError.emit({ file, message: error });
      else accepted.push(file);
    }
    this.files.set(this.multiple() ? [...this.files(), ...accepted] : accepted.slice(0, 1));
  }
}

@Directive({
  selector: '[fewFileUploadDropzone]',
  host: {
    class: 'few-file-upload-dropzone',
    '[attr.data-dragging]': 'dataAttr(upload.dragging())',
    '[attr.data-disabled]': 'dataAttr(upload.disabled())',
    '(dragover)': 'onDragOver($event)',
    '(dragleave)': 'onDragLeave()',
    '(drop)': 'onDrop($event)',
  },
})
export class FewFileUploadDropzone {
  protected readonly upload = inject(FewFileUpload);
  protected readonly dataAttr = dataAttr;
  protected onDragOver(event: DragEvent) { if (this.upload.disabled()) return; event.preventDefault(); this.upload.dragging.set(true); }
  protected onDragLeave() { this.upload.dragging.set(false); }
  protected onDrop(event: DragEvent) {
    if (this.upload.disabled()) return;
    event.preventDefault();
    this.upload.dragging.set(false);
    if (event.dataTransfer) this.upload.addFiles(event.dataTransfer.files);
  }
}

@Directive({ selector: 'button[fewFileUploadTrigger]', host: { class: 'few-file-upload-trigger', type: 'button', '[disabled]': 'upload.disabled()', '(click)': 'upload.openPicker()' } })
export class FewFileUploadTrigger {
  protected readonly upload = inject(FewFileUpload);
}

@Directive({
  selector: 'input[fewFileUploadHiddenInput]',
  host: {
    class: 'few-sr-only', type: 'file',
    '[attr.accept]': 'upload.accept() ?? null',
    '[multiple]': 'upload.multiple()',
    '[disabled]': 'upload.disabled()',
    '(change)': 'onChange($event)',
  },
})
export class FewFileUploadHiddenInput {
  protected readonly upload = inject(FewFileUpload);
  private readonly hostEl = inject<ElementRef<HTMLInputElement>>(ElementRef);
  constructor() { this.upload.registerInput(this.hostEl.nativeElement); }
  protected onChange(event: Event) {
    const el = event.target as HTMLInputElement;
    if (el.files) this.upload.addFiles(el.files);
    el.value = '';
  }
}

@Directive({ selector: '[fewFileUploadList]', host: { class: 'few-file-upload-list' } })
export class FewFileUploadList {}

/** `<li fewFileUploadItem [index]="i">…</li>`: distribui o `File` correspondente para ItemName/ItemSize/ItemDelete. */
@Directive({ selector: '[fewFileUploadItem]', exportAs: 'fewFileUploadItem', host: { class: 'few-file-upload-item' } })
export class FewFileUploadItem {
  private readonly upload = inject(FewFileUpload);
  readonly index = input.required<number>();
  readonly file = computed<File | undefined>(() => this.upload.files()[this.index()]);
}

@Component({ selector: 'span[fewFileUploadItemName]', host: { class: 'few-file-upload-item-name' }, template: `<ng-content>{{ item.file()?.name }}</ng-content>` })
export class FewFileUploadItemName {
  protected readonly item = inject(FewFileUploadItem);
}

@Component({ selector: 'span[fewFileUploadItemSize]', host: { class: 'few-file-upload-item-size few-muted' }, template: `<ng-content>{{ sizeText() }}</ng-content>` })
export class FewFileUploadItemSize {
  private readonly item = inject(FewFileUploadItem);
  protected readonly sizeText = computed(() => { const file = this.item.file(); return file ? formatFileSize(file.size) : ''; });
}

// Adaptação documentada: aria-label fixo ("Remover <nome>"), sem override via props.
@Component({
  selector: 'button[fewFileUploadItemDelete]',
  host: { class: 'few-file-upload-item-delete', type: 'button', '[attr.aria-label]': 'ariaLabel', '(click)': 'onClick()' },
  template: `<ng-content>&times;</ng-content>`,
})
export class FewFileUploadItemDelete {
  private readonly upload = inject(FewFileUpload);
  private readonly item = inject(FewFileUploadItem);
  protected get ariaLabel() { return `Remover ${this.item.file()?.name ?? ''}`; }
  protected onClick() {
    const index = this.item.index();
    this.upload.files.set(this.upload.files().filter((_, i) => i !== index));
  }
}

/** Importe tudo de uma vez: `imports: [FEW_FILE_UPLOAD]`. */
export const FEW_FILE_UPLOAD = [
  FewFileUpload, FewFileUploadDropzone, FewFileUploadTrigger, FewFileUploadHiddenInput,
  FewFileUploadList, FewFileUploadItem, FewFileUploadItemName, FewFileUploadItemSize, FewFileUploadItemDelete,
] as const;
