// packages/react/src/components/forms/label.tsx
"use client";
import type { ComponentProps } from 'react';
import { Slot, Slottable } from '../../lib/slot.js';
import { cx } from '../../lib/cx.js';

export interface LabelProps extends ComponentProps<'label'> {
  asChild?: boolean;
  /** Mostra um indicador (*) de campo obrigatório ao lado do texto. */
  required?: boolean;
}
/** Label nativo com asChild. Uso solto (htmlFor manual) ou via Field.Label (htmlFor automático). */
function LabelRoot({ asChild, required, className, children, ...props }: LabelProps) {
  const Comp = asChild ? Slot : 'label';
  return (
    <Comp {...props} className={cx('few-form-label', className)}>
      <Slottable>{children}</Slottable>
      {required && <span className="few-form-label-required" aria-hidden="true"> *</span>}
    </Comp>
  );
}

export const Label = Object.assign(LabelRoot, { Root: LabelRoot });
export { LabelRoot };

// packages/angular/src/components/forms/label.ts
// Label (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/forms/label.tsx.
import { Component, booleanAttribute, input } from '@angular/core';

/** Uso solto (for manual): `<label fewLabel for="email">E-mail</label>`. Dentro de um Field, use `fewFieldLabel` (ver field.ts). */
@Component({
  selector: 'label[fewLabel]',
  host: { class: 'few-form-label' },
  template: `<ng-content></ng-content>@if (required()) {<span class="few-form-label-required" aria-hidden="true"> *</span>}`,
})
export class FewLabel {
  /** Mostra um indicador (*) de campo obrigatório ao lado do texto. */
  readonly required = input(false, { transform: booleanAttribute });
}

/** Importe tudo de uma vez: `imports: [FEW_LABEL]`. */
export const FEW_LABEL = [FewLabel] as const;
