// packages/react/src/components/forms/pin-input.tsx
"use client";
import { useRef, type ChangeEvent, type ClipboardEvent, type ComponentProps, type KeyboardEvent, type MutableRefObject } from 'react';
import { distributePin, nextPinIndex } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';

interface PinInputContextValue {
  length: number; value: string; disabled?: boolean; mask?: boolean;
  setChar: (index: number, char: string) => void; setMany: (index: number, text: string) => void;
  refs: MutableRefObject<Array<HTMLInputElement | null>>;
}
const [PinInputProvider, usePinInput] = createContext<PinInputContextValue>('PinInput');

export interface PinInputProps extends Omit<ComponentProps<'div'>, 'onChange'> {
  asChild?: boolean;
  length?: number;
  value?: string; defaultValue?: string; onValueChange?: (value: string) => void;
  onComplete?: (value: string) => void;
  mask?: boolean; disabled?: boolean;
}
function PinInputRoot({ asChild, length = 4, value, defaultValue = '', onValueChange, onComplete, mask, disabled, className, ...props }: PinInputProps) {
  const [current, setCurrent] = useControllableState({ value, defaultValue, onChange: onValueChange });
  const refs = useRef<Array<HTMLInputElement | null>>([]);
  function commit(next: string) {
    setCurrent(next);
    if (next.length === length && !next.includes('')) onComplete?.(next);
  }
  function setChar(index: number, char: string) {
    // Não usa distributePin aqui: com texto vazio (limpar 1 casa no Backspace) ele não escreve nada
    // (''.split('') === []), então a escrita de uma única casa é feita diretamente.
    const chars = current.split('');
    while (chars.length < length) chars.push('');
    chars[index] = char;
    commit(chars.slice(0, length).join(''));
    if (char && index + 1 < length) refs.current[index + 1]?.focus();
  }
  function setMany(index: number, text: string) {
    const digits = text.replace(/\s/g, '');
    const chars = distributePin(current.split(''), digits, index, length);
    commit(chars.join(''));
    refs.current[nextPinIndex(index, digits.length, length)]?.focus();
  }
  const Comp = asChild ? Slot : 'div';
  return (
    <PinInputProvider value={{ length, value: current, disabled, mask, setChar, setMany, refs }}>
      <Comp {...props} role="group" className={cx('few-pin-input', className)} data-disabled={dataAttr(disabled)} />
    </PinInputProvider>
  );
}

export interface PinInputFieldProps extends Omit<ComponentProps<'input'>, 'value' | 'defaultValue'> { index: number }
function PinInputInput({ index, className, onKeyDown, onChange, onPaste, disabled, ...props }: PinInputFieldProps) {
  const { length, value, disabled: ctxDisabled, mask, setChar, setMany, refs } = usePinInput('PinInput.Input');
  const isDisabled = disabled ?? ctxDisabled;
  const char = value[index] ?? '';
  function handleChange(event: ChangeEvent<HTMLInputElement>) {
    onChange?.(event);
    const raw = event.currentTarget.value;
    const last = raw.slice(-1);
    setChar(index, /[a-zA-Z0-9]/.test(last) ? last : '');
  }
  function handleKeyDown(event: KeyboardEvent<HTMLInputElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented) return;
    if (event.key === 'Backspace' && !char && index > 0) { event.preventDefault(); setChar(index - 1, ''); refs.current[index - 1]?.focus(); }
    else if (event.key === 'ArrowLeft' && index > 0) { event.preventDefault(); refs.current[index - 1]?.focus(); }
    else if (event.key === 'ArrowRight' && index + 1 < length) { event.preventDefault(); refs.current[index + 1]?.focus(); }
  }
  function handlePaste(event: ClipboardEvent<HTMLInputElement>) {
    onPaste?.(event);
    event.preventDefault();
    setMany(index, event.clipboardData.getData('text'));
  }
  return (
    <input
      {...props}
      ref={(el) => { refs.current[index] = el; }}
      type={mask ? 'password' : 'text'}
      inputMode="numeric"
      autoComplete={index === 0 ? 'one-time-code' : 'off'}
      maxLength={1}
      disabled={isDisabled}
      value={char}
      onChange={handleChange}
      onKeyDown={handleKeyDown}
      onPaste={handlePaste}
      className={cx('few-input', 'few-pin-input-field', className)}
      aria-label={props['aria-label'] ?? `Dígito ${index + 1} de ${length}`}
    />
  );
}

/** PinInput composto: <PinInput length={4} onComplete={...}>{Array.from({length:4}).map((_, i) => <PinInput.Input key={i} index={i}/>)}</PinInput> */
export const PinInput = Object.assign(PinInputRoot, { Root: PinInputRoot, Input: PinInputInput });
export { PinInputRoot, PinInputInput };

// packages/angular/src/components/forms/pin-input.ts
// PinInput (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/forms/pin-input.tsx.
// Os slots (`fewPinInputInput`) são descobertos via `contentChildren` (equivalente ao array de refs do React)
// para permitir focar o slot correto após digitar/colar/apagar.
import { Directive, ElementRef, booleanAttribute, computed, contentChildren, inject, input, model, output } from '@angular/core';
import { distributePin, nextPinIndex } from '@fewcompany/core';
import { dataAttr } from '../../lib/attrs.js';

/** Raiz: `<div fewPinInput [length]="4" (complete)="onComplete($event)">…</div>`. */
@Directive({
  selector: '[fewPinInput]',
  exportAs: 'fewPinInput',
  host: { class: 'few-pin-input', role: 'group', '[attr.data-disabled]': 'dataAttr(disabled())' },
})
export class FewPinInput {
  readonly value = model('');
  readonly length = input(4);
  readonly mask = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly complete = output<string>();
  private readonly items = contentChildren(FewPinInputInput, { descendants: false });
  protected readonly dataAttr = dataAttr;

  private commit(next: string) {
    this.value.set(next);
    if (next.length === this.length() && !next.includes('')) this.complete.emit(next);
  }
  setChar(index: number, char: string) {
    const chars = this.value().split('');
    while (chars.length < this.length()) chars.push('');
    chars[index] = char;
    this.commit(chars.slice(0, this.length()).join(''));
    if (char && index + 1 < this.length()) this.focusItem(index + 1);
  }
  setMany(index: number, text: string) {
    const digits = text.replace(/\s/g, '');
    const chars = distributePin(this.value().split(''), digits, index, this.length());
    this.commit(chars.join(''));
    this.focusItem(nextPinIndex(index, digits.length, this.length()));
  }
  focusItem(index: number) { this.items()[index]?.focus(); }
}

/** `<input fewPinInputInput [index]="0">`. */
@Directive({
  selector: 'input[fewPinInputInput]',
  host: {
    class: 'few-input few-pin-input-field',
    inputmode: 'numeric', maxlength: '1',
    '[attr.type]': "pinInput.mask() ? 'password' : 'text'",
    '[attr.autocomplete]': "index() === 0 ? 'one-time-code' : 'off'",
    '[disabled]': 'pinInput.disabled()',
    '[value]': 'char()',
    '[attr.aria-label]': 'ariaLabel',
    '(input)': 'onInput($event)',
    '(keydown)': 'onKeydown($event)',
    '(paste)': 'onPaste($event)',
  },
})
export class FewPinInputInput {
  protected readonly pinInput = inject(FewPinInput);
  private readonly hostEl = inject<ElementRef<HTMLInputElement>>(ElementRef);
  readonly index = input.required<number>();
  protected readonly char = computed(() => this.pinInput.value()[this.index()] ?? '');
  protected get ariaLabel() { return `Dígito ${this.index() + 1} de ${this.pinInput.length()}`; }

  focus() { this.hostEl.nativeElement.focus(); }

  protected onInput(event: Event) {
    const raw = (event.target as HTMLInputElement).value;
    const last = raw.slice(-1);
    this.pinInput.setChar(this.index(), /[a-zA-Z0-9]/.test(last) ? last : '');
  }
  protected onKeydown(event: KeyboardEvent) {
    if (event.defaultPrevented) return;
    const i = this.index();
    if (event.key === 'Backspace' && !this.char() && i > 0) { event.preventDefault(); this.pinInput.setChar(i - 1, ''); this.pinInput.focusItem(i - 1); }
    else if (event.key === 'ArrowLeft' && i > 0) { event.preventDefault(); this.pinInput.focusItem(i - 1); }
    else if (event.key === 'ArrowRight' && i + 1 < this.pinInput.length()) { event.preventDefault(); this.pinInput.focusItem(i + 1); }
  }
  protected onPaste(event: ClipboardEvent) {
    event.preventDefault();
    this.pinInput.setMany(this.index(), event.clipboardData?.getData('text') ?? '');
  }
}

/** Importe tudo de uma vez: `imports: [FEW_PIN_INPUT]`. */
export const FEW_PIN_INPUT = [FewPinInput, FewPinInputInput] as const;
