// packages/react/src/components/forms/radio-group.tsx
"use client";
import { useId, useRef, type ComponentProps, type KeyboardEvent, type ReactNode } from 'react';
import type { Orientation } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';
import { moveFocus } from '../../lib/roving.js';

interface RadioGroupContextValue { value: string; setValue: (value: string) => void; name: string; disabled?: boolean; orientation: Orientation }
const [RadioGroupProvider, useRadioGroup] = createContext<RadioGroupContextValue>('RadioGroup');

export interface RadioGroupProps extends Omit<ComponentProps<'div'>, 'defaultValue'> {
  asChild?: boolean;
  value?: string; defaultValue?: string; onValueChange?: (value: string) => void;
  name?: string; disabled?: boolean; required?: boolean; orientation?: Orientation; loop?: boolean;
}
function RadioGroupRoot({ asChild, value, defaultValue = '', onValueChange, name, disabled, required, orientation = 'vertical', loop = true, className, onKeyDown, ...props }: RadioGroupProps) {
  const baseId = useId();
  const groupName = name ?? baseId;
  const [current, setCurrent] = useControllableState({ value, defaultValue, onChange: onValueChange });
  const ref = useRef<HTMLDivElement>(null);
  function handleKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented) return;
    const target = moveFocus(ref.current, 'input[type="radio"]:not(:disabled)', event.key, { orientation, loop });
    if (!target) return;
    event.preventDefault();
    setCurrent((target as HTMLInputElement).value);
  }
  const Comp = asChild ? Slot : 'div';
  return (
    <RadioGroupProvider value={{ value: current, setValue: setCurrent, name: groupName, disabled, orientation }}>
      <Comp {...props} ref={ref} role="radiogroup" aria-orientation={orientation} aria-required={required || undefined} data-orientation={orientation} className={cx('few-radio-group', className)} onKeyDown={handleKeyDown} />
    </RadioGroupProvider>
  );
}

type RadioItemState = 'checked' | 'unchecked';
interface RadioItemContextValue { state: RadioItemState }
const [RadioItemProvider, useRadioItemState] = createContext<RadioItemContextValue>('RadioGroup.Item');

export interface RadioGroupItemProps extends Omit<ComponentProps<'input'>, 'type' | 'checked' | 'defaultChecked' | 'onChange'> { value: string; children?: ReactNode }
function RadioGroupItem({ value, disabled, className, children, ...inputProps }: RadioGroupItemProps) {
  const ctx = useRadioGroup('RadioGroup.Item');
  const checked = ctx.value === value;
  const isDisabled = disabled ?? ctx.disabled;
  const state: RadioItemState = checked ? 'checked' : 'unchecked';
  return (
    <label className={cx('few-radio-group-item', className)} data-state={state} data-disabled={dataAttr(isDisabled)}>
      <input
        {...inputProps}
        type="radio"
        name={ctx.name}
        value={value}
        checked={checked}
        disabled={isDisabled}
        className="few-sr-only"
        onChange={() => ctx.setValue(value)}
      />
      <RadioItemProvider value={{ state }}>{children}</RadioItemProvider>
    </label>
  );
}

export interface RadioGroupIndicatorProps extends ComponentProps<'span'> { asChild?: boolean; forceMount?: boolean }
function RadioGroupIndicator({ asChild, forceMount, className, ...props }: RadioGroupIndicatorProps) {
  const { state } = useRadioItemState('RadioGroup.Indicator');
  if (state === 'unchecked' && !forceMount) return null;
  const Comp = asChild ? Slot : 'span';
  return <Comp {...props} aria-hidden="true" data-state={state} className={cx('few-radio-group-indicator', className)} />;
}

/** RadioGroup composto: <RadioGroup value={..} onValueChange={..}><RadioGroup.Item value="a"><RadioGroup.Indicator/> A</RadioGroup.Item></RadioGroup> */
export const RadioGroup = Object.assign(RadioGroupRoot, { Root: RadioGroupRoot, Item: RadioGroupItem, Indicator: RadioGroupIndicator });
export { RadioGroupRoot, RadioGroupItem, RadioGroupIndicator };

// packages/angular/src/components/forms/radio-group.ts
// RadioGroup (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/forms/radio-group.tsx.
import { Directive, ElementRef, booleanAttribute, computed, inject, input, model } from '@angular/core';
import type { Orientation } from '@fewcompany/core';
import { dataAttr } from '../../lib/attrs.js';
import { fewId } from '../../lib/ids.js';
import { moveFocus } from '../../lib/roving.js';

/** Raiz: `<div fewRadioGroup [(value)]="plan">…</div>`. Roving focus por setas/Home/End entre os radios. */
@Directive({
  selector: '[fewRadioGroup]',
  exportAs: 'fewRadioGroup',
  host: {
    class: 'few-radio-group', role: 'radiogroup',
    '[attr.aria-orientation]': 'orientation()',
    '[attr.aria-required]': 'required() || null',
    '[attr.data-orientation]': 'orientation()',
    '(keydown)': 'onKeydown($event)',
  },
})
export class FewRadioGroup {
  private readonly hostEl = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly baseId = fewId('radio-group');
  readonly value = model('');
  readonly name = input<string>();
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly required = input(false, { transform: booleanAttribute });
  readonly orientation = input<Orientation>('vertical');
  readonly loop = input(true, { transform: booleanAttribute });

  get groupName() { return this.name() ?? this.baseId; }

  protected onKeydown(event: KeyboardEvent) {
    if (event.defaultPrevented) return;
    const target = moveFocus(this.hostEl.nativeElement, 'input[type="radio"]:not(:disabled)', event.key, { orientation: this.orientation(), loop: this.loop() });
    if (!target) return;
    event.preventDefault();
    this.value.set((target as HTMLInputElement).value);
  }
}

/** `<label fewRadioGroupItem value="a"><input fewRadioGroupItemInput/><span fewRadioGroupIndicator/> A</label>`. */
@Directive({
  selector: 'label[fewRadioGroupItem]',
  exportAs: 'fewRadioGroupItem',
  host: { class: 'few-radio-group-item', '[attr.data-state]': 'state()', '[attr.data-disabled]': 'dataAttr(isDisabled())' },
})
export class FewRadioGroupItem {
  private readonly group = inject(FewRadioGroup);
  readonly value = input.required<string>();
  readonly disabled = input(false, { transform: booleanAttribute });
  protected readonly checked = computed(() => this.group.value() === this.value());
  readonly isDisabled = computed(() => this.disabled() || this.group.disabled());
  readonly state = computed<'checked' | 'unchecked'>(() => (this.checked() ? 'checked' : 'unchecked'));
  protected readonly dataAttr = dataAttr;

  get name() { return this.group.groupName; }
  select() { if (!this.isDisabled()) this.group.value.set(this.value()); }
}

@Directive({
  selector: 'input[fewRadioGroupItemInput]',
  host: {
    class: 'few-sr-only', type: 'radio',
    '[attr.name]': 'item.name',
    '[value]': 'item.value()',
    '[checked]': 'item.state() === "checked"',
    '[disabled]': 'item.isDisabled()',
    '(change)': 'item.select()',
  },
})
export class FewRadioGroupItemInput {
  protected readonly item = inject(FewRadioGroupItem);
}

/** `<span fewRadioGroupIndicator></span>`: o ponto central vem do CSS (`::after`); fica no DOM com `[hidden]`. */
@Directive({
  selector: 'span[fewRadioGroupIndicator]',
  host: {
    class: 'few-radio-group-indicator', 'aria-hidden': 'true',
    '[attr.data-state]': 'item.state()',
    '[hidden]': 'item.state() === "unchecked"',
  },
})
export class FewRadioGroupIndicator {
  protected readonly item = inject(FewRadioGroupItem);
}

/** Importe tudo de uma vez: `imports: [FEW_RADIO_GROUP]`. */
export const FEW_RADIO_GROUP = [FewRadioGroup, FewRadioGroupItem, FewRadioGroupItemInput, FewRadioGroupIndicator] as const;
