// packages/react/src/components/forms/switch.tsx
"use client";
import type { ComponentProps, ReactNode } from 'react';
import type { Size } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';

interface SwitchContextValue { checked: boolean }
const [SwitchProvider, useSwitchState] = createContext<SwitchContextValue>('Switch');

export interface SwitchProps extends Omit<ComponentProps<'input'>, 'type' | 'checked' | 'defaultChecked' | 'onChange' | 'size'> {
  checked?: boolean; defaultChecked?: boolean; onCheckedChange?: (checked: boolean) => void;
  size?: Size; children?: ReactNode;
}
/** role=switch no input nativo (checkbox + role="switch" é o padrão recomendado pela WAI-ARIA APG). */
function SwitchRoot({ checked, defaultChecked = false, onCheckedChange, size = 'md', disabled, className, children, id, ...inputProps }: SwitchProps) {
  const [current, setCurrent] = useControllableState({ value: checked, defaultValue: defaultChecked, onChange: onCheckedChange });
  return (
    <label className={cx('few-switch', `few-switch--${size}`, className)} data-state={current ? 'checked' : 'unchecked'} data-disabled={dataAttr(disabled)}>
      <input
        {...inputProps}
        id={id}
        type="checkbox"
        role="switch"
        checked={current}
        disabled={disabled}
        className="few-sr-only"
        onChange={(event) => setCurrent(event.currentTarget.checked)}
      />
      <SwitchProvider value={{ checked: current }}>{children}</SwitchProvider>
    </label>
  );
}

export interface SwitchThumbProps extends ComponentProps<'span'> { asChild?: boolean }
function SwitchThumb({ asChild, className, ...props }: SwitchThumbProps) {
  const { checked } = useSwitchState('Switch.Thumb');
  const Comp = asChild ? Slot : 'span';
  return <Comp {...props} aria-hidden="true" data-state={checked ? 'checked' : 'unchecked'} className={cx('few-switch-thumb', className)} />;
}

/** Switch composto: <Switch.Root checked={..} onCheckedChange={..}><Switch.Thumb/></Switch.Root> */
export const Switch = Object.assign(SwitchRoot, { Root: SwitchRoot, Thumb: SwitchThumb });
export { SwitchRoot, SwitchThumb };

// packages/angular/src/components/forms/switch.ts
// Switch (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/forms/switch.tsx.
// role=switch no input nativo (checkbox + role="switch" é o padrão recomendado pela WAI-ARIA APG).
import { Directive, booleanAttribute, computed, inject, input, model } from '@angular/core';
import type { Size } from '@fewcompany/core';
import { dataAttr } from '../../lib/attrs.js';

/** Raiz: `<label fewSwitch [(checked)]="on"><input fewSwitchInput/><span fewSwitchThumb/></label>`. */
@Directive({
  selector: 'label[fewSwitch]',
  exportAs: 'fewSwitch',
  host: { '[class]': 'classes()', '[attr.data-state]': 'state()', '[attr.data-disabled]': 'dataAttr(disabled())' },
})
export class FewSwitch {
  readonly checked = model(false);
  readonly size = input<Size>('md');
  readonly disabled = input(false, { transform: booleanAttribute });
  protected readonly classes = computed(() => `few-switch few-switch--${this.size()}`);
  readonly state = computed<'checked' | 'unchecked'>(() => (this.checked() ? 'checked' : 'unchecked'));
  protected readonly dataAttr = dataAttr;
}

@Directive({
  selector: 'input[fewSwitchInput]',
  host: {
    class: 'few-sr-only', type: 'checkbox', role: 'switch',
    '[checked]': 'switchRoot.checked()',
    '[disabled]': 'switchRoot.disabled()',
    '(change)': 'onChange($event)',
  },
})
export class FewSwitchInput {
  protected readonly switchRoot = inject(FewSwitch);
  protected onChange(event: Event) { this.switchRoot.checked.set((event.target as HTMLInputElement).checked); }
}

/** `<span fewSwitchThumb></span>`: sem markup próprio — a trilha/bolinha vêm inteiramente do CSS. */
@Directive({ selector: 'span[fewSwitchThumb]', host: { class: 'few-switch-thumb', 'aria-hidden': 'true', '[attr.data-state]': 'switchRoot.state()' } })
export class FewSwitchThumb {
  protected readonly switchRoot = inject(FewSwitch);
}

/** Importe tudo de uma vez: `imports: [FEW_SWITCH]`. */
export const FEW_SWITCH = [FewSwitch, FewSwitchInput, FewSwitchThumb] as const;
