// packages/react/src/components/forms/textarea.tsx
"use client";
import type { ComponentProps } from 'react';
import { cx, dataAttr } from '../../lib/cx.js';

export interface TextareaProps extends ComponentProps<'textarea'> {
  invalid?: boolean;
  /** Cresce a altura conforme o conteúdo, sem barra de rolagem própria. */
  autoResize?: boolean;
}
/** Textarea nativa. Sem asChild: é sempre um <textarea> real. */
export function Textarea({ invalid, autoResize, className, onInput, rows = 3, ...props }: TextareaProps) {
  const handleInput: NonNullable<ComponentProps<'textarea'>['onInput']> = (event) => {
    onInput?.(event);
    if (!autoResize) return;
    const el = event.currentTarget;
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  };
  return (
    <textarea
      {...props}
      rows={rows}
      onInput={handleInput}
      className={cx('few-input', 'few-textarea', autoResize && 'few-textarea--auto', className)}
      aria-invalid={invalid || (props['aria-invalid'] && props['aria-invalid'] !== 'false') || undefined}
      data-invalid={dataAttr(invalid)}
    />
  );
}

// packages/angular/src/components/forms/textarea.ts
// Textarea (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/forms/textarea.tsx.
import { Directive, ElementRef, booleanAttribute, computed, inject, input } from '@angular/core';
import { dataAttr } from '../../lib/attrs.js';
import { FewField } from './field.js';

/** `<textarea fewTextarea autoResize>`. `autoResize` cresce a altura conforme o conteúdo, sem rolagem própria. */
@Directive({
  selector: 'textarea[fewTextarea]',
  host: {
    class: 'few-input few-textarea',
    '[class.few-textarea--auto]': 'autoResize()',
    '[attr.aria-invalid]': 'isInvalid() || null',
    '[attr.data-invalid]': 'dataAttr(isInvalid())',
    '(input)': 'onInput()',
  },
})
export class FewTextarea {
  private readonly field = inject(FewField, { optional: true });
  private readonly hostEl = inject<ElementRef<HTMLTextAreaElement>>(ElementRef);
  readonly invalid = input(false, { transform: booleanAttribute });
  readonly autoResize = input(false, { transform: booleanAttribute });
  protected readonly isInvalid = computed(() => this.invalid() || (this.field?.invalid() ?? false));
  protected readonly dataAttr = dataAttr;

  protected onInput() {
    if (!this.autoResize() || typeof document === 'undefined') return;
    const el = this.hostEl.nativeElement;
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  }
}

/** Importe tudo de uma vez: `imports: [FEW_TEXTAREA]`. */
export const FEW_TEXTAREA = [FewTextarea] as const;
