// packages/angular/src/demos/feedback.ts
// Hosts de demonstração/teste da categoria "Feedback" (pasta components/feedback). Um @Component por id do registry,
// selector few-demo-<id>. Textos e exemplos espelham apps/catalog/demos/feedback.tsx (React) quando fazem sentido.
import { Component, signal, type Type } from '@angular/core';
import { FEW_ALERT } from '../components/feedback/alert.js';
import { FEW_BADGE } from '../components/feedback/badge.js';
import { FEW_TAG } from '../components/feedback/tag.js';
import { FEW_PROGRESS } from '../components/feedback/progress.js';
import { FEW_PROGRESS_CIRCLE } from '../components/feedback/progress-circle.js';
import { FEW_SPINNER } from '../components/feedback/spinner.js';
import { FEW_SKELETON } from '../components/feedback/skeleton.js';
import { FEW_EMPTY_STATE } from '../components/feedback/empty-state.js';

@Component({
  selector: 'few-demo-alert',
  imports: [FEW_ALERT],
  template: `
    <div class="demo-stack demo-narrow">
      @if (soft()) {
        <div fewAlert tone="success" variant="soft">
          <span fewAlertIcon></span>
          <strong fewAlertTitle>Salvo</strong>
          <div fewAlertDescription>Suas alterações foram salvas com sucesso.</div>
          <button fewAlertClose aria-label="Fechar aviso" (dismiss)="soft.set(false)"></button>
        </div>
      }
      @if (outline()) {
        <div fewAlert tone="danger" variant="outline">
          <span fewAlertIcon></span>
          <strong fewAlertTitle>Falha ao publicar</strong>
          <div fewAlertDescription>Verifique sua conexão e tente novamente.</div>
          <div fewAlertAction><button type="button" class="few-button few-button--secondary">Tentar de novo</button></div>
          <button fewAlertClose aria-label="Fechar aviso" (dismiss)="outline.set(false)"></button>
        </div>
      }
      @if (!soft() && !outline()) {
        <p class="few-muted">Os dois avisos foram fechados.</p>
      }
    </div>
  `,
})
export class DemoAlert {
  readonly soft = signal(true);
  readonly outline = signal(true);
}

@Component({
  selector: 'few-demo-badge',
  imports: [FEW_BADGE],
  template: `
    <div class="demo-stack">
      <div class="demo-row">
        <span fewBadge tone="neutral">Rascunho</span>
        <span fewBadge tone="success" dot>Ativo</span>
        <span fewBadge tone="warning">Pendente</span>
        <span fewBadge tone="danger">Bloqueado</span>
        <span fewBadge tone="info">Novo</span>
      </div>
      <div class="demo-row">
        <span fewBadge tone="success" variant="solid">Solid</span>
        <span fewBadge tone="success" variant="soft">Soft</span>
        <span fewBadge tone="success" variant="outline">Outline</span>
        <span fewBadge tone="info" size="sm">Pequeno</span>
      </div>
    </div>
  `,
})
export class DemoBadge {}

@Component({
  selector: 'few-demo-tag',
  imports: [FEW_TAG],
  template: `
    <div class="demo-stack">
      <div class="demo-row">
        @for (tag of tags(); track tag) {
          <span fewTag tone="info" variant="soft">
            <span fewTagLabel>{{ tag }}</span>
            <button fewTagClose [label]="tag" (remove)="remove(tag)"></button>
          </span>
        }
        @if (tags().length === 0) {
          <p class="few-muted">Todas as tags foram removidas.</p>
        }
      </div>
      <span fewTag tone="neutral" variant="outline" interactive (select)="restore()">
        <span fewTagLabel>Restaurar tags</span>
      </span>
    </div>
  `,
})
export class DemoTag {
  readonly tags = signal(['React', 'TypeScript', 'Acessibilidade']);
  remove(tag: string) { this.tags.update(current => current.filter(item => item !== tag)); }
  restore() { this.tags.set(['React', 'TypeScript', 'Acessibilidade']); }
}

@Component({
  selector: 'few-demo-progress',
  imports: [FEW_PROGRESS],
  template: `
    <div class="demo-stack demo-narrow">
      <div fewProgress [value]="indeterminate() ? null : value()" tone="info">
        <span fewProgressLabel>Importação de dados</span>
        <span fewProgressValue></span>
        <div fewProgressTrack><div fewProgressIndicator></div></div>
      </div>
      <div class="demo-row">
        <button type="button" class="few-button few-button--secondary" [disabled]="indeterminate()" (click)="value.set(Math.min(100, value() + 10))">+10%</button>
        <button type="button" class="few-button few-button--secondary" [disabled]="indeterminate()" (click)="value.set(Math.max(0, value() - 10))">-10%</button>
        <label class="few-muted"><input type="checkbox" [checked]="indeterminate()" (change)="indeterminate.set(!indeterminate())" /> Indeterminado</label>
      </div>
    </div>
  `,
})
export class DemoProgress {
  readonly value = signal(30);
  readonly indeterminate = signal(false);
  protected readonly Math = Math;
}

@Component({
  selector: 'few-demo-progress-circle',
  imports: [FEW_PROGRESS_CIRCLE],
  template: `
    <div class="demo-row">
      <div fewProgressCircle [value]="value()" tone="success" size="md">
        <svg fewProgressCircleCircle></svg>
        <span fewProgressCircleLabel></span>
      </div>
      <div fewProgressCircle [value]="null" tone="info" size="md">
        <svg fewProgressCircleCircle></svg>
      </div>
      <div class="demo-stack">
        <button type="button" class="few-button few-button--secondary" (click)="value.set(Math.min(100, value() + 15))">+15%</button>
        <button type="button" class="few-button few-button--secondary" (click)="value.set(Math.max(0, value() - 15))">-15%</button>
      </div>
    </div>
  `,
})
export class DemoProgressCircle {
  readonly value = signal(65);
  protected readonly Math = Math;
}

@Component({
  selector: 'few-demo-spinner',
  imports: [FEW_SPINNER],
  template: `
    <div class="demo-row">
      <span fewSpinner size="sm" label="Carregando"></span>
      <span fewSpinner size="md" tone="info" label="Carregando pedidos"></span>
      <span fewSpinner size="lg" tone="success" label="Enviando"></span>
    </div>
  `,
})
export class DemoSpinner {}

@Component({
  selector: 'few-demo-skeleton',
  imports: [FEW_SKELETON],
  template: `
    <div class="demo-stack demo-narrow">
      <label class="few-muted"><input type="checkbox" [checked]="loading()" (change)="loading.set(!loading())" /> Carregando</label>
      @if (loading()) {
        <div class="demo-row" style="align-items:flex-start">
          <span fewSkeleton variant="circle"></span>
          <span fewSkeleton variant="text" [lines]="3"></span>
        </div>
      } @else {
        <div class="demo-row" style="align-items:flex-start">
          <span aria-hidden="true" class="few-empty-icon" style="width:40px;height:40px;font-size:18px">VN</span>
          <p class="few-muted">Vinícius Negrão publicou 3 novos componentes no catálogo Few UI.</p>
        </div>
      }
    </div>
  `,
})
export class DemoSkeleton {
  readonly loading = signal(true);
}

@Component({
  selector: 'few-demo-empty-state',
  imports: [FEW_EMPTY_STATE],
  template: `
    <div class="demo-narrow">
      <div fewEmptyState size="sm">
        <span fewEmptyStateIcon></span>
        <h3 fewEmptyStateTitle>Nenhum projeto ainda</h3>
        <p fewEmptyStateDescription>Crie o primeiro projeto para começar a organizar seu trabalho.</p>
        <div fewEmptyStateActions>
          <button type="button" class="few-button" (click)="created.set(true)">+ Novo projeto</button>
        </div>
      </div>
      @if (created()) {
        <p class="few-muted">Projeto criado.</p>
      }
    </div>
  `,
})
export class DemoEmptyState {
  readonly created = signal(false);
}

export const FEEDBACK_DEMOS: Record<string, Type<unknown>> = {
  alert: DemoAlert,
  badge: DemoBadge,
  tag: DemoTag,
  progress: DemoProgress,
  'progress-circle': DemoProgressCircle,
  spinner: DemoSpinner,
  skeleton: DemoSkeleton,
  'empty-state': DemoEmptyState,
};

// packages/react/src/registry/feedback.ts
import { component, type ComponentRecord } from './shared.js';
// Registro da categoria "Feedback" (pasta components/feedback). Um component() por componente, na ordem do menu.
export const feedbackRegistry: ComponentRecord[] = [
  component({
    id: 'alert', name: 'Alert', category: 'Feedback',
    description: 'Aviso inline com tom semântico, ícone, título, descrição, ação e fechamento opcional.',
    variants: ['tone: neutral | success | warning | danger | info', 'variant: soft | outline', 'role=alert (danger) | role=status (demais)'],
    parts: ['Root', 'Icon', 'Title', 'Description', 'Action', 'Close'],
    origins: ['Caraminholas · feedback de checkout', 'iFIGHT · cards de status'],
    references: ['Radix (padrão de composição)', 'PrimeReact Message'],
    code: '<Alert tone="success"><Alert.Icon /><Alert.Title>Salvo</Alert.Title><Alert.Description>Suas alterações foram salvas.</Alert.Description><Alert.Close onDismiss={() => {}} /></Alert>',
    vueCode: '<FewAlert tone="success">\n  <FewAlertIcon />\n  <FewAlertTitle>Salvo</FewAlertTitle>\n  <FewAlertDescription>Suas alterações foram salvas.</FewAlertDescription>\n  <FewAlertClose @dismiss="() => {}" />\n</FewAlert>',
  }),
  component({
    id: 'badge', name: 'Badge', category: 'Feedback',
    description: 'Rótulo pequeno de status ou contagem, com tom, variante e bolinha opcional.',
    variants: ['variant: solid | soft | outline', 'size: sm | md', 'dot'],
    parts: [],
    origins: ['Caraminholas · .chip', 'iFIGHT · ui/badge.tsx'],
    references: ['Radix Badge', 'PrimeReact Tag'],
    code: '<Badge tone="success" dot>Ativo</Badge>',
    vueCode: '<FewBadge tone="success" dot>Ativo</FewBadge>',
  }),
  component({
    id: 'tag', name: 'Tag', category: 'Feedback',
    description: 'Chip com rótulo, ícone opcional e botão de remover — para filtros e seleções múltiplas.',
    variants: ['variant: solid | soft | outline', 'size: sm | md', 'interactive (com onClick)', 'removable (com Tag.Close)'],
    parts: ['Root', 'Label', 'Icon', 'Close'],
    origins: ['Few · novo padrão'],
    references: ['PrimeReact Chip', 'MUI Chip'],
    code: '<Tag><Tag.Label>React</Tag.Label><Tag.Close label="React" onRemove={() => {}} /></Tag>',
    vueCode: '<FewTag>\n  <FewTagLabel>React</FewTagLabel>\n  <FewTagClose label="React" @remove="() => {}" />\n</FewTag>',
  }),
  component({
    id: 'progress', name: 'Progress', category: 'Feedback',
    description: 'Barra de progresso linear, determinada ou indeterminada, com rótulo e valor.',
    variants: ['determinate (value)', 'indeterminate (value={null})', 'size: sm | md | lg'],
    parts: ['Root', 'Track', 'Indicator', 'Label', 'Value'],
    origins: ['iFIGHT · progressão'],
    references: ['Radix Progress'],
    code: '<Progress value={72}><Progress.Label>Perfil</Progress.Label><Progress.Track><Progress.Indicator /></Progress.Track><Progress.Value /></Progress>',
    vueCode: '<FewProgress :value="72">\n  <FewProgressLabel>Perfil</FewProgressLabel>\n  <FewProgressTrack><FewProgressIndicator /></FewProgressTrack>\n  <FewProgressValue />\n</FewProgress>',
  }),
  component({
    id: 'progress-circle', name: 'Progress Circle', category: 'Feedback',
    description: 'Progresso circular em SVG, determinado ou indeterminado, com rótulo central opcional.',
    variants: ['determinate (value)', 'indeterminate (value={null})', 'size: sm | md | lg | número (px)'],
    parts: ['Root', 'Circle', 'Label'],
    origins: ['Few · novo padrão'],
    references: ['MUI CircularProgress', 'Radix (padrão de composição)'],
    code: '<ProgressCircle value={72}><ProgressCircle.Circle /><ProgressCircle.Label /></ProgressCircle>',
    vueCode: '<FewProgressCircle :value="72">\n  <FewProgressCircleCircle />\n  <FewProgressCircleLabel />\n</FewProgressCircle>',
  }),
  component({
    id: 'spinner', name: 'Spinner', category: 'Feedback',
    description: 'Indicador de carregamento giratório com anúncio sr-only para leitores de tela.',
    variants: ['size: sm | md | lg', 'tone'],
    parts: [],
    origins: ['Few · novo padrão'],
    references: ['Radix (padrão de composição)', 'PrimeReact ProgressSpinner'],
    code: '<Spinner label="Carregando pedidos" />',
    vueCode: '<FewSpinner label="Carregando pedidos" />',
  }),
  component({
    id: 'skeleton', name: 'Skeleton', category: 'Feedback',
    description: 'Placeholder de carregamento: linhas de texto, círculo, retângulo, ou o próprio conteúdo escondido.',
    variants: ['variant: text | circle | rect', 'lines', 'asChild (envolve e esconde o conteúdo real)'],
    parts: [],
    origins: ['Few · novo padrão'],
    references: ['Radix (padrão de composição)'],
    code: '<Skeleton variant="text" lines={3} />',
    vueCode: '<FewSkeleton variant="text" :lines="3" />',
  }),
  component({
    id: 'empty-state', name: 'Empty State', category: 'Feedback',
    description: 'Estado vazio com ícone, título, descrição e ações — para listas, buscas e caixas sem conteúdo.',
    variants: ['size: sm | md | lg'],
    parts: ['Root', 'Icon', 'Title', 'Description', 'Actions'],
    origins: ['Caraminholas · sacola vazia'],
    references: ['Radix (padrão de composição)'],
    code: '<EmptyState><EmptyState.Icon /><EmptyState.Title>Nada por aqui</EmptyState.Title><EmptyState.Description>Crie o primeiro projeto para começar.</EmptyState.Description><EmptyState.Actions><button className="few-button few-button--primary">Novo projeto</button></EmptyState.Actions></EmptyState>',
    vueCode: '<FewEmptyState>\n  <FewEmptyStateIcon />\n  <FewEmptyStateTitle>Nada por aqui</FewEmptyStateTitle>\n  <FewEmptyStateDescription>Crie o primeiro projeto para começar.</FewEmptyStateDescription>\n  <FewEmptyStateActions>\n    <button class="few-button few-button--primary">Novo projeto</button>\n  </FewEmptyStateActions>\n</FewEmptyState>',
  }),
];
