// packages/angular/src/components/data/accordion.ts
// Accordion: painéis expansíveis com roving focus (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/data/accordion.tsx.
// Adaptação documentada: `value` é sempre `string[]` (mesmo com `type="single"`), diferente da união `string | string[]`
// do React — mais simples de tipar em template Angular e consistente com o `value: string[]` de `Tree`.
// `Accordion.Header` não tem prop `level`: o consumidor escreve a tag de heading (`<h3 fewAccordionHeader>`) diretamente.
import { Component, Directive, ElementRef, booleanAttribute, computed, inject, input, model } from '@angular/core';
import type { Orientation } from '@fewcompany/core';
import { fewId } from '../../lib/ids.js';
import { moveFocus } from '../../lib/roving.js';
import { dataAttr } from '../../lib/attrs.js';

export type FewAccordionType = 'single' | 'multiple';

@Directive({
  selector: '[fewAccordion]',
  exportAs: 'fewAccordion',
  host: { class: 'few-accordion', '[attr.data-orientation]': 'orientation()' },
})
export class FewAccordion {
  readonly baseId = fewId('accordion');
  readonly type = input<FewAccordionType>('single');
  /** Só vale para `type="single"`: permite fechar o item aberto sem abrir outro. */
  readonly collapsible = input(false, { transform: booleanAttribute });
  readonly value = model<string[]>([]);
  readonly orientation = input<Orientation>('vertical');

  isOpen(itemValue: string) { return this.value().includes(itemValue); }
  toggle(itemValue: string) {
    if (this.type() === 'multiple') {
      this.value.update(list => (list.includes(itemValue) ? list.filter(v => v !== itemValue) : [...list, itemValue]));
      return;
    }
    this.value.update(current => {
      const isOpen = current.includes(itemValue);
      if (isOpen) return this.collapsible() ? [] : current;
      return [itemValue];
    });
  }
}

@Directive({
  selector: '[fewAccordionItem]',
  host: {
    class: 'few-accordion-item',
    '[attr.data-state]': 'accordion.isOpen(value()) ? "open" : "closed"',
    '[attr.data-disabled]': 'dataAttr(disabled())',
  },
})
export class FewAccordionItem {
  protected readonly accordion = inject(FewAccordion);
  readonly value = input.required<string>();
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly open = computed(() => this.accordion.isOpen(this.value()));
  protected readonly dataAttr = dataAttr;
}

/** O consumidor escreve a tag de heading (`h1`–`h6`); esta diretiva só aplica a classe. */
@Directive({ selector: '[fewAccordionHeader]', host: { class: 'few-accordion-header' } })
export class FewAccordionHeader {}

@Directive({
  selector: 'button[fewAccordionTrigger]',
  host: {
    class: 'few-accordion-trigger',
    type: 'button',
    '[id]': 'id',
    '[attr.aria-expanded]': 'item.open()',
    '[attr.aria-controls]': 'contentId',
    '[disabled]': 'isDisabled()',
    '[attr.data-state]': 'item.open() ? "open" : "closed"',
    '[attr.data-disabled]': 'dataAttr(isDisabled())',
    '(click)': 'onClick()',
    '(keydown)': 'onKeydown($event)',
  },
})
export class FewAccordionTrigger {
  private readonly accordion = inject(FewAccordion);
  protected readonly item = inject(FewAccordionItem);
  private readonly hostRef = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly disabled = input(false, { transform: booleanAttribute });
  protected readonly isDisabled = computed(() => this.disabled() || this.item.disabled());
  protected readonly dataAttr = dataAttr;
  protected get id() { return `${this.accordion.baseId}-trigger-${this.item.value()}`; }
  protected get contentId() { return `${this.accordion.baseId}-content-${this.item.value()}`; }

  protected onClick() { if (!this.isDisabled()) this.accordion.toggle(this.item.value()); }
  protected onKeydown(event: KeyboardEvent) {
    if (event.defaultPrevented) return;
    const container = this.hostRef.nativeElement.closest('.few-accordion');
    const target = moveFocus(container, '.few-accordion-trigger', event.key, { orientation: this.accordion.orientation() });
    if (target) event.preventDefault();
  }
}

/** `<div fewAccordionContent>`: envolve o conteúdo projetado num `.few-accordion-content-inner`, igual ao React. */
@Component({
  selector: '[fewAccordionContent]',
  host: {
    class: 'few-accordion-content',
    role: 'region',
    '[id]': 'id',
    '[attr.aria-labelledby]': 'labelledBy',
    '[attr.inert]': 'item.open() ? null : ""',
    '[attr.data-state]': 'item.open() ? "open" : "closed"',
  },
  template: `<div class="few-accordion-content-inner"><ng-content></ng-content></div>`,
})
export class FewAccordionContent {
  private readonly accordion = inject(FewAccordion);
  protected readonly item = inject(FewAccordionItem);
  protected get id() { return `${this.accordion.baseId}-content-${this.item.value()}`; }
  protected get labelledBy() { return `${this.accordion.baseId}-trigger-${this.item.value()}`; }
}

/** Importe tudo de uma vez: `imports: [FEW_ACCORDION]`. */
export const FEW_ACCORDION = [FewAccordion, FewAccordionItem, FewAccordionHeader, FewAccordionTrigger, FewAccordionContent] as const;

// packages/react/src/components/data/accordion.tsx
"use client";
// Accordion: painéis expansíveis com roving focus (ver docs/composition.md, padrão Radix Accordion).
import { useId, useRef, type ComponentProps, type KeyboardEvent } from 'react';
import type { Orientation } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';
import { moveFocus } from '../../lib/roving.js';

interface AccordionContextValue { baseId: string; type: 'single' | 'multiple'; values: string[]; toggle: (value: string) => void; orientation: Orientation }
const [AccordionProvider, useAccordionCtx] = createContext<AccordionContextValue>('Accordion');
interface AccordionItemContextValue { value: string; open: boolean; disabled: boolean }
const [AccordionItemProvider, useAccordionItemCtx] = createContext<AccordionItemContextValue>('Accordion.Item');

export interface AccordionProps extends Omit<ComponentProps<'div'>, 'defaultValue'> {
  asChild?: boolean;
  type?: 'single' | 'multiple';
  /** Só vale para `type="single"`: permite fechar o item aberto sem abrir outro. */
  collapsible?: boolean;
  value?: string | string[];
  defaultValue?: string | string[];
  onValueChange?: (value: string | string[]) => void;
  orientation?: Orientation;
}
function AccordionRoot({ asChild, type = 'single', collapsible = false, value, defaultValue, onValueChange, orientation = 'vertical', className, ...props }: AccordionProps) {
  const baseId = useId();
  const resolvedDefault = defaultValue ?? (type === 'multiple' ? [] : '');
  const [raw, setRaw] = useControllableState<string | string[]>({ value, defaultValue: resolvedDefault, onChange: onValueChange });
  const values = Array.isArray(raw) ? raw : raw ? [raw] : [];
  function toggle(itemValue: string) {
    if (type === 'multiple') {
      setRaw(current => {
        const list = Array.isArray(current) ? current : [];
        return list.includes(itemValue) ? list.filter(v => v !== itemValue) : [...list, itemValue];
      });
    } else {
      setRaw(current => (current === itemValue ? (collapsible ? '' : current) : itemValue));
    }
  }
  const Comp = asChild ? Slot : 'div';
  return <AccordionProvider value={{ baseId, type, values, toggle, orientation }}>
    <Comp {...props} className={cx('few-accordion', className)} data-orientation={orientation} />
  </AccordionProvider>;
}

export interface AccordionItemProps extends ComponentProps<'div'> { asChild?: boolean; value: string; disabled?: boolean }
function AccordionItem({ asChild, value, disabled = false, className, ...props }: AccordionItemProps) {
  const { values } = useAccordionCtx('Accordion.Item');
  const open = values.includes(value);
  const Comp = asChild ? Slot : 'div';
  return <AccordionItemProvider value={{ value, open, disabled }}>
    <Comp {...props} className={cx('few-accordion-item', className)} data-state={open ? 'open' : 'closed'} data-disabled={dataAttr(disabled)} />
  </AccordionItemProvider>;
}

export interface AccordionHeaderProps extends ComponentProps<'h3'> { asChild?: boolean; level?: 1 | 2 | 3 | 4 | 5 | 6 }
function AccordionHeader({ asChild, level = 3, className, ...props }: AccordionHeaderProps) {
  const Tag = (`h${level}`) as 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
  const Comp = asChild ? Slot : Tag;
  return <Comp {...props} className={cx('few-accordion-header', className)} />;
}

export interface AccordionTriggerProps extends ComponentProps<'button'> { asChild?: boolean }
function AccordionTrigger({ asChild, className, disabled, onClick, onKeyDown, ...props }: AccordionTriggerProps) {
  const { baseId, toggle, orientation } = useAccordionCtx('Accordion.Trigger');
  const { value, open, disabled: itemDisabled } = useAccordionItemCtx('Accordion.Trigger');
  const isDisabled = disabled || itemDisabled;
  const ref = useRef<HTMLButtonElement>(null);
  const Comp = asChild ? Slot : 'button';
  function handleKeyDown(event: KeyboardEvent<HTMLButtonElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented) return;
    const container = ref.current?.closest('.few-accordion') ?? null;
    const target = moveFocus(container, '.few-accordion-trigger', event.key, { orientation });
    if (target) event.preventDefault();
  }
  return <Comp {...props} ref={ref} type="button" id={`${baseId}-trigger-${value}`} aria-expanded={open} aria-controls={`${baseId}-content-${value}`}
    disabled={isDisabled} data-state={open ? 'open' : 'closed'} data-disabled={dataAttr(isDisabled)} className={cx('few-accordion-trigger', className)}
    onClick={(event) => { onClick?.(event); if (!event.defaultPrevented && !isDisabled) toggle(value); }}
    onKeyDown={handleKeyDown} />;
}

export interface AccordionContentProps extends ComponentProps<'div'> { asChild?: boolean }
function AccordionContent({ asChild, className, children, ...props }: AccordionContentProps) {
  const { baseId } = useAccordionCtx('Accordion.Content');
  const { value, open } = useAccordionItemCtx('Accordion.Content');
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} role="region" id={`${baseId}-content-${value}`} aria-labelledby={`${baseId}-trigger-${value}`} inert={open ? undefined : true}
    data-state={open ? 'open' : 'closed'} className={cx('few-accordion-content', className)}>
    <div className="few-accordion-content-inner">{children}</div>
  </Comp>;
}

/** Accordion composto: <Accordion type="single" collapsible><Accordion.Item value="a"><Accordion.Header><Accordion.Trigger/></Accordion.Header><Accordion.Content/></Accordion.Item></Accordion> */
export const Accordion = Object.assign(AccordionRoot, { Root: AccordionRoot, Item: AccordionItem, Header: AccordionHeader, Trigger: AccordionTrigger, Content: AccordionContent });
export { AccordionRoot, AccordionItem, AccordionHeader, AccordionTrigger, AccordionContent };
