// packages/angular/src/components/data/table.ts
// Table: primitiva composta de tabela acessível (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/data/table.tsx.
// DataTable (data-table.ts) é o atalho orientado a dados sobre esta base.
import { Component, Directive, booleanAttribute, input, output } from '@angular/core';
import { dataAttr } from '../../lib/attrs.js';

export type FewTableDensity = 'compact' | 'comfortable';
export type FewTableSortDirection = 'ascending' | 'descending' | 'none';

/**
 * Raiz: `<div fewTable>` gera a `<table class="few-table">` e projeta o conteúdo (caption/thead/tbody/tfoot) dentro dela.
 * O wrapper (host, `<div>`) recebe `role="region"` + `tabindex="0"` para rolagem horizontal acessível — equivalente ao `Table.Root` do React.
 */
@Component({
  selector: '[fewTable]',
  host: {
    class: 'few-table-root',
    role: 'region',
    tabindex: '0',
    '[attr.data-density]': 'density()',
  },
  template: `<table class="few-table" [class.few-table--striped]="striped()" [attr.data-density]="density()" [attr.data-sticky-header]="dataAttr(stickyHeader())"><ng-content></ng-content></table>`,
})
export class FewTable {
  readonly density = input<FewTableDensity>('comfortable');
  readonly striped = input(false, { transform: booleanAttribute });
  readonly stickyHeader = input(false, { transform: booleanAttribute });
  protected readonly dataAttr = dataAttr;
}

@Directive({ selector: '[fewTableCaption]', host: { class: 'few-table-caption' } })
export class FewTableCaption {}

@Directive({ selector: '[fewTableHeader]', host: { class: 'few-table-header' } })
export class FewTableHeader {}

@Directive({ selector: '[fewTableBody]', host: { class: 'few-table-body' } })
export class FewTableBody {}

@Directive({ selector: '[fewTableFooter]', host: { class: 'few-table-footer' } })
export class FewTableFooter {}

@Directive({
  selector: '[fewTableRow]',
  host: {
    class: 'few-table-row',
    '[attr.data-state]': 'selected() ? "selected" : null',
    '[attr.aria-selected]': 'selected() || null',
  },
})
export class FewTableRow {
  readonly selected = input(false, { transform: booleanAttribute });
}

/** `<th fewTableHead>`: `scope="col"` fixo. `sortable` desenha o botão interno de ordenação (ignora conteúdo simples). */
@Component({
  selector: 'th[fewTableHead]',
  host: {
    class: 'few-table-head',
    scope: 'col',
    '[attr.aria-sort]': 'sortable() ? sortDirection() : null',
    '[attr.data-numeric]': 'dataAttr(numeric())',
  },
  template: `
    @if (sortable()) {
      <button type="button" class="few-table-sort" [attr.data-direction]="sortDirection()" (click)="sort.emit()">
        <span><ng-content></ng-content></span><span aria-hidden="true" class="few-table-sort-icon"></span>
      </button>
    } @else {
      <ng-content></ng-content>
    }
  `,
})
export class FewTableHead {
  readonly numeric = input(false, { transform: booleanAttribute });
  readonly sortable = input(false, { transform: booleanAttribute });
  readonly sortDirection = input<FewTableSortDirection>('none');
  readonly sort = output<void>();
  protected readonly dataAttr = dataAttr;
}

@Directive({
  selector: '[fewTableCell]',
  host: { class: 'few-table-cell', '[attr.data-numeric]': 'dataAttr(numeric())' },
})
export class FewTableCell {
  readonly numeric = input(false, { transform: booleanAttribute });
  protected readonly dataAttr = dataAttr;
}

/** `<tr fewTableEmpty [colSpan]="n">Mensagem</tr>`: envolve o conteúdo projetado num único `<td>`. */
@Component({
  selector: 'tr[fewTableEmpty]',
  host: { class: 'few-table-empty' },
  template: `<td [attr.colspan]="colSpan()" class="few-table-empty-cell"><ng-content></ng-content></td>`,
})
export class FewTableEmpty {
  readonly colSpan = input.required<number>();
}

/** Importe tudo de uma vez: `imports: [FEW_TABLE]`. */
export const FEW_TABLE = [FewTable, FewTableCaption, FewTableHeader, FewTableBody, FewTableFooter, FewTableRow, FewTableHead, FewTableCell, FewTableEmpty] as const;

// packages/react/src/components/data/table.tsx
"use client";
// Table: primitiva composta de tabela acessível (ver docs/composition.md). DataTable é o atalho orientado a dados sobre esta base.
import type { ComponentProps, ReactNode } from 'react';
import { Slot } from '../../lib/slot.js';
import { cx, dataAttr } from '../../lib/cx.js';

export interface TableProps extends ComponentProps<'div'> {
  asChild?: boolean;
  /** Densidade do espaçamento de células. */
  density?: 'compact' | 'comfortable';
  /** Zebra nas linhas do corpo. */
  striped?: boolean;
  /** Fixa o cabeçalho ao rolar verticalmente. */
  stickyHeader?: boolean;
}
/**
 * Wrapper com rolagem horizontal (`role="region"`, focável) + `<table>`.
 * `asChild` aplica os atributos do wrapper diretamente na `<table>` (sem a div de rolagem) —
 * útil quando a tabela já vive dentro de um contêiner com overflow próprio.
 */
function TableRoot({ asChild, density = 'comfortable', striped = false, stickyHeader = false, className, children, ...props }: TableProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} role="region" tabIndex={0} className={cx('few-table-root', className)} data-density={density}>
    <table className={cx('few-table', striped && 'few-table--striped')} data-density={density} data-sticky-header={dataAttr(stickyHeader)}>{children}</table>
  </Comp>;
}

export interface TableCaptionProps extends ComponentProps<'caption'> { asChild?: boolean }
function TableCaption({ asChild, className, ...props }: TableCaptionProps) {
  const Comp = asChild ? Slot : 'caption';
  return <Comp {...props} className={cx('few-table-caption', className)} />;
}

export interface TableHeaderProps extends ComponentProps<'thead'> { asChild?: boolean }
function TableHeader({ asChild, className, ...props }: TableHeaderProps) {
  const Comp = asChild ? Slot : 'thead';
  return <Comp {...props} className={cx('few-table-header', className)} />;
}

export interface TableBodyProps extends ComponentProps<'tbody'> { asChild?: boolean }
function TableBody({ asChild, className, ...props }: TableBodyProps) {
  const Comp = asChild ? Slot : 'tbody';
  return <Comp {...props} className={cx('few-table-body', className)} />;
}

export interface TableFooterProps extends ComponentProps<'tfoot'> { asChild?: boolean }
function TableFooter({ asChild, className, ...props }: TableFooterProps) {
  const Comp = asChild ? Slot : 'tfoot';
  return <Comp {...props} className={cx('few-table-footer', className)} />;
}

export interface TableRowProps extends ComponentProps<'tr'> { asChild?: boolean; selected?: boolean }
function TableRow({ asChild, selected, className, ...props }: TableRowProps) {
  const Comp = asChild ? Slot : 'tr';
  return <Comp {...props} className={cx('few-table-row', className)} data-state={selected ? 'selected' : undefined} aria-selected={selected || undefined} />;
}

export interface TableHeadProps extends ComponentProps<'th'> {
  asChild?: boolean;
  numeric?: boolean;
  /** Ativa o botão interno de ordenação. Ignora `asChild` (o `<th>` precisa do `scope`). */
  sortable?: boolean;
  sortDirection?: 'ascending' | 'descending' | 'none';
  onSort?: () => void;
}
function TableHead({ asChild, numeric, sortable = false, sortDirection = 'none', onSort, className, children, ...props }: TableHeadProps) {
  const Comp = asChild && !sortable ? Slot : 'th';
  return <Comp {...props} scope="col" aria-sort={sortable ? sortDirection : undefined} data-numeric={dataAttr(numeric)} className={cx('few-table-head', className)}>
    {sortable
      ? <button type="button" className="few-table-sort" onClick={onSort} data-direction={sortDirection}>
          <span>{children}</span><span aria-hidden="true" className="few-table-sort-icon" />
        </button>
      : children}
  </Comp>;
}

export interface TableCellProps extends ComponentProps<'td'> { asChild?: boolean; numeric?: boolean }
function TableCell({ asChild, numeric, className, ...props }: TableCellProps) {
  const Comp = asChild ? Slot : 'td';
  return <Comp {...props} data-numeric={dataAttr(numeric)} className={cx('few-table-cell', className)} />;
}

export interface TableEmptyProps extends ComponentProps<'tr'> { asChild?: boolean; colSpan: number; children?: ReactNode }
function TableEmpty({ asChild, colSpan, className, children, ...props }: TableEmptyProps) {
  const Comp = asChild ? Slot : 'tr';
  return <Comp {...props} className={cx('few-table-empty', className)}><td colSpan={colSpan} className="few-table-empty-cell">{children}</td></Comp>;
}

/** Table composto: <Table.Root><Table.Caption/><Table.Header>…</Table.Header><Table.Body>…</Table.Body></Table.Root> */
export const Table = Object.assign(TableRoot, { Root: TableRoot, Caption: TableCaption, Header: TableHeader, Body: TableBody, Footer: TableFooter, Row: TableRow, Head: TableHead, Cell: TableCell, Empty: TableEmpty });
export { TableRoot, TableCaption, TableHeader, TableBody, TableFooter, TableRow, TableHead, TableCell, TableEmpty };
