// packages/angular/src/components/overlays/alert-dialog.ts
// AlertDialog: mesma base do Dialog (<dialog> nativo), mas role=alertdialog, sem fechar no clique fora, Cancel/Action
// em vez de Close, foco inicial no Cancel (autofocus nativo, lido pelo showModal() a cada abertura).
// Espelha packages/react/src/components/overlays/alert-dialog.tsx.
import { Directive, DestroyRef, ElementRef, effect, inject, model, signal } from '@angular/core';
import { fewId } from '../../lib/ids.js';

/** Raiz: `<div fewAlertDialog [(open)]="aberto">`. Sempre modal, sem fechar no clique fora. */
@Directive({ selector: '[fewAlertDialog]', exportAs: 'fewAlertDialog' })
export class FewAlertDialog {
  readonly open = model(false);
  readonly baseId = fewId('alert-dialog');
  private readonly hasDescriptionState = signal(false);
  readonly hasDescription = this.hasDescriptionState.asReadonly();
  private readonly triggerElement = signal<HTMLElement | null>(null);
  get titleId(): string { return `${this.baseId}-title`; }
  get descriptionId(): string { return `${this.baseId}-description`; }
  setOpen(open: boolean): void { this.open.set(open); }
  setHasDescription(value: boolean): void { this.hasDescriptionState.set(value); }
  setTriggerElement(element: HTMLElement): void { this.triggerElement.set(element); }
  focusTrigger(): void { this.triggerElement()?.focus(); }
}

@Directive({
  selector: '[fewAlertDialogTrigger]',
  host: {
    class: 'few-alert-dialog-trigger', type: 'button',
    '[attr.aria-haspopup]': "'dialog'", '[attr.aria-expanded]': 'alertDialog.open()',
    '(click)': 'onClick()',
  },
})
export class FewAlertDialogTrigger {
  protected readonly alertDialog = inject(FewAlertDialog);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  constructor() { this.alertDialog.setTriggerElement(this.el.nativeElement); }
  protected onClick(): void { this.alertDialog.setOpen(true); }
}

/** Content: `<dialog fewAlertDialogContent>`. Sem fechar no clique fora — só Cancel/Action/Escape. */
@Directive({
  selector: 'dialog[fewAlertDialogContent]',
  host: {
    class: 'few-alert-dialog', role: 'alertdialog',
    '[attr.aria-labelledby]': 'alertDialog.titleId', '[attr.aria-describedby]': 'alertDialog.hasDescription() ? alertDialog.descriptionId : null',
    '(cancel)': 'onCancel($event)', '(close)': 'onClose()',
  },
})
export class FewAlertDialogContent {
  protected readonly alertDialog = inject(FewAlertDialog);
  private readonly el = inject<ElementRef<HTMLDialogElement>>(ElementRef);
  constructor() {
    effect(() => {
      const el = this.el.nativeElement;
      if (typeof document === 'undefined' || typeof el.showModal !== 'function') return;
      const open = this.alertDialog.open();
      if (open && !el.open) el.showModal();
      if (!open && el.open) el.close();
    });
  }
  protected onCancel(event: Event): void { event.preventDefault(); this.alertDialog.setOpen(false); }
  protected onClose(): void { this.alertDialog.setOpen(false); this.alertDialog.focusTrigger(); }
}

@Directive({ selector: '[fewAlertDialogTitle]', host: { class: 'few-alert-dialog-title', '[id]': 'alertDialog.titleId' } })
export class FewAlertDialogTitle {
  protected readonly alertDialog = inject(FewAlertDialog);
}

@Directive({ selector: '[fewAlertDialogDescription]', host: { class: 'few-alert-dialog-description few-muted', '[id]': 'alertDialog.descriptionId' } })
export class FewAlertDialogDescription {
  protected readonly alertDialog = inject(FewAlertDialog);
  constructor() {
    this.alertDialog.setHasDescription(true);
    inject(DestroyRef).onDestroy(() => this.alertDialog.setHasDescription(false));
  }
}

/** Recebe o foco inicial (autofocus nativo lido pelo showModal() a cada abertura). */
@Directive({ selector: '[fewAlertDialogCancel]', host: { class: 'few-alert-dialog-cancel', type: 'button', autofocus: '', '(click)': 'alertDialog.setOpen(false)' } })
export class FewAlertDialogCancel {
  protected readonly alertDialog = inject(FewAlertDialog);
}

/**
 * Ação principal: fecha o diálogo ao clicar. Simplificação assumida (sem `asChild`/Slot): o `(click)` do próprio
 * consumidor no mesmo elemento roda como um listener independente — não há como checar `preventDefault()` dele
 * para cancelar o fechamento, diferente do React (que embrulha o onClick do consumidor).
 */
@Directive({ selector: '[fewAlertDialogAction]', host: { class: 'few-alert-dialog-action', type: 'button', '(click)': 'alertDialog.setOpen(false)' } })
export class FewAlertDialogAction {
  protected readonly alertDialog = inject(FewAlertDialog);
}

/** Importe tudo de uma vez: `imports: [FEW_ALERT_DIALOG]`. */
export const FEW_ALERT_DIALOG = [
  FewAlertDialog, FewAlertDialogTrigger, FewAlertDialogContent, FewAlertDialogTitle, FewAlertDialogDescription, FewAlertDialogCancel, FewAlertDialogAction,
] as const;

// packages/react/src/components/overlays/alert-dialog.tsx
"use client";
// AlertDialog: mesma base do Dialog (<dialog> nativo), mas role=alertdialog, sem fechar no clique fora,
// Cancel/Action em vez de Close, foco inicial no Cancel (autofocus nativo, ver docs/composition.md #8).
import { useEffect, useId, useRef, useState, type ComponentProps, type ReactNode, type RefObject } from 'react';
import { createContext } from '../../lib/context.js';
import { Slot } from '../../lib/slot.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx } from '../../lib/cx.js';
import { setRef } from '../../lib/compose-refs.js';

interface AlertDialogContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
  titleId: string;
  descriptionId: string;
  hasDescription: boolean;
  setHasDescription: (value: boolean) => void;
  contentRef: RefObject<HTMLDialogElement | null>;
  triggerRef: RefObject<HTMLElement | null>;
}
const [AlertDialogProvider, useAlertDialog] = createContext<AlertDialogContextValue>('AlertDialog');

export interface AlertDialogProps { children?: ReactNode; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void }
/** AlertDialog.Root: só contexto (sempre modal, sem fechar fora). */
function AlertDialogRoot({ children, open: openProp, defaultOpen = false, onOpenChange }: AlertDialogProps) {
  const baseId = useId();
  const [open, setOpen] = useControllableState({ value: openProp, defaultValue: defaultOpen, onChange: onOpenChange });
  const [hasDescription, setHasDescription] = useState(false);
  const contentRef = useRef<HTMLDialogElement>(null);
  const triggerRef = useRef<HTMLElement>(null);
  return (
    <AlertDialogProvider value={{ open, setOpen, titleId: `${baseId}-title`, descriptionId: `${baseId}-description`, hasDescription, setHasDescription, contentRef, triggerRef }}>
      {children}
    </AlertDialogProvider>
  );
}

export interface AlertDialogTriggerProps extends ComponentProps<'button'> { asChild?: boolean }
function AlertDialogTrigger({ asChild, className, onClick, ...props }: AlertDialogTriggerProps) {
  const { open, setOpen, triggerRef } = useAlertDialog('AlertDialog.Trigger');
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} ref={(node: HTMLElement | null) => setRef(triggerRef, node)} type="button" aria-haspopup="dialog" aria-expanded={open} className={cx('few-alert-dialog-trigger', className)}
    onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) setOpen(true); }} />;
}

export interface AlertDialogContentProps extends Omit<ComponentProps<'dialog'>, 'onCancel' | 'onClose' | 'open'> {}
/** Content não suporta asChild: depende do <dialog> nativo. Sem fechar no clique fora — só Cancel/Action/Escape. */
function AlertDialogContent({ className, children, ...props }: AlertDialogContentProps) {
  const { open, setOpen, titleId, descriptionId, hasDescription, contentRef, triggerRef } = useAlertDialog('AlertDialog.Content');
  useEffect(() => {
    const dialog = contentRef.current;
    if (!dialog) return;
    if (open && !dialog.open) dialog.showModal();
    if (!open && dialog.open) dialog.close();
  }, [open, contentRef]);
  return (
    <dialog {...props} ref={contentRef} role="alertdialog" className={cx('few-alert-dialog', className)}
      aria-labelledby={titleId} aria-describedby={hasDescription ? descriptionId : undefined}
      onCancel={(event) => { event.preventDefault(); setOpen(false); }}
      onClose={() => { setOpen(false); triggerRef.current?.focus(); }}>
      {children}
    </dialog>
  );
}

export interface AlertDialogTitleProps extends ComponentProps<'h2'> { asChild?: boolean }
function AlertDialogTitle({ asChild, className, ...props }: AlertDialogTitleProps) {
  const { titleId } = useAlertDialog('AlertDialog.Title');
  const Comp = asChild ? Slot : 'h2';
  return <Comp {...props} id={titleId} className={cx('few-alert-dialog-title', className)} />;
}

export interface AlertDialogDescriptionProps extends ComponentProps<'p'> { asChild?: boolean }
function AlertDialogDescription({ asChild, className, ...props }: AlertDialogDescriptionProps) {
  const { descriptionId, setHasDescription } = useAlertDialog('AlertDialog.Description');
  useEffect(() => { setHasDescription(true); return () => setHasDescription(false); }, [setHasDescription]);
  const Comp = asChild ? Slot : 'p';
  return <Comp {...props} id={descriptionId} className={cx('few-alert-dialog-description', 'few-muted', className)} />;
}

export interface AlertDialogCancelProps extends ComponentProps<'button'> { asChild?: boolean }
/** Recebe o foco inicial (autofocus nativo lido pelo showModal() a cada abertura). */
function AlertDialogCancel({ asChild, className, onClick, ...props }: AlertDialogCancelProps) {
  const { setOpen } = useAlertDialog('AlertDialog.Cancel');
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} type="button" autoFocus className={cx('few-alert-dialog-cancel', className)}
    onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) setOpen(false); }} />;
}

export interface AlertDialogActionProps extends ComponentProps<'button'> { asChild?: boolean }
/** Ação principal: executa o onClick do consumidor e fecha o diálogo (como Radix, que embrulha Close). */
function AlertDialogAction({ asChild, className, onClick, ...props }: AlertDialogActionProps) {
  const { setOpen } = useAlertDialog('AlertDialog.Action');
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} type="button" className={cx('few-alert-dialog-action', className)}
    onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) setOpen(false); }} />;
}

/** AlertDialog composto: <AlertDialog><AlertDialog.Trigger/><AlertDialog.Content><AlertDialog.Title/><AlertDialog.Cancel/><AlertDialog.Action/></AlertDialog.Content></AlertDialog> */
export const AlertDialog = Object.assign(AlertDialogRoot, { Root: AlertDialogRoot, Trigger: AlertDialogTrigger, Content: AlertDialogContent, Title: AlertDialogTitle, Description: AlertDialogDescription, Cancel: AlertDialogCancel, Action: AlertDialogAction });
export { AlertDialogRoot, AlertDialogTrigger, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogCancel, AlertDialogAction };
