// packages/angular/src/components/overlays/drawer.ts
// Drawer: mesma base do Dialog (<dialog> nativo, showModal/close), lateral. Animação via CSS (@starting-style,
// mesmo CSS do core); movimento reduzido já é zerado em base.css. Espelha
// packages/react/src/components/overlays/drawer.tsx.
import { Directive, DestroyRef, ElementRef, booleanAttribute, effect, inject, input, model, signal } from '@angular/core';
import { fewId } from '../../lib/ids.js';

export type DrawerSide = 'left' | 'right' | 'top' | 'bottom';

/** Raiz: `<div fewDrawer [(open)]="aberto" side="bottom">`. `side` fica no Root: estiliza Handle e Content juntos. */
@Directive({ selector: '[fewDrawer]', exportAs: 'fewDrawer' })
export class FewDrawer {
  readonly open = model(false);
  readonly side = input<DrawerSide>('right');
  readonly baseId = fewId('drawer');
  private readonly hasDescriptionState = signal(false);
  readonly hasDescription = this.hasDescriptionState.asReadonly();
  private readonly triggerElement = signal<HTMLElement | null>(null);
  get titleId(): string { return `${this.baseId}-title`; }
  get descriptionId(): string { return `${this.baseId}-description`; }
  setOpen(open: boolean): void { this.open.set(open); }
  setHasDescription(value: boolean): void { this.hasDescriptionState.set(value); }
  setTriggerElement(element: HTMLElement): void { this.triggerElement.set(element); }
  focusTrigger(): void { this.triggerElement()?.focus(); }
}

@Directive({
  selector: '[fewDrawerTrigger]',
  host: {
    class: 'few-drawer-trigger', type: 'button',
    '[attr.aria-haspopup]': "'dialog'", '[attr.aria-expanded]': 'drawer.open()',
    '(click)': 'onClick()',
  },
})
export class FewDrawerTrigger {
  protected readonly drawer = inject(FewDrawer);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  constructor() { this.drawer.setTriggerElement(this.el.nativeElement); }
  protected onClick(): void { this.drawer.setOpen(true); }
}

/** Content: `<dialog fewDrawerContent>` — depende do `<dialog>` nativo. */
@Directive({
  selector: 'dialog[fewDrawerContent]',
  host: {
    class: 'few-drawer', '[attr.data-side]': 'drawer.side()', '[style.--few-drawer-size]': 'size() ?? null',
    '[attr.aria-labelledby]': 'drawer.titleId', '[attr.aria-describedby]': 'drawer.hasDescription() ? drawer.descriptionId : null',
    '(cancel)': 'onCancel($event)', '(close)': 'onClose()', '(click)': 'onClick($event)',
  },
})
export class FewDrawerContent {
  protected readonly drawer = inject(FewDrawer);
  private readonly el = inject<ElementRef<HTMLDialogElement>>(ElementRef);
  /** Tamanho via `--few-drawer-size` (largura em left/right, altura em top/bottom). Ex.: "420px", "70vh". */
  readonly size = input<string | undefined>(undefined);
  readonly dismissOnOutsideClick = input(true, { transform: booleanAttribute });
  constructor() {
    effect(() => {
      const el = this.el.nativeElement;
      if (typeof document === 'undefined' || typeof el.showModal !== 'function') return;
      const open = this.drawer.open();
      if (open && !el.open) el.showModal();
      if (!open && el.open) el.close();
    });
  }
  protected onCancel(event: Event): void { event.preventDefault(); this.drawer.setOpen(false); }
  protected onClose(): void { this.drawer.setOpen(false); this.drawer.focusTrigger(); }
  protected onClick(event: MouseEvent): void { if (this.dismissOnOutsideClick() && event.target === this.el.nativeElement) this.drawer.setOpen(false); }
}

@Directive({ selector: '[fewDrawerTitle]', host: { class: 'few-drawer-title', '[id]': 'drawer.titleId' } })
export class FewDrawerTitle {
  protected readonly drawer = inject(FewDrawer);
}

@Directive({ selector: '[fewDrawerDescription]', host: { class: 'few-drawer-description few-muted', '[id]': 'drawer.descriptionId' } })
export class FewDrawerDescription {
  protected readonly drawer = inject(FewDrawer);
  constructor() {
    this.drawer.setHasDescription(true);
    inject(DestroyRef).onDestroy(() => this.drawer.setHasDescription(false));
  }
}

@Directive({ selector: '[fewDrawerClose]', host: { class: 'few-drawer-close', type: 'button', '(click)': 'drawer.setOpen(false)' } })
export class FewDrawerClose {
  protected readonly drawer = inject(FewDrawer);
}

/** Indicador visual de arrasto (decorativo), comum em drawers `side="bottom"`. */
@Directive({ selector: '[fewDrawerHandle]', host: { class: 'few-drawer-handle', 'aria-hidden': 'true' } })
export class FewDrawerHandle {}

/** Importe tudo de uma vez: `imports: [FEW_DRAWER]`. */
export const FEW_DRAWER = [
  FewDrawer, FewDrawerTrigger, FewDrawerContent, FewDrawerTitle, FewDrawerDescription, FewDrawerClose, FewDrawerHandle,
] as const;

// packages/react/src/components/overlays/drawer.tsx
"use client";
// Drawer: mesma base do Dialog (<dialog> nativo, showModal/close), lateral. Animação via CSS (@starting-style),
// movimento reduzido já é zerado em base.css. Ver docs/composition.md #8.
import { useEffect, useId, useRef, useState, type ComponentProps, type CSSProperties, type ReactNode, type RefObject } from 'react';
import { createContext } from '../../lib/context.js';
import { Slot } from '../../lib/slot.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx } from '../../lib/cx.js';
import { setRef } from '../../lib/compose-refs.js';

export type DrawerSide = 'left' | 'right' | 'top' | 'bottom';

interface DrawerContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
  side: DrawerSide;
  titleId: string;
  descriptionId: string;
  hasDescription: boolean;
  setHasDescription: (value: boolean) => void;
  contentRef: RefObject<HTMLDialogElement | null>;
  triggerRef: RefObject<HTMLElement | null>;
}
const [DrawerProvider, useDrawer] = createContext<DrawerContextValue>('Drawer');

export interface DrawerProps { children?: ReactNode; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void; side?: DrawerSide }
/** Drawer.Root: só contexto. `side` fica no Root porque estiliza Handle e Content juntos. */
function DrawerRoot({ children, open: openProp, defaultOpen = false, onOpenChange, side = 'right' }: DrawerProps) {
  const baseId = useId();
  const [open, setOpen] = useControllableState({ value: openProp, defaultValue: defaultOpen, onChange: onOpenChange });
  const [hasDescription, setHasDescription] = useState(false);
  const contentRef = useRef<HTMLDialogElement>(null);
  const triggerRef = useRef<HTMLElement>(null);
  return (
    <DrawerProvider value={{ open, setOpen, side, titleId: `${baseId}-title`, descriptionId: `${baseId}-description`, hasDescription, setHasDescription, contentRef, triggerRef }}>
      {children}
    </DrawerProvider>
  );
}

export interface DrawerTriggerProps extends ComponentProps<'button'> { asChild?: boolean }
function DrawerTrigger({ asChild, className, onClick, ...props }: DrawerTriggerProps) {
  const { open, setOpen, triggerRef } = useDrawer('Drawer.Trigger');
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} ref={(node: HTMLElement | null) => setRef(triggerRef, node)} type="button" aria-haspopup="dialog" aria-expanded={open} className={cx('few-drawer-trigger', className)}
    onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) setOpen(true); }} />;
}

export interface DrawerContentProps extends Omit<ComponentProps<'dialog'>, 'onCancel' | 'onClose' | 'open'> {
  /** Tamanho via `--few-drawer-size` (largura em left/right, altura em top/bottom). Ex.: "420px", "70vh". */
  size?: string;
  dismissOnOutsideClick?: boolean;
}
/** Content não suporta asChild: depende do <dialog> nativo. */
function DrawerContent({ size, dismissOnOutsideClick = true, className, children, style, ...props }: DrawerContentProps) {
  const { open, setOpen, side, titleId, descriptionId, hasDescription, contentRef, triggerRef } = useDrawer('Drawer.Content');
  useEffect(() => {
    const dialog = contentRef.current;
    if (!dialog) return;
    if (open && !dialog.open) dialog.showModal();
    if (!open && dialog.open) dialog.close();
  }, [open, contentRef]);
  return (
    <dialog {...props} ref={contentRef} className={cx('few-drawer', className)} data-side={side}
      style={size ? ({ ...style, '--few-drawer-size': size } as CSSProperties) : style}
      aria-labelledby={titleId} aria-describedby={hasDescription ? descriptionId : undefined}
      onCancel={(event) => { event.preventDefault(); setOpen(false); }}
      onClose={() => { setOpen(false); triggerRef.current?.focus(); }}
      onClick={(event) => { if (dismissOnOutsideClick && event.target === contentRef.current) setOpen(false); }}>
      {children}
    </dialog>
  );
}

export interface DrawerTitleProps extends ComponentProps<'h2'> { asChild?: boolean }
function DrawerTitle({ asChild, className, ...props }: DrawerTitleProps) {
  const { titleId } = useDrawer('Drawer.Title');
  const Comp = asChild ? Slot : 'h2';
  return <Comp {...props} id={titleId} className={cx('few-drawer-title', className)} />;
}

export interface DrawerDescriptionProps extends ComponentProps<'p'> { asChild?: boolean }
function DrawerDescription({ asChild, className, ...props }: DrawerDescriptionProps) {
  const { descriptionId, setHasDescription } = useDrawer('Drawer.Description');
  useEffect(() => { setHasDescription(true); return () => setHasDescription(false); }, [setHasDescription]);
  const Comp = asChild ? Slot : 'p';
  return <Comp {...props} id={descriptionId} className={cx('few-drawer-description', 'few-muted', className)} />;
}

export interface DrawerCloseProps extends ComponentProps<'button'> { asChild?: boolean }
function DrawerClose({ asChild, className, onClick, ...props }: DrawerCloseProps) {
  const { setOpen } = useDrawer('Drawer.Close');
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} type="button" className={cx('few-drawer-close', className)}
    onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) setOpen(false); }} />;
}

export interface DrawerHandleProps extends ComponentProps<'div'> { asChild?: boolean }
/** Indicador visual de arrasto (decorativo), comum em drawers `side="bottom"`. */
function DrawerHandle({ asChild, className, ...props }: DrawerHandleProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} aria-hidden="true" className={cx('few-drawer-handle', className)} />;
}

/** Drawer composto: <Drawer side="right"><Drawer.Trigger/><Drawer.Content><Drawer.Handle/><Drawer.Title/><Drawer.Close/></Drawer.Content></Drawer> */
export const Drawer = Object.assign(DrawerRoot, { Root: DrawerRoot, Trigger: DrawerTrigger, Content: DrawerContent, Title: DrawerTitle, Description: DrawerDescription, Close: DrawerClose, Handle: DrawerHandle });
export { DrawerRoot, DrawerTrigger, DrawerContent, DrawerTitle, DrawerDescription, DrawerClose, DrawerHandle };
