// packages/angular/src/components/overlays/popover.ts
// Popover: não modal, sobre popover="manual" + setupTopLayer (top layer nativo, herda tema) em vez de Portal.
// Posiciona com setupPosition, fecha com setupDismiss. Espelha packages/react/src/components/overlays/popover.tsx.
import { Directive, ElementRef, effect, inject, input, model, signal } from '@angular/core';
import type { FloatingAlign, FloatingSide } from '@fewcompany/core';
import { dataState } from '../../lib/attrs.js';
import { fewId } from '../../lib/ids.js';
import { focusableItems } from '../../lib/roving.js';
import { setupDismiss } from '../../lib/dismiss.js';
import { setupPosition } from '../../lib/position.js';
import { setupTopLayer } from '../../lib/top-layer.js';

/** Raiz: `<div fewPopover [(open)]="aberto">`. Não modal — não bloqueia o resto da página. */
@Directive({ selector: '[fewPopover]', exportAs: 'fewPopover' })
export class FewPopover {
  readonly open = model(false);
  readonly baseId = fewId('popover');
  private readonly sideState = signal<FloatingSide>('bottom');
  private readonly anchorElementState = signal<Element | null>(null);
  private readonly triggerElement = signal<HTMLElement | null>(null);
  get contentId(): string { return `${this.baseId}-popover`; }
  setOpen(open: boolean): void { this.open.set(open); }
  setSide(side: FloatingSide): void { this.sideState.set(side); }
  side(): FloatingSide { return this.sideState(); }
  /** Usado pelo `fewPopoverAnchor` (âncora explícita), sempre sobrescreve. */
  setAnchorElement(element: Element): void { this.anchorElementState.set(element); }
  /** Usado pelo Trigger: só define a âncora se nenhum `fewPopoverAnchor` já definiu uma. */
  setAnchorFallback(element: Element): void { if (!this.anchorElementState()) this.anchorElementState.set(element); }
  anchorElement(): Element | null { return this.anchorElementState(); }
  setTriggerElement(element: HTMLElement): void { this.triggerElement.set(element); }
  focusTrigger(): void { this.triggerElement()?.focus(); }
}

/** Ancora o posicionamento em outro elemento que não o Trigger (opcional). */
@Directive({ selector: '[fewPopoverAnchor]', host: { class: 'few-popover-anchor' } })
export class FewPopoverAnchor {
  private readonly popover = inject(FewPopover);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  constructor() { this.popover.setAnchorElement(this.el.nativeElement); }
}

@Directive({
  selector: '[fewPopoverTrigger]',
  host: {
    class: 'few-popover-trigger', type: 'button',
    '[attr.aria-haspopup]': "'dialog'", '[attr.aria-expanded]': 'popover.open()',
    '[attr.aria-controls]': 'popover.open() ? popover.contentId : null',
    '(click)': 'onClick()',
  },
})
export class FewPopoverTrigger {
  protected readonly popover = inject(FewPopover);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  constructor() {
    this.popover.setAnchorFallback(this.el.nativeElement);
    this.popover.setTriggerElement(this.el.nativeElement);
  }
  protected onClick(): void { this.popover.setOpen(!this.popover.open()); }
}

@Directive({
  selector: '[fewPopoverContent]',
  host: {
    class: 'few-popover', role: 'dialog', '[attr.tabindex]': '-1', popover: 'manual',
    '[id]': 'popover.contentId', '[attr.data-state]': 'dataState(popover.open())', '[attr.data-side]': 'position().side',
    '[style.position]': "'fixed'", '[style.top.px]': 'position().top', '[style.left.px]': 'position().left',
    '(keydown)': 'onKeyDown($event)',
  },
})
export class FewPopoverContent {
  protected readonly popover = inject(FewPopover);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly side = input<FloatingSide>('bottom');
  readonly align = input<FloatingAlign>('center');
  readonly offset = input(8);
  protected readonly dataState = dataState;
  protected readonly position = setupPosition(this.popover.open, () => this.popover.anchorElement(), () => this.el.nativeElement, () => ({ side: this.side(), align: this.align(), offset: this.offset() }));
  constructor() {
    setupTopLayer(this.popover.open, () => this.el.nativeElement);
    setupDismiss(this.popover.open, () => this.popover.setOpen(false), () => [this.el.nativeElement, this.popover.anchorElement()]);
    effect(() => this.popover.setSide(this.position().side));
    effect(() => {
      if (!this.popover.open() || typeof document === 'undefined') return;
      const el = this.el.nativeElement;
      queueMicrotask(() => { (focusableItems(el, 'a[href],button,input,textarea,select,[tabindex]')[0] ?? el).focus(); });
    });
    effect(() => { if (!this.popover.open()) this.popover.focusTrigger(); });
  }
  protected onKeyDown(event: KeyboardEvent): void {
    if (event.defaultPrevented) return;
    if (event.key === 'Escape') { event.preventDefault(); this.popover.setOpen(false); }
  }
}

@Directive({ selector: '[fewPopoverClose]', host: { class: 'few-popover-close', type: 'button', '(click)': 'popover.setOpen(false)' } })
export class FewPopoverClose {
  protected readonly popover = inject(FewPopover);
}

/** Seta decorativa; a direção é lida em CSS via `data-side` (herdado do Content através do Root). */
@Directive({ selector: '[fewPopoverArrow]', host: { class: 'few-popover-arrow', 'aria-hidden': 'true', '[attr.data-side]': 'popover.side()' } })
export class FewPopoverArrow {
  protected readonly popover = inject(FewPopover);
}

/** Importe tudo de uma vez: `imports: [FEW_POPOVER]`. */
export const FEW_POPOVER = [FewPopover, FewPopoverAnchor, FewPopoverTrigger, FewPopoverContent, FewPopoverClose, FewPopoverArrow] as const;

// packages/react/src/components/overlays/popover.tsx
"use client";
// Popover: não modal, sobre popover="manual" + useTopLayer (top layer nativo, herda tema) em vez de Portal
// (ver docs/composition.md #8). Posiciona com usePosition, fecha com useDismiss.
import { useEffect, useId, useRef, useState, type ComponentProps, type ReactNode, type RefObject } from 'react';
import { createContext } from '../../lib/context.js';
import { Slot } from '../../lib/slot.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx } from '../../lib/cx.js';
import { setRef } from '../../lib/compose-refs.js';
import { useDismiss } from '../../lib/use-dismiss.js';
import { usePosition, type Align, type Side } from '../../lib/use-position.js';
import { useTopLayer } from '../../lib/use-top-layer.js';
import { focusableItems } from '../../lib/roving.js';

interface PopoverContextValue {
  open: boolean;
  setOpen: (open: boolean) => void;
  contentId: string;
  anchorRef: RefObject<HTMLElement | null>;
  triggerRef: RefObject<HTMLElement | null>;
  contentRef: RefObject<HTMLDivElement | null>;
  side: Side;
  setSide: (side: Side) => void;
}
const [PopoverProvider, usePopover] = createContext<PopoverContextValue>('Popover');

export interface PopoverProps { children?: ReactNode; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void; modal?: false }
/** Popover.Root: só contexto (não modal — não bloqueia o resto da página). */
function PopoverRoot({ children, open: openProp, defaultOpen = false, onOpenChange }: PopoverProps) {
  const baseId = useId();
  const [open, setOpen] = useControllableState({ value: openProp, defaultValue: defaultOpen, onChange: onOpenChange });
  const [side, setSide] = useState<Side>('bottom');
  const anchorRef = useRef<HTMLElement>(null);
  const triggerRef = useRef<HTMLElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  return (
    <PopoverProvider value={{ open, setOpen, contentId: `${baseId}-popover`, anchorRef, triggerRef, contentRef, side, setSide }}>
      {children}
    </PopoverProvider>
  );
}

export interface PopoverAnchorProps extends ComponentProps<'span'> { asChild?: boolean }
/** Ancora o posicionamento em outro elemento que não o Trigger (opcional). */
function PopoverAnchor({ asChild, className, ...props }: PopoverAnchorProps) {
  const { anchorRef } = usePopover('Popover.Anchor');
  const Comp = asChild ? Slot : 'span';
  return <Comp {...props} ref={(node: HTMLElement | null) => setRef(anchorRef, node)} className={cx('few-popover-anchor', className)} />;
}

export interface PopoverTriggerProps extends ComponentProps<'button'> { asChild?: boolean }
function PopoverTrigger({ asChild, className, onClick, ...props }: PopoverTriggerProps) {
  const { open, setOpen, contentId, anchorRef, triggerRef } = usePopover('Popover.Trigger');
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} ref={(node: HTMLElement | null) => { setRef(triggerRef, node); if (!anchorRef.current) setRef(anchorRef, node); }} type="button"
    aria-haspopup="dialog" aria-expanded={open} aria-controls={open ? contentId : undefined} className={cx('few-popover-trigger', className)}
    onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) setOpen(!open); }} />;
}

export interface PopoverContentProps extends ComponentProps<'div'> {
  asChild?: boolean; side?: Side; align?: Align; offset?: number;
}
function PopoverContent({ asChild, side = 'bottom', align = 'center', offset = 8, className, style, onKeyDown, ...props }: PopoverContentProps) {
  const { open, setOpen, contentId, anchorRef, triggerRef, contentRef, setSide } = usePopover('Popover.Content');
  const position = usePosition(anchorRef, contentRef, { side, align, offset, open });
  useTopLayer(contentRef, open);
  useDismiss(open, () => setOpen(false), [contentRef, anchorRef]);
  useEffect(() => { setSide(position.side); }, [position.side, setSide]);
  useEffect(() => {
    if (!open) return;
    const target = focusableItems(contentRef.current, 'a[href],button,input,textarea,select,[tabindex]')[0] ?? contentRef.current;
    target?.focus();
  }, [open, contentRef]);
  useEffect(() => {
    if (open) return;
    triggerRef.current?.focus();
  }, [open, triggerRef]);
  const Comp = asChild ? Slot : 'div';
  return (
    <Comp {...props} ref={contentRef} popover="manual" id={contentId} role="dialog" tabIndex={-1} data-state={open ? 'open' : 'closed'} data-side={position.side}
      className={cx('few-popover', className)} style={{ ...position.style, ...style }}
      onKeyDown={(event) => { onKeyDown?.(event); if (!event.defaultPrevented && event.key === 'Escape') { event.preventDefault(); setOpen(false); } }}>
      {props.children}
    </Comp>
  );
}

export interface PopoverCloseProps extends ComponentProps<'button'> { asChild?: boolean }
function PopoverClose({ asChild, className, onClick, ...props }: PopoverCloseProps) {
  const { setOpen } = usePopover('Popover.Close');
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} type="button" className={cx('few-popover-close', className)}
    onClick={(event) => { onClick?.(event); if (!event.defaultPrevented) setOpen(false); }} />;
}

export interface PopoverArrowProps extends ComponentProps<'span'> { asChild?: boolean }
/** Seta decorativa; a direção é lida em CSS via `data-side` (herdado do Content). */
function PopoverArrow({ asChild, className, ...props }: PopoverArrowProps) {
  const { side } = usePopover('Popover.Arrow');
  const Comp = asChild ? Slot : 'span';
  return <Comp {...props} aria-hidden="true" data-side={side} className={cx('few-popover-arrow', className)} />;
}

/** Popover composto: <Popover><Popover.Trigger/><Popover.Content><Popover.Arrow/></Popover.Content></Popover> */
export const Popover = Object.assign(PopoverRoot, { Root: PopoverRoot, Anchor: PopoverAnchor, Trigger: PopoverTrigger, Content: PopoverContent, Close: PopoverClose, Arrow: PopoverArrow });
export { PopoverRoot, PopoverAnchor, PopoverTrigger, PopoverContent, PopoverClose, PopoverArrow };
