// packages/angular/src/components/overlays/tooltip.ts
// Tooltip: popover="manual" + setupTopLayer (top layer nativo) em vez de Portal, posicionado com setupPosition.
// Provider (opcional) compartilha o "skip delay": depois que um tooltip abre, os próximos abrem sem esperar o
// delay se o ponteiro migrar de um trigger para outro dentro de `skipDelayDuration`. Espelha
// packages/react/src/components/overlays/tooltip.tsx.
import { Directive, DestroyRef, ElementRef, booleanAttribute, effect, inject, input, model, signal } from '@angular/core';
import type { FloatingAlign, FloatingSide } from '@fewcompany/core';
import { dataState } from '../../lib/attrs.js';
import { fewId } from '../../lib/ids.js';
import { setupDismiss } from '../../lib/dismiss.js';
import { setupPosition } from '../../lib/position.js';
import { setupTopLayer } from '../../lib/top-layer.js';

/** Compartilha o delay de abertura entre vários `fewTooltip` (opcional): `<div fewTooltipProvider>`. */
@Directive({ selector: '[fewTooltipProvider]', exportAs: 'fewTooltipProvider' })
export class FewTooltipProvider {
  readonly delayDuration = input(700);
  readonly skipDelayDuration = input(300);
  private skipping = false;
  private skipTimer?: ReturnType<typeof setTimeout>;
  constructor() { inject(DestroyRef).onDestroy(() => clearTimeout(this.skipTimer)); }
  isSkipping(): boolean { return this.skipping; }
  onOpen(): void { this.skipping = true; clearTimeout(this.skipTimer); }
  onClose(): void {
    clearTimeout(this.skipTimer);
    this.skipTimer = setTimeout(() => { this.skipping = false; }, this.skipDelayDuration());
  }
}

/** Raiz: `<div fewTooltip [(open)]="aberto">`. */
@Directive({ selector: '[fewTooltip]', exportAs: 'fewTooltip' })
export class FewTooltip {
  private readonly provider = inject(FewTooltipProvider, { optional: true });
  readonly open = model(false);
  readonly delay = input<number | undefined>(undefined);
  readonly baseId = fewId('tooltip');
  private readonly sideState = signal<FloatingSide>('top');
  private readonly triggerElementState = signal<HTMLElement | null>(null);
  private openTimer?: ReturnType<typeof setTimeout>;
  get contentId(): string { return `${this.baseId}-tooltip`; }
  side(): FloatingSide { return this.sideState(); }
  setSide(side: FloatingSide): void { this.sideState.set(side); }
  triggerElement(): HTMLElement | null { return this.triggerElementState(); }
  setTriggerElement(element: HTMLElement): void { this.triggerElementState.set(element); }
  private effectiveDelay(): number { return this.delay() ?? this.provider?.delayDuration() ?? 700; }
  /** Abre no hover (com delay) ou imediatamente no foco (`immediate`), salvo se já estiver "pulando" o delay. */
  requestOpen(immediate = false): void {
    clearTimeout(this.openTimer);
    if (immediate || this.provider?.isSkipping()) { this.provider?.onOpen(); this.open.set(true); return; }
    this.openTimer = setTimeout(() => { this.provider?.onOpen(); this.open.set(true); }, this.effectiveDelay());
  }
  requestClose(): void {
    clearTimeout(this.openTimer);
    this.provider?.onClose();
    this.open.set(false);
  }
  constructor() { inject(DestroyRef).onDestroy(() => clearTimeout(this.openTimer)); }
}

/** Abre no hover (com delay) e no foco (imediato); fecha no blur, pointerleave, pointerdown ou Escape (via dismiss do Content). Não abre se `disabled`. */
@Directive({
  selector: '[fewTooltipTrigger]',
  host: {
    class: 'few-tooltip-trigger', type: 'button',
    '[attr.disabled]': 'disabled() ? "" : null', '[attr.aria-describedby]': 'tooltip.contentId',
    '(pointerenter)': 'onPointerEnter($event)', '(pointerleave)': 'tooltip.requestClose()',
    '(pointerdown)': 'tooltip.requestClose()', '(focus)': 'onFocus()', '(blur)': 'tooltip.requestClose()',
  },
})
export class FewTooltipTrigger {
  protected readonly tooltip = inject(FewTooltip);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly disabled = input(false, { transform: booleanAttribute });
  constructor() { this.tooltip.setTriggerElement(this.el.nativeElement); }
  protected onPointerEnter(event: PointerEvent): void { if (!this.disabled() && event.pointerType !== 'touch') this.tooltip.requestOpen(); }
  protected onFocus(): void { if (!this.disabled()) this.tooltip.requestOpen(true); }
}

@Directive({
  selector: '[fewTooltipContent]',
  host: {
    class: 'few-tooltip', role: 'tooltip', popover: 'manual',
    '[id]': 'tooltip.contentId', '[attr.data-state]': 'dataState(tooltip.open())', '[attr.data-side]': 'position().side',
    '[style.position]': "'fixed'", '[style.top.px]': 'position().top', '[style.left.px]': 'position().left',
  },
})
export class FewTooltipContent {
  protected readonly tooltip = inject(FewTooltip);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly side = input<FloatingSide>('top');
  readonly align = input<FloatingAlign>('center');
  readonly offset = input(6);
  protected readonly dataState = dataState;
  protected readonly position = setupPosition(this.tooltip.open, () => this.tooltip.triggerElement(), () => this.el.nativeElement, () => ({ side: this.side(), align: this.align(), offset: this.offset() }));
  constructor() {
    setupTopLayer(this.tooltip.open, () => this.el.nativeElement);
    setupDismiss(this.tooltip.open, () => this.tooltip.requestClose(), () => [this.tooltip.triggerElement(), this.el.nativeElement], { outside: false });
    effect(() => this.tooltip.setSide(this.position().side));
  }
}

@Directive({ selector: '[fewTooltipArrow]', host: { class: 'few-tooltip-arrow', 'aria-hidden': 'true', '[attr.data-side]': 'tooltip.side()' } })
export class FewTooltipArrow {
  protected readonly tooltip = inject(FewTooltip);
}

/** Importe tudo de uma vez: `imports: [FEW_TOOLTIP]`. */
export const FEW_TOOLTIP = [FewTooltipProvider, FewTooltip, FewTooltipTrigger, FewTooltipContent, FewTooltipArrow] as const;

// packages/react/src/components/overlays/tooltip.tsx
"use client";
// Tooltip: popover="manual" + useTopLayer (top layer nativo) em vez de Portal, posicionado com usePosition.
// Provider compartilha o "skip delay": depois que um tooltip abre, os próximos abrem sem esperar o delay
// se o ponteiro migrar de um trigger para outro dentro de `skipDelayDuration`.
import { useCallback, useEffect, useId, useMemo, useRef, useState, type ComponentProps, type ReactNode, type RefObject } from 'react';
import { createContext } from '../../lib/context.js';
import { Slot } from '../../lib/slot.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx } from '../../lib/cx.js';
import { setRef } from '../../lib/compose-refs.js';
import { useDismiss } from '../../lib/use-dismiss.js';
import { usePosition, type Align, type Side } from '../../lib/use-position.js';
import { useTopLayer } from '../../lib/use-top-layer.js';

interface TooltipProviderContextValue { delayDuration: number; isSkipping: () => boolean; onOpen: () => void; onClose: () => void }
const [TooltipProviderRoot, , useOptionalTooltipProvider] = createContext<TooltipProviderContextValue>('Tooltip.Provider');

export interface TooltipProviderProps { children?: ReactNode; delayDuration?: number; skipDelayDuration?: number }
/** Compartilha o delay de abertura entre vários Tooltip.Root (opcional). */
function TooltipProvider({ children, delayDuration = 700, skipDelayDuration = 300 }: TooltipProviderProps) {
  const skipping = useRef(false);
  const skipTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const value = useMemo<TooltipProviderContextValue>(() => ({
    delayDuration,
    isSkipping: () => skipping.current,
    onOpen: () => { skipping.current = true; window.clearTimeout(skipTimer.current); },
    onClose: () => { window.clearTimeout(skipTimer.current); skipTimer.current = setTimeout(() => { skipping.current = false; }, skipDelayDuration); },
  }), [delayDuration, skipDelayDuration]);
  return <TooltipProviderRoot value={value}>{children}</TooltipProviderRoot>;
}

interface TooltipContextValue {
  open: boolean;
  contentId: string;
  triggerRef: RefObject<HTMLElement | null>;
  contentRef: RefObject<HTMLDivElement | null>;
  requestOpen: (immediate?: boolean) => void;
  requestClose: () => void;
  side: Side;
  setSide: (side: Side) => void;
}
const [TooltipRootProvider, useTooltip] = createContext<TooltipContextValue>('Tooltip');

export interface TooltipProps { children?: ReactNode; open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void; delay?: number }
function TooltipRoot({ children, open: openProp, defaultOpen = false, onOpenChange, delay }: TooltipProps) {
  const baseId = useId();
  const provider = useOptionalTooltipProvider();
  const [open, setOpen] = useControllableState({ value: openProp, defaultValue: defaultOpen, onChange: onOpenChange });
  const [side, setSide] = useState<Side>('top');
  const openTimer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  const triggerRef = useRef<HTMLElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const effectiveDelay = delay ?? provider?.delayDuration ?? 700;
  const requestOpen = useCallback((immediate = false) => {
    window.clearTimeout(openTimer.current);
    if (immediate || provider?.isSkipping()) { provider?.onOpen(); setOpen(true); return; }
    openTimer.current = setTimeout(() => { provider?.onOpen(); setOpen(true); }, effectiveDelay);
  }, [effectiveDelay, provider, setOpen]);
  const requestClose = useCallback(() => {
    window.clearTimeout(openTimer.current);
    provider?.onClose();
    setOpen(false);
  }, [provider, setOpen]);
  useEffect(() => () => window.clearTimeout(openTimer.current), []);
  return (
    <TooltipRootProvider value={{ open, contentId: `${baseId}-tooltip`, triggerRef, contentRef, requestOpen, requestClose, side, setSide }}>
      {children}
    </TooltipRootProvider>
  );
}

export interface TooltipTriggerProps extends ComponentProps<'button'> { asChild?: boolean }
/** Abre no hover (com delay) e no foco (imediato); fecha no blur, pointerleave, pointerdown ou Escape. Não abre se `disabled`. */
function TooltipTrigger({ asChild, className, disabled, onPointerEnter, onPointerLeave, onPointerDown, onFocus, onBlur, ...props }: TooltipTriggerProps) {
  const { contentId, triggerRef, requestOpen, requestClose } = useTooltip('Tooltip.Trigger');
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} ref={(node: HTMLElement | null) => setRef(triggerRef, node)} type="button" disabled={disabled} aria-describedby={contentId} className={cx('few-tooltip-trigger', className)}
    onPointerEnter={(event) => { onPointerEnter?.(event); if (!event.defaultPrevented && !disabled && event.pointerType !== 'touch') requestOpen(); }}
    onPointerLeave={(event) => { onPointerLeave?.(event); if (!event.defaultPrevented) requestClose(); }}
    onPointerDown={(event) => { onPointerDown?.(event); if (!event.defaultPrevented) requestClose(); }}
    onFocus={(event) => { onFocus?.(event); if (!event.defaultPrevented && !disabled) requestOpen(true); }}
    onBlur={(event) => { onBlur?.(event); if (!event.defaultPrevented) requestClose(); }} />;
}

export interface TooltipContentProps extends ComponentProps<'div'> { asChild?: boolean; side?: Side; align?: Align; offset?: number }
function TooltipContent({ asChild, side = 'top', align = 'center', offset = 6, className, style, ...props }: TooltipContentProps) {
  const { open, contentId, triggerRef, contentRef, requestClose, setSide } = useTooltip('Tooltip.Content');
  const position = usePosition(triggerRef, contentRef, { side, align, offset, open });
  useTopLayer(contentRef, open);
  useDismiss(open, requestClose, [triggerRef, contentRef], { outside: false });
  useEffect(() => { setSide(position.side); }, [position.side, setSide]);
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} ref={contentRef} id={contentId} role="tooltip" popover="manual" data-state={open ? 'open' : 'closed'} data-side={position.side}
    className={cx('few-tooltip', className)} style={{ ...position.style, ...style }} />;
}

export interface TooltipArrowProps extends ComponentProps<'span'> { asChild?: boolean }
function TooltipArrow({ asChild, className, ...props }: TooltipArrowProps) {
  const { side } = useTooltip('Tooltip.Arrow');
  const Comp = asChild ? Slot : 'span';
  return <Comp {...props} aria-hidden="true" data-side={side} className={cx('few-tooltip-arrow', className)} />;
}

/** Tooltip composto: <Tooltip.Provider><Tooltip><Tooltip.Trigger/><Tooltip.Content><Tooltip.Arrow/></Tooltip.Content></Tooltip></Tooltip.Provider> */
export const Tooltip = Object.assign(TooltipRoot, { Provider: TooltipProvider, Root: TooltipRoot, Trigger: TooltipTrigger, Content: TooltipContent, Arrow: TooltipArrow });
export { TooltipProvider, TooltipRoot, TooltipTrigger, TooltipContent, TooltipArrow };
