// apps/catalog/demos/actions.tsx
"use client";
import { useState } from 'react';
import { Button, IconButton, ButtonGroup, Toggle, ToggleGroup, SplitButton, Link } from '@fewcompany/ui';
import type { DemoMap } from './types';
// Demos da categoria "Ações". Chave = id do registry. Cada demo é um componente React interativo.

function ButtonDemo() {
  const [status, setStatus] = useState<'idle' | 'loading' | 'done'>('idle');
  function handleSave() {
    if (status === 'loading') return;
    setStatus('loading');
    setTimeout(() => {
      setStatus('done');
      setTimeout(() => setStatus('idle'), 1600);
    }, 700);
  }
  return (
    <div className="demo-stack">
      <div className="demo-row">
        <Button variant="primary">Primário</Button>
        <Button variant="secondary">Secundário</Button>
        <Button variant="ghost">Discreto</Button>
        <Button variant="danger">Excluir conta</Button>
        <Button variant="link">Ver detalhes</Button>
      </div>
      <div className="demo-row">
        <Button size="sm">Pequeno</Button>
        <Button size="md">Médio</Button>
        <Button size="lg">Grande</Button>
      </div>
      <div className="demo-row">
        <Button onClick={handleSave} loading={status === 'loading'}>
          {status === 'done' ? 'Salvo ✓' : 'Salvar alterações'}
        </Button>
        <p className="few-muted" role="status">
          {status === 'loading' ? 'Salvando…' : status === 'done' ? 'Alterações salvas com sucesso.' : 'Clique para simular o salvamento.'}
        </p>
      </div>
      <div className="demo-row">
        <Button asChild>
          <a href="#exemplo-aschild" onClick={event => event.preventDefault()}>Renderizado como link (asChild)</a>
        </Button>
      </div>
    </div>
  );
}

function IconButtonDemo() {
  const [liked, setLiked] = useState(false);
  return (
    <div className="demo-row">
      <IconButton aria-label={liked ? 'Remover curtida' : 'Curtir'} variant={liked ? 'primary' : 'secondary'} onClick={() => setLiked(value => !value)}>{liked ? '♥' : '♡'}</IconButton>
      <IconButton aria-label="Editar" variant="ghost" shape="square">✎</IconButton>
      <IconButton aria-label="Excluir" variant="danger">🗑</IconButton>
      <IconButton aria-label="Carregando" loading />
    </div>
  );
}

function ButtonGroupDemo() {
  const [view, setView] = useState<'lista' | 'grade'>('lista');
  return (
    <div className="demo-stack">
      <ButtonGroup attached>
        <Button variant={view === 'lista' ? 'primary' : 'secondary'} onClick={() => setView('lista')}>Lista</Button>
        <Button variant={view === 'grade' ? 'primary' : 'secondary'} onClick={() => setView('grade')}>Grade</Button>
      </ButtonGroup>
      <p className="few-muted">Visualização atual: {view}</p>
      <ButtonGroup attached orientation="vertical" size="sm" variant="secondary">
        <Button>Um</Button>
        <Button>Dois</Button>
        <Button>Três</Button>
      </ButtonGroup>
    </div>
  );
}

function ToggleDemo() {
  const [bold, setBold] = useState(false);
  const [italic, setItalic] = useState(true);
  return (
    <div className="demo-row">
      <Toggle pressed={bold} onPressedChange={setBold} aria-label="Negrito"><strong>N</strong></Toggle>
      <Toggle pressed={italic} onPressedChange={setItalic} aria-label="Itálico"><em>I</em></Toggle>
      <Toggle defaultPressed size="sm">Favorito</Toggle>
    </div>
  );
}

function ToggleGroupDemo() {
  const [align, setAlign] = useState('left');
  const [tags, setTags] = useState<string[]>(['few']);
  return (
    <div className="demo-stack">
      <ToggleGroup type="single" value={align} onValueChange={setAlign} aria-label="Alinhamento do texto">
        <ToggleGroup.Item value="left">Esquerda</ToggleGroup.Item>
        <ToggleGroup.Item value="center">Centro</ToggleGroup.Item>
        <ToggleGroup.Item value="right">Direita</ToggleGroup.Item>
      </ToggleGroup>
      <p className="few-muted">Alinhamento: {align}</p>
      <ToggleGroup type="multiple" value={tags} onValueChange={setTags} aria-label="Marcadores">
        <ToggleGroup.Item value="few">Few</ToggleGroup.Item>
        <ToggleGroup.Item value="ui">UI</ToggleGroup.Item>
        <ToggleGroup.Item value="beta">Beta</ToggleGroup.Item>
      </ToggleGroup>
      <p className="few-muted">Marcadores: {tags.length ? tags.join(', ') : 'nenhum'}</p>
    </div>
  );
}

function SplitButtonDemo() {
  const [message, setMessage] = useState('Nenhuma ação executada ainda.');
  return (
    <div className="demo-stack demo-narrow">
      <SplitButton>
        <SplitButton.Action onClick={() => setMessage('Publicado.')}>Publicar</SplitButton.Action>
        <SplitButton.Trigger aria-label="Mais ações de publicação" />
        <SplitButton.Content>
          <SplitButton.Item onClick={() => setMessage('Salvo como rascunho.')}>Salvar como rascunho</SplitButton.Item>
          <SplitButton.Item onClick={() => setMessage('Agendado para amanhã.')}>Agendar publicação</SplitButton.Item>
          <SplitButton.Item disabled onClick={() => setMessage('Duplicado.')}>Duplicar (em breve)</SplitButton.Item>
        </SplitButton.Content>
      </SplitButton>
      <p className="few-muted" role="status">{message}</p>
    </div>
  );
}

function LinkDemo() {
  return (
    <div className="demo-stack">
      <div className="demo-row">
        <Link href="#exemplo" onClick={event => event.preventDefault()}>Link padrão</Link>
        <Link href="#exemplo" variant="muted" onClick={event => event.preventDefault()}>Link discreto</Link>
        <Link href="#exemplo" variant="brand" onClick={event => event.preventDefault()}>Link de marca</Link>
      </div>
      <div className="demo-row">
        <Link href="#exemplo" underline="always" onClick={event => event.preventDefault()}>Sempre sublinhado</Link>
        <Link href="#exemplo" underline="none" onClick={event => event.preventDefault()}>Sem sublinhado</Link>
      </div>
      <Link href="https://fewcompany.com" external>Site da Few Company</Link>
      <Link asChild variant="brand">
        <a href="#exemplo-aschild" onClick={event => event.preventDefault()}>Renderizado via asChild</a>
      </Link>
    </div>
  );
}

export const actionsDemos: DemoMap = {
  button: ButtonDemo,
  'icon-button': IconButtonDemo,
  'button-group': ButtonGroupDemo,
  toggle: ToggleDemo,
  'toggle-group': ToggleGroupDemo,
  'split-button': SplitButtonDemo,
  link: LinkDemo,
};

// packages/angular/src/demos/actions.ts
// Hosts de demonstração/teste da categoria "Ações" (pasta components/actions). Um @Component por id do registry, selector few-demo-<id>.
import { Component, type Type } from '@angular/core';
import { FewButton } from '../components/actions/button.js';
import { FewButtonGroup } from '../components/actions/button-group.js';
import { FewIconButton } from '../components/actions/icon-button.js';
import { FewToggle } from '../components/actions/toggle.js';
import { FEW_TOGGLE_GROUP } from '../components/actions/toggle-group.js';
import { FEW_SPLIT_BUTTON } from '../components/actions/split-button.js';
import { FewLink } from '../components/actions/link.js';

@Component({
  selector: 'few-demo-button',
  imports: [FewButton],
  template: `
    <div class="demo-stack">
      <div class="demo-row">
        <button fewButton variant="primary">Primário</button>
        <button fewButton variant="secondary">Secundário</button>
        <button fewButton variant="ghost">Discreto</button>
        <button fewButton variant="danger">Excluir conta</button>
        <button fewButton variant="link">Ver detalhes</button>
      </div>
      <div class="demo-row">
        <button fewButton size="sm">Pequeno</button>
        <button fewButton size="md">Médio</button>
        <button fewButton size="lg">Grande</button>
      </div>
      <div class="demo-row">
        <button fewButton loading>Salvando alterações</button>
        <a fewButton variant="secondary" href="#exemplo">Renderizado como link</a>
      </div>
    </div>
  `,
})
export class DemoButton {}

@Component({
  selector: 'few-demo-icon-button',
  imports: [FewIconButton],
  template: `
    <div class="demo-row">
      <button fewIconButton aria-label="Curtir" variant="secondary">♡</button>
      <button fewIconButton aria-label="Editar" variant="ghost" shape="square">✎</button>
      <button fewIconButton aria-label="Excluir" variant="danger">🗑</button>
      <button fewIconButton aria-label="Carregando" loading></button>
    </div>
  `,
})
export class DemoIconButton {}

@Component({
  selector: 'few-demo-button-group',
  imports: [FewButtonGroup, FewButton],
  template: `
    <div class="demo-stack">
      <div fewButtonGroup attached>
        <button fewButton variant="primary">Lista</button>
        <button fewButton variant="secondary">Grade</button>
      </div>
      <div fewButtonGroup attached orientation="vertical" size="sm" variant="secondary">
        <button fewButton>Um</button>
        <button fewButton>Dois</button>
        <button fewButton>Três</button>
      </div>
    </div>
  `,
})
export class DemoButtonGroup {}

@Component({
  selector: 'few-demo-toggle',
  imports: [FewToggle],
  template: `
    <div class="demo-row">
      <button fewToggle aria-label="Negrito" [pressed]="true"><strong>N</strong></button>
      <button fewToggle aria-label="Itálico"><em>I</em></button>
      <button fewToggle size="sm">Favorito</button>
    </div>
  `,
})
export class DemoToggle {}

@Component({
  selector: 'few-demo-toggle-group',
  imports: [FEW_TOGGLE_GROUP],
  template: `
    <div class="demo-stack">
      <div fewToggleGroup type="single" [value]="'left'" aria-label="Alinhamento do texto">
        <button fewToggleGroupItem value="left">Esquerda</button>
        <button fewToggleGroupItem value="center">Centro</button>
        <button fewToggleGroupItem value="right">Direita</button>
      </div>
      <div fewToggleGroup type="multiple" [value]="['few']" aria-label="Marcadores">
        <button fewToggleGroupItem value="few">Few</button>
        <button fewToggleGroupItem value="ui">UI</button>
        <button fewToggleGroupItem value="beta">Beta</button>
      </div>
    </div>
  `,
})
export class DemoToggleGroup {}

@Component({
  selector: 'few-demo-split-button',
  imports: [FEW_SPLIT_BUTTON],
  template: `
    <div fewSplitButton class="demo-narrow">
      <button fewSplitButtonAction>Publicar</button>
      <button fewSplitButtonTrigger aria-label="Mais ações de publicação"></button>
      <div fewSplitButtonContent>
        <button fewSplitButtonItem>Salvar como rascunho</button>
        <button fewSplitButtonItem>Agendar publicação</button>
        <button fewSplitButtonItem disabled>Duplicar (em breve)</button>
      </div>
    </div>
  `,
})
export class DemoSplitButton {}

@Component({
  selector: 'few-demo-link',
  imports: [FewLink],
  template: `
    <div class="demo-stack">
      <div class="demo-row">
        <a fewLink href="#exemplo">Link padrão</a>
        <a fewLink href="#exemplo" variant="muted">Link discreto</a>
        <a fewLink href="#exemplo" variant="brand">Link de marca</a>
      </div>
      <div class="demo-row">
        <a fewLink href="#exemplo" underline="always">Sempre sublinhado</a>
        <a fewLink href="#exemplo" underline="none">Sem sublinhado</a>
      </div>
      <a fewLink href="https://fewcompany.com" external>Site da Few Company</a>
    </div>
  `,
})
export class DemoLink {}

export const ACTIONS_DEMOS: Record<string, Type<unknown>> = {
  button: DemoButton,
  'icon-button': DemoIconButton,
  'button-group': DemoButtonGroup,
  toggle: DemoToggle,
  'toggle-group': DemoToggleGroup,
  'split-button': DemoSplitButton,
  link: DemoLink,
};
