// packages/react/src/registry/overlays.ts
import { component, type ComponentRecord } from './shared.js';
// Registro da categoria "Overlays" (pasta components/overlays). Um component() por componente, na ordem do menu.
export const overlaysRegistry: ComponentRecord[] = [
  component({
    id: 'dialog', name: 'Dialog', category: 'Overlays',
    description: 'Janela modal sobre <dialog> nativo: foco preso, Escape fecha, foco volta ao gatilho.',
    variants: ['sm', 'md', 'lg', 'full'],
    parts: ['Root', 'Trigger', 'Content', 'Title', 'Description', 'Close'],
    origins: ['Caraminholas · StageDialog'],
    references: ['Radix Dialog', 'MUI Dialog'],
    code: '<Dialog><Dialog.Trigger asChild><Button>Abrir</Button></Dialog.Trigger><Dialog.Content size="md"><Dialog.Title>Título</Dialog.Title><Dialog.Description>Descrição.</Dialog.Description><Dialog.Close asChild><Button variant="ghost">Fechar</Button></Dialog.Close></Dialog.Content></Dialog>',
    vueCode: `<FewDialog>
  <FewDialogTrigger as-child><FewButton>Abrir</FewButton></FewDialogTrigger>
  <FewDialogContent size="md">
    <FewDialogTitle>Título</FewDialogTitle>
    <FewDialogDescription>Descrição.</FewDialogDescription>
    <FewDialogClose as-child><FewButton variant="ghost">Fechar</FewButton></FewDialogClose>
  </FewDialogContent>
</FewDialog>`,
  }),
  component({
    id: 'alert-dialog', name: 'AlertDialog', category: 'Overlays',
    description: 'Confirmação que interrompe o fluxo: só fecha por Cancel, Action ou Escape (nunca clique fora).',
    variants: ['confirmação', 'ação destrutiva'],
    parts: ['Root', 'Trigger', 'Content', 'Title', 'Description', 'Cancel', 'Action'],
    origins: ['Few · novo padrão'],
    references: ['Radix AlertDialog', 'PrimeReact ConfirmDialog'],
    code: '<AlertDialog><AlertDialog.Trigger asChild><Button variant="danger">Excluir</Button></AlertDialog.Trigger><AlertDialog.Content><AlertDialog.Title>Excluir item?</AlertDialog.Title><AlertDialog.Description>Não pode ser desfeito.</AlertDialog.Description><AlertDialog.Cancel asChild><Button variant="secondary">Cancelar</Button></AlertDialog.Cancel><AlertDialog.Action asChild><Button variant="danger">Excluir</Button></AlertDialog.Action></AlertDialog.Content></AlertDialog>',
    vueCode: `<FewAlertDialog>
  <FewAlertDialogTrigger as-child><FewButton variant="danger">Excluir</FewButton></FewAlertDialogTrigger>
  <FewAlertDialogContent>
    <FewAlertDialogTitle>Excluir item?</FewAlertDialogTitle>
    <FewAlertDialogDescription>Não pode ser desfeito.</FewAlertDialogDescription>
    <FewAlertDialogCancel as-child><FewButton variant="secondary">Cancelar</FewButton></FewAlertDialogCancel>
    <FewAlertDialogAction as-child><FewButton variant="danger">Excluir</FewButton></FewAlertDialogAction>
  </FewAlertDialogContent>
</FewAlertDialog>`,
  }),
  component({
    id: 'drawer', name: 'Drawer', category: 'Overlays',
    description: 'Painel modal que desliza de uma borda da tela (<dialog> nativo), com Handle opcional embaixo.',
    variants: ['left', 'right', 'top', 'bottom'],
    parts: ['Root', 'Trigger', 'Content', 'Title', 'Description', 'Close', 'Handle'],
    origins: ['Few · novo padrão'],
    references: ['Vaul', 'MUI Drawer'],
    code: '<Drawer side="right"><Drawer.Trigger asChild><Button>Filtros</Button></Drawer.Trigger><Drawer.Content><Drawer.Title>Filtros</Drawer.Title><Drawer.Close asChild><Button variant="ghost">Fechar</Button></Drawer.Close></Drawer.Content></Drawer>',
    vueCode: `<FewDrawer side="right">
  <FewDrawerTrigger as-child><FewButton>Filtros</FewButton></FewDrawerTrigger>
  <FewDrawerContent>
    <FewDrawerTitle>Filtros</FewDrawerTitle>
    <FewDrawerClose as-child><FewButton variant="ghost">Fechar</FewButton></FewDrawerClose>
  </FewDrawerContent>
</FewDrawer>`,
  }),
  component({
    id: 'popover', name: 'Popover', category: 'Overlays',
    description: 'Camada não modal ancorada a um gatilho: popover="manual" + posicionamento automático, sem Portal.',
    variants: ['top', 'bottom', 'left', 'right'],
    parts: ['Root', 'Anchor', 'Trigger', 'Content', 'Close', 'Arrow'],
    origins: ['iFIGHT · painel de ações rápidas'],
    references: ['Radix Popover', 'PrimeReact OverlayPanel'],
    code: '<Popover><Popover.Trigger asChild><Button variant="secondary">Ajustes</Button></Popover.Trigger><Popover.Content side="bottom" align="start"><Popover.Arrow />Conteúdo</Popover.Content></Popover>',
    vueCode: `<FewPopover>
  <FewPopoverTrigger as-child><FewButton variant="secondary">Ajustes</FewButton></FewPopoverTrigger>
  <FewPopoverContent side="bottom" align="start">
    <FewPopoverArrow />Conteúdo
  </FewPopoverContent>
</FewPopover>`,
  }),
  component({
    id: 'tooltip', name: 'Tooltip', category: 'Overlays',
    description: 'Dica textual no hover/foco, com delay compartilhado entre vários tooltips via Provider.',
    variants: ['top', 'bottom', 'left', 'right'],
    parts: ['Provider', 'Root', 'Trigger', 'Content', 'Arrow'],
    origins: ['Few · novo padrão'],
    references: ['Radix Tooltip', 'MUI Tooltip'],
    code: '<Tooltip.Provider><Tooltip><Tooltip.Trigger asChild><Button variant="ghost">?</Button></Tooltip.Trigger><Tooltip.Content>Ajuda<Tooltip.Arrow /></Tooltip.Content></Tooltip></Tooltip.Provider>',
    vueCode: `<FewTooltipProvider>
  <FewTooltip>
    <FewTooltipTrigger as-child><FewButton variant="ghost">?</FewButton></FewTooltipTrigger>
    <FewTooltipContent>Ajuda<FewTooltipArrow /></FewTooltipContent>
  </FewTooltip>
</FewTooltipProvider>`,
  }),
  component({
    id: 'dropdown-menu', name: 'DropdownMenu', category: 'Overlays',
    description: 'Menu acionado por botão: itens, checkbox, radio, atalhos e grupos, com roving focus e typeahead.',
    variants: ['itens', 'checkbox', 'radio', 'com grupos'],
    parts: ['Root', 'Trigger', 'Content', 'Item', 'CheckboxItem', 'RadioGroup', 'RadioItem', 'ItemIndicator', 'Label', 'Group', 'Separator', 'Shortcut'],
    origins: ['iFIGHT · ações da linha da tabela'],
    references: ['Radix DropdownMenu', 'MUI Menu'],
    code: '<DropdownMenu><DropdownMenu.Trigger asChild><Button variant="secondary">Ações</Button></DropdownMenu.Trigger><DropdownMenu.Content><DropdownMenu.Item>Editar</DropdownMenu.Item><DropdownMenu.Separator /><DropdownMenu.Item disabled>Excluir</DropdownMenu.Item></DropdownMenu.Content></DropdownMenu>',
    vueCode: `<FewDropdownMenu>
  <FewDropdownMenuTrigger as-child><FewButton variant="secondary">Ações</FewButton></FewDropdownMenuTrigger>
  <FewDropdownMenuContent>
    <FewDropdownMenuItem>Editar</FewDropdownMenuItem>
    <FewDropdownMenuSeparator />
    <FewDropdownMenuItem disabled>Excluir</FewDropdownMenuItem>
  </FewDropdownMenuContent>
</FewDropdownMenu>`,
  }),
  component({
    id: 'context-menu', name: 'ContextMenu', category: 'Overlays',
    description: 'Menu na posição do ponteiro (clique direito ou toque longo); reusa o núcleo do DropdownMenu.',
    variants: ['clique direito', 'toque longo'],
    parts: ['Root', 'Trigger', 'Content', 'Item', 'CheckboxItem', 'RadioGroup', 'RadioItem', 'ItemIndicator', 'Label', 'Group', 'Separator', 'Shortcut'],
    origins: ['Few · novo padrão'],
    references: ['Radix ContextMenu'],
    code: '<ContextMenu><ContextMenu.Trigger><div className="demo-surface">Clique com o botão direito</div></ContextMenu.Trigger><ContextMenu.Content><ContextMenu.Item>Copiar</ContextMenu.Item><ContextMenu.Item>Colar</ContextMenu.Item></ContextMenu.Content></ContextMenu>',
    vueCode: `<FewContextMenu>
  <FewContextMenuTrigger>
    <div class="demo-surface">Clique com o botão direito</div>
  </FewContextMenuTrigger>
  <FewContextMenuContent>
    <FewContextMenuItem>Copiar</FewContextMenuItem>
    <FewContextMenuItem>Colar</FewContextMenuItem>
  </FewContextMenuContent>
</FewContextMenu>`,
  }),
  component({
    id: 'menubar', name: 'Menubar', category: 'Overlays',
    description: 'Barra horizontal de menus (Arquivo, Editar…): roving focus, troca por seta e por hover.',
    variants: ['horizontal'],
    parts: ['Root', 'Menu', 'Trigger', 'Content', 'Item', 'CheckboxItem', 'RadioGroup', 'RadioItem', 'ItemIndicator', 'Label', 'Group', 'Separator', 'Shortcut'],
    origins: ['Few · novo padrão'],
    references: ['Radix Menubar', 'PrimeReact Menubar'],
    code: '<Menubar><Menubar.Menu value="file"><Menubar.Trigger>Arquivo</Menubar.Trigger><Menubar.Content><Menubar.Item>Novo</Menubar.Item></Menubar.Content></Menubar.Menu></Menubar>',
    vueCode: `<FewMenubar>
  <FewMenubarMenu value="file">
    <FewMenubarTrigger>Arquivo</FewMenubarTrigger>
    <FewMenubarContent>
      <FewMenubarItem>Novo</FewMenubarItem>
    </FewMenubarContent>
  </FewMenubarMenu>
</FewMenubar>`,
  }),
  component({
    id: 'toast', name: 'Toast', category: 'Overlays',
    description: 'Notificação efêmera em fila: hook useToast() imperativo, pausa no hover/foco, aria-live.',
    variants: ['neutral', 'success', 'warning', 'danger', 'info'],
    parts: ['Provider', 'Viewport', 'Root', 'Title', 'Description', 'Action', 'Close'],
    origins: ['iFIGHT · notificações de partida'],
    references: ['Radix Toast', 'Sonner'],
    code: 'const { toast } = useToast(); <Toast.Provider><Toast.Viewport /></Toast.Provider>; toast({ title: "Salvo", tone: "success" });',
    vueCode: `<!-- const { toast } = useToast() -->
<FewToastProvider>
  <FewToastViewport />
</FewToastProvider>
<!-- toast({ title: "Salvo", tone: "success" }) -->`,
  }),
];

// packages/angular/src/demos/overlays.ts
// Hosts de demonstração/teste da categoria "Overlays" (pasta components/overlays). Um @Component por id do
// registry, selector few-demo-<id>.
import { Component, inject, type Type } from '@angular/core';
import { FewButton } from '../components/actions/button.js';
import { FEW_DIALOG } from '../components/overlays/dialog.js';
import { FEW_ALERT_DIALOG } from '../components/overlays/alert-dialog.js';
import { FEW_DRAWER } from '../components/overlays/drawer.js';
import { FEW_POPOVER } from '../components/overlays/popover.js';
import { FEW_TOOLTIP } from '../components/overlays/tooltip.js';
import { FEW_DROPDOWN_MENU } from '../components/overlays/dropdown-menu.js';
import { FEW_CONTEXT_MENU } from '../components/overlays/context-menu.js';
import { FEW_MENUBAR } from '../components/overlays/menubar.js';
import { FEW_MENU_PARTS } from '../components/overlays/menu-core.js';
import { FEW_TOAST, FewToastService } from '../components/overlays/toast.js';

@Component({
  selector: 'few-demo-dialog',
  imports: [FewButton, FEW_DIALOG],
  template: `
    <div fewDialog>
      <button fewDialogTrigger fewButton>Editar perfil</button>
      <dialog fewDialogContent>
        <h2 fewDialogTitle>Editar perfil</h2>
        <p fewDialogDescription>Atualize seus dados. As mudanças são salvas automaticamente.</p>
        <button fewDialogClose fewButton>Fechar</button>
      </dialog>
    </div>
  `,
})
export class DemoDialog {}

@Component({
  selector: 'few-demo-alert-dialog',
  imports: [FewButton, FEW_ALERT_DIALOG],
  template: `
    <div fewAlertDialog>
      <button fewAlertDialogTrigger fewButton>Excluir conta</button>
      <dialog fewAlertDialogContent>
        <h2 fewAlertDialogTitle>Tem certeza?</h2>
        <p fewAlertDialogDescription>Essa ação não pode ser desfeita.</p>
        <button fewAlertDialogCancel fewButton>Cancelar</button>
        <button fewAlertDialogAction fewButton>Excluir</button>
      </dialog>
    </div>
  `,
})
export class DemoAlertDialog {}

@Component({
  selector: 'few-demo-drawer',
  imports: [FewButton, FEW_DRAWER],
  template: `
    <div fewDrawer side="right">
      <button fewDrawerTrigger fewButton>Abrir menu</button>
      <dialog fewDrawerContent>
        <div fewDrawerHandle></div>
        <h2 fewDrawerTitle>Navegação</h2>
        <p fewDrawerDescription>Acesse as seções do painel.</p>
        <button fewDrawerClose fewButton>Fechar</button>
      </dialog>
    </div>
  `,
})
export class DemoDrawer {}

@Component({
  selector: 'few-demo-popover',
  imports: [FewButton, FEW_POPOVER],
  template: `
    <div fewPopover>
      <button fewPopoverTrigger fewButton>Mais informações</button>
      <div fewPopoverContent>
        <span fewPopoverArrow></span>
        <p class="few-muted">Conteúdo adicional sobre este item.</p>
        <button fewPopoverClose fewButton>Fechar</button>
      </div>
    </div>
  `,
})
export class DemoPopover {}

@Component({
  selector: 'few-demo-tooltip',
  imports: [FewButton, FEW_TOOLTIP],
  template: `
    <div fewTooltipProvider>
      <div fewTooltip>
        <button fewTooltipTrigger fewButton>Ajuda</button>
        <div fewTooltipContent>
          <span fewTooltipArrow></span>
          Mostra informações extras.
        </div>
      </div>
    </div>
  `,
})
export class DemoTooltip {}

@Component({
  selector: 'few-demo-dropdown-menu',
  imports: [FewButton, FEW_DROPDOWN_MENU],
  template: `
    <div fewDropdownMenu>
      <button fewDropdownMenuTrigger fewButton>Opções</button>
      <div fewDropdownMenuContent>
        <div fewMenuLabel>Conta</div>
        <div fewMenuItem>Perfil</div>
        <div fewMenuItem>Configurações</div>
        <div fewMenuSeparator></div>
        <div fewMenuCheckboxItem [checked]="true">
          <span fewMenuItemIndicator>✓</span>
          Notificações
        </div>
        <div fewMenuRadioGroup value="claro">
          <div fewMenuRadioItem value="claro">
            <span fewMenuItemIndicator>•</span>
            Tema claro
          </div>
          <div fewMenuRadioItem value="escuro">
            <span fewMenuItemIndicator>•</span>
            Tema escuro
          </div>
        </div>
        <div fewMenuItem>
          Sair
          <kbd fewMenuShortcut>Ctrl+Q</kbd>
        </div>
      </div>
    </div>
  `,
})
export class DemoDropdownMenu {}

@Component({
  selector: 'few-demo-context-menu',
  imports: [FewButton, FEW_CONTEXT_MENU, FEW_MENU_PARTS],
  template: `
    <div fewContextMenu>
      <div fewContextMenuTrigger class="few-muted" style="border:1px dashed currentColor;padding:2rem;text-align:center;">
        Clique com o botão direito aqui
      </div>
      <div fewContextMenuContent>
        <div fewMenuItem>Copiar</div>
        <div fewMenuItem>Colar</div>
        <div fewMenuSeparator></div>
        <div fewMenuItem>Excluir</div>
      </div>
    </div>
  `,
})
export class DemoContextMenu {}

@Component({
  selector: 'few-demo-menubar',
  imports: [FewButton, FEW_MENUBAR, FEW_MENU_PARTS],
  template: `
    <div fewMenubar>
      <div fewMenubarMenu value="arquivo">
        <button fewMenubarTrigger>Arquivo</button>
        <div fewMenubarContent>
          <div fewMenuItem>Novo</div>
          <div fewMenuItem>Abrir</div>
        </div>
      </div>
      <div fewMenubarMenu value="editar">
        <button fewMenubarTrigger>Editar</button>
        <div fewMenubarContent>
          <div fewMenuItem>Copiar</div>
          <div fewMenuItem>Colar</div>
        </div>
      </div>
    </div>
  `,
})
export class DemoMenubar {}

@Component({
  selector: 'few-demo-toast',
  imports: [FewButton, FEW_TOAST],
  template: `
    <div>
      <button fewButton (click)="notify()">Notificar</button>
      <div fewToastViewport position="bottom-right"></div>
    </div>
  `,
})
export class DemoToast {
  private readonly toastService = inject(FewToastService);
  protected notify(): void {
    this.toastService.toast({ title: 'Salvo', description: 'Suas alterações foram salvas.', tone: 'success' });
  }
}

export const OVERLAYS_DEMOS: Record<string, Type<unknown>> = {
  dialog: DemoDialog,
  'alert-dialog': DemoAlertDialog,
  drawer: DemoDrawer,
  popover: DemoPopover,
  tooltip: DemoTooltip,
  'dropdown-menu': DemoDropdownMenu,
  'context-menu': DemoContextMenu,
  menubar: DemoMenubar,
  toast: DemoToast,
};
