// packages/angular/src/components/typography/code.ts
// Ver docs/composition-angular.md. Fonte da verdade: packages/react/src/components/typography/code.tsx.
import { Component, Directive, ElementRef, booleanAttribute, input, signal, viewChild } from '@angular/core';

export type CodeVariant = 'soft' | 'outline';

/** Código inline: aplique em `<code fewCode>` do consumidor. Sem efeito de bloco — use `FewCodeBlock` para isso. */
@Directive({
  selector: 'code[fewCode]',
  host: {
    class: 'few-code',
    '[attr.data-variant]': 'variant()',
    '[attr.data-lang]': 'lang()',
  },
})
export class FewCode {
  readonly variant = input<CodeVariant>('soft');
  /** Linguagem do trecho, exposta só como data-lang (sem syntax highlight). */
  readonly lang = input<string>();
}

/**
 * Código em bloco: `<pre fewCodeBlock>...</pre>`, rolagem horizontal e por teclado (tabindex 0), cópia opcional.
 * Sem `document`, o botão de copiar não é renderizado (guard) e `copy()` não é chamado fora de handler de usuário.
 */
@Component({
  selector: 'pre[fewCodeBlock]',
  host: {
    class: 'few-code',
    'data-block': '',
    tabindex: '0',
    '[attr.data-lang]': 'lang()',
  },
  template: `
    <code class="few-code-code" #codeEl><ng-content /></code>
    @if (copyable()) {
      <button type="button" class="few-code-copy" (click)="copy()" aria-label="Copiar código">{{ copied() ? 'Copiado' : 'Copiar' }}</button>
      <span role="status" aria-live="polite" class="few-sr-only">{{ copied() ? 'Copiado' : '' }}</span>
    }
  `,
})
export class FewCodeBlock {
  readonly lang = input<string>();
  /** Mostra um botão de copiar. */
  readonly copyable = input(false, { transform: booleanAttribute });
  protected readonly copied = signal(false);
  private readonly codeEl = viewChild<ElementRef<HTMLElement>>('codeEl');
  private resetTimer: ReturnType<typeof setTimeout> | undefined;

  protected async copy() {
    const text = this.codeEl()?.nativeElement.textContent ?? '';
    try {
      await navigator.clipboard.writeText(text);
      this.copied.set(true);
      clearTimeout(this.resetTimer);
      this.resetTimer = setTimeout(() => this.copied.set(false), 2000);
    } catch {
      /* clipboard indisponível (permissão/contexto não seguro); botão fica sem feedback de sucesso */
    }
  }
}

export const FEW_CODE = [FewCode, FewCodeBlock] as const;

// packages/react/src/components/typography/code.tsx
"use client";
import { useRef, useState, type ComponentProps } from 'react';
import { Slot, Slottable } from '../../lib/slot.js';
import { cx } from '../../lib/cx.js';

export type CodeVariant = 'soft' | 'outline';

export interface CodeProps extends Omit<ComponentProps<'code'>, 'color' | 'ref'> {
  asChild?: boolean;
  /** Estilo do código inline. Sem efeito quando `block` está ativo. */
  variant?: CodeVariant;
  /** Renderiza um bloco (pre>code) com rolagem horizontal, em vez de código inline. */
  block?: boolean;
  /** Linguagem do trecho, exposta só como data-lang (sem syntax highlight). */
  lang?: string;
  /** Mostra um botão de copiar. Só tem efeito com `block`. */
  copyable?: boolean;
}

/** Code: código inline (`code`) ou em bloco (`pre>code`, rolagem por teclado, cópia opcional). */
function Code({ asChild, variant = 'soft', block, lang, copyable, className, children, ...props }: CodeProps) {
  const codeRef = useRef<HTMLElement>(null);
  const [copied, setCopied] = useState(false);

  if (!block) {
    const Comp = asChild ? Slot : 'code';
    return <Comp {...props} className={cx('few-code', className)} data-variant={variant} data-lang={lang}>{children}</Comp>;
  }

  const Comp = asChild ? Slot : 'pre';

  async function handleCopy() {
    const text = codeRef.current?.textContent ?? (typeof children === 'string' ? children : '');
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      /* clipboard indisponível (permissão/contexto não seguro); botão fica sem feedback de sucesso */
    }
  }

  return (
    <Comp {...props} tabIndex={0} className={cx('few-code', className)} data-block="" data-lang={lang}>
      {asChild
        ? <Slottable>{children}</Slottable>
        : <code ref={codeRef} className="few-code-code">{children}</code>}
      {copyable && <button type="button" className="few-code-copy" onClick={handleCopy} aria-label="Copiar código">{copied ? 'Copiado' : 'Copiar'}</button>}
      {copyable && <span role="status" aria-live="polite" className="few-sr-only">{copied ? 'Copiado' : ''}</span>}
    </Comp>
  );
}

export { Code };
