// packages/react/src/components/layout/grid.tsx
"use client";
// Grid: ver docs/composition.md. grid-template-columns/span resolvidos pelo headless (@fewcompany/core).
import type { ComponentProps, CSSProperties } from 'react';
import { resolveGap, resolveGridColumns, resolveGridSpan, type Gap, type GridColumns } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { cx } from '../../lib/cx.js';

export interface GridProps extends ComponentProps<'div'> {
  asChild?: boolean;
  /** Número de colunas iguais, ou 'auto' (usa `minChildWidth` com minmax/auto-fit). Padrão 'auto'. */
  columns?: GridColumns;
  minChildWidth?: string;
  gap?: Gap;
  rowGap?: Gap;
  align?: CSSProperties['alignItems'];
}
function GridRoot({ asChild, columns = 'auto', minChildWidth = '200px', gap, rowGap, align, style, className, ...props }: GridProps) {
  const Comp = asChild ? Slot : 'div';
  return (
    <Comp
      {...props}
      className={cx('few-grid', className)}
      style={{
        gridTemplateColumns: resolveGridColumns(columns, minChildWidth),
        gap: resolveGap(gap, '0px'),
        rowGap: rowGap !== undefined ? resolveGap(rowGap) : undefined,
        alignItems: align,
        ...style,
      }}
    />
  );
}

export interface GridItemProps extends ComponentProps<'div'> { asChild?: boolean; colSpan?: number; rowSpan?: number }
function GridItem({ asChild, colSpan, rowSpan, style, className, ...props }: GridItemProps) {
  const Comp = asChild ? Slot : 'div';
  return (
    <Comp
      {...props}
      className={cx('few-grid-item', className)}
      style={{ gridColumn: resolveGridSpan(colSpan), gridRow: resolveGridSpan(rowSpan), ...style }}
    />
  );
}

/** Grid composto: <Grid columns="auto" minChildWidth="220px" gap={4}><Grid.Item colSpan={2}>…</Grid.Item></Grid> */
export const Grid = Object.assign(GridRoot, { Root: GridRoot, Item: GridItem });
export { GridRoot, GridItem };

// packages/angular/src/components/layout/grid.ts
// Grid: ver docs/composition-angular.md. Espelha packages/react/src/components/layout/grid.tsx:
// grid-template-columns/span resolvidos pelo headless (@fewcompany/core).
import { Directive, computed, input } from '@angular/core';
import { resolveGap, resolveGridColumns, resolveGridSpan, type Gap, type GridColumns } from '@fewcompany/core';

@Directive({
  selector: '[fewGrid]',
  exportAs: 'fewGrid',
  host: {
    class: 'few-grid',
    '[style.grid-template-columns]': 'gridTemplateColumns()',
    '[style.gap]': 'gapValue()',
    '[style.row-gap]': 'rowGapValue()',
    '[style.align-items]': 'align()',
  },
})
export class FewGrid {
  /** Número de colunas iguais, ou 'auto' (usa `minChildWidth` com minmax/auto-fit). Padrão 'auto'. */
  readonly columns = input<GridColumns>('auto');
  readonly minChildWidth = input<string>('200px');
  readonly gap = input<Gap | undefined>(undefined);
  readonly rowGap = input<Gap | undefined>(undefined);
  readonly align = input<string | undefined>(undefined);

  protected readonly gridTemplateColumns = computed(() => resolveGridColumns(this.columns(), this.minChildWidth()));
  protected readonly gapValue = computed(() => resolveGap(this.gap(), '0px'));
  protected readonly rowGapValue = computed(() => (this.rowGap() !== undefined ? resolveGap(this.rowGap()) : undefined));
}

@Directive({
  selector: '[fewGridItem]',
  host: {
    class: 'few-grid-item',
    '[style.grid-column]': 'colSpanValue()',
    '[style.grid-row]': 'rowSpanValue()',
  },
})
export class FewGridItem {
  readonly colSpan = input<number | undefined>(undefined);
  readonly rowSpan = input<number | undefined>(undefined);
  protected readonly colSpanValue = computed(() => resolveGridSpan(this.colSpan()));
  protected readonly rowSpanValue = computed(() => resolveGridSpan(this.rowSpan()));
}

/** Importe tudo de uma vez: `imports: [FEW_GRID]`. */
export const FEW_GRID = [FewGrid, FewGridItem] as const;
