// packages/angular/src/components/actions/button.ts
// Botão simples (sem partes). Fonte da verdade: packages/react/src/components/actions/button.tsx.
import { Component, ElementRef, booleanAttribute, computed, inject, input } from '@angular/core';
import type { Size } from '@fewcompany/core';
import { dataAttr } from '../../lib/attrs.js';
import { FewButtonGroup } from './button-group.js';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'link';

/**
 * `<button fewButton variant="primary">Salvar</button>` ou `<a fewButton href="/">Ir</a>`.
 * `loading` mostra spinner, marca aria-busy e desabilita. Size/variant caem para o ButtonGroup ancestral quando não definidos.
 */
@Component({
  selector: 'button[fewButton], a[fewButton]',
  host: {
    class: 'few-button',
    '[class]': 'variantClasses()',
    '[attr.type]': 'typeAttr',
    '[attr.disabled]': 'isDisabled() ? "" : null',
    '[attr.aria-busy]': 'loading() ? "true" : null',
    '[attr.data-loading]': 'dataAttr(loading())',
  },
  template: `@if (loading()) {<span class="few-spinner" aria-hidden="true"></span>}<ng-content></ng-content>`,
})
export class FewButton {
  private readonly hostEl = inject<ElementRef<HTMLElement>>(ElementRef);
  private readonly group = inject(FewButtonGroup, { optional: true });

  readonly variant = input<ButtonVariant>();
  readonly size = input<Size>();
  readonly type = input<'button' | 'submit' | 'reset'>('button');
  readonly loading = input(false, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });

  protected readonly resolvedVariant = computed(() => this.variant() ?? this.group?.variant() ?? 'primary');
  protected readonly resolvedSize = computed(() => this.size() ?? this.group?.size() ?? 'md');
  protected readonly isDisabled = computed(() => this.disabled() || this.loading());
  protected readonly variantClasses = computed(() => `few-button--${this.resolvedVariant()} few-button--${this.resolvedSize()}`);
  protected readonly dataAttr = dataAttr;

  protected get typeAttr(): string | null { return this.hostEl.nativeElement.tagName === 'A' ? null : this.type(); }
}

// packages/react/src/components/actions/button.tsx
"use client";
import type { ComponentProps } from 'react';
import type { Size } from '@fewcompany/core';
import { Slot, Slottable } from '../../lib/slot.js';
import { cx, dataAttr } from '../../lib/cx.js';
import { useButtonGroupOptionalContext } from './button-group.js';

export type ButtonVariant = 'primary' | 'secondary' | 'ghost' | 'danger' | 'link';

export interface ButtonProps extends ComponentProps<'button'> {
  asChild?: boolean;
  variant?: ButtonVariant;
  size?: Size;
  /** Mostra spinner, marca aria-busy e desabilita o botão. Com asChild, o spinner envolve `children` no elemento filho. */
  loading?: boolean;
}

/** Botão simples (sem partes). `<Button variant="primary">Salvar</Button>` ou `<Button asChild><Link href="/">Ir</Link></Button>`. */
export function Button({ asChild, variant, size, loading = false, disabled, className, type = 'button', children, ...props }: ButtonProps) {
  const group = useButtonGroupOptionalContext();
  const resolvedVariant = variant ?? group?.variant ?? 'primary';
  const resolvedSize = size ?? group?.size ?? 'md';
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp
      {...props}
      type={type}
      disabled={disabled || loading}
      aria-busy={loading || undefined}
      data-loading={dataAttr(loading)}
      className={cx('few-button', `few-button--${resolvedVariant}`, `few-button--${resolvedSize}`, className)}
    >
      {loading && <span className="few-spinner" aria-hidden="true" />}
      <Slottable>{children}</Slottable>
    </Comp>
  );
}
