// packages/react/src/components/pickers/calendar.tsx
"use client";
// Calendar: grade de dias (role=grid) com roving tabindex (Calendar.Day) e navegação completa por teclado.
// Toda a matemática de datas vem do core (calendarGrid, isSameDay, addDays/Months/Years, isInRange,
// isDateDisabled); aqui só ligamos estado a DOM e usamos Intl para nomes de mês/dia (Intl fica no React).
// GridHead/GridBody renderizam sozinhos por padrão (usando o core), mas aceitam children para composição manual.
// Ver docs/composition.md.
import { useCallback, useEffect, useId, useRef, useState, type ComponentProps, type KeyboardEvent, type MutableRefObject } from 'react';
import { addDays, addMonths, addYears, calendarGrid, isDateDisabled, isInRange, isSameDay, startOfMonth, type DateRange } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';

export type CalendarMode = 'single' | 'range' | 'multiple';
export type CalendarValue = Date | Date[] | DateRange;

interface CalendarContextValue {
  baseId: string;
  mode: CalendarMode;
  value: CalendarValue | undefined;
  selectDate: (date: Date) => void;
  month: Date; setMonth: (month: Date) => void;
  focusedDate: Date; setFocusedDate: (date: Date) => void;
  focusRef: MutableRefObject<boolean>;
  min?: Date; max?: Date; disabledDates?: (date: Date) => boolean;
  weekStartsOn: number; locale: string;
}
const [CalendarProvider, useCalendar] = createContext<CalendarContextValue>('Calendar');

const capitalize = (text: string) => text.length ? text.charAt(0).toUpperCase() + text.slice(1) : text;

function isDateSelected(mode: CalendarMode, value: CalendarValue | undefined, date: Date): boolean {
  if (!value) return false;
  if (mode === 'multiple') return Array.isArray(value) && value.some(d => isSameDay(d, date));
  if (mode === 'range') { const range = value as DateRange; return Boolean((range.from && isSameDay(range.from, date)) || (range.to && isSameDay(range.to, date))); }
  return value instanceof Date && isSameDay(value, date);
}

function initialFocusFromValue(mode: CalendarMode, value: CalendarValue | undefined): Date {
  if (mode === 'multiple' && Array.isArray(value) && value[0]) return value[0];
  if (mode === 'range' && value && !Array.isArray(value) && (value as DateRange).from) return (value as DateRange).from as Date;
  if (mode === 'single' && value instanceof Date) return value;
  return new Date();
}

export interface CalendarProps extends Omit<ComponentProps<'div'>, 'defaultValue' | 'onChange'> {
  asChild?: boolean;
  mode?: CalendarMode;
  value?: CalendarValue; defaultValue?: CalendarValue; onValueChange?: (value: CalendarValue) => void;
  min?: Date; max?: Date; disabledDates?: (date: Date) => boolean;
  /** 0 = domingo … 6 = sábado. */
  weekStartsOn?: number;
  /** Locale do Intl para nomes de mês/semana (o headless não usa Intl). */
  locale?: string;
  month?: Date; defaultMonth?: Date; onMonthChange?: (month: Date) => void;
}
function CalendarRoot({ asChild, mode = 'single', value: valueProp, defaultValue, onValueChange, min, max, disabledDates, weekStartsOn = 0, locale = 'pt-BR', month: monthProp, defaultMonth, onMonthChange, className, children, ...props }: CalendarProps) {
  const baseId = useId();
  const defaultForMode: CalendarValue | undefined = mode === 'multiple' ? [] : mode === 'range' ? {} : undefined;
  const [value, setValue] = useControllableState<CalendarValue | undefined>({ value: valueProp, defaultValue: defaultValue ?? defaultForMode, onChange: onValueChange as (value: CalendarValue | undefined) => void });
  const [month, setMonth] = useControllableState<Date>({ value: monthProp, defaultValue: startOfMonth(defaultMonth ?? initialFocusFromValue(mode, value)), onChange: onMonthChange });
  const [focusedDate, setFocusedDate] = useState<Date>(() => initialFocusFromValue(mode, value));
  const focusRef = useRef(false);
  const selectDate = useCallback((date: Date) => {
    if (isDateDisabled(date, { min, max, disabledDates })) return;
    if (mode === 'multiple') {
      const arr = Array.isArray(value) ? value : [];
      setValue(arr.some(d => isSameDay(d, date)) ? arr.filter(d => !isSameDay(d, date)) : [...arr, date]);
    } else if (mode === 'range') {
      const range = (value && !Array.isArray(value)) ? value as DateRange : {};
      if (!range.from || range.to) setValue({ from: date, to: undefined });
      else setValue(date.getTime() < range.from.getTime() ? { from: date, to: range.from } : { from: range.from, to: date });
    } else {
      setValue(date);
    }
  }, [mode, value, setValue, min, max, disabledDates]);
  const Comp = asChild ? Slot : 'div';
  return (
    <CalendarProvider value={{ baseId, mode, value, selectDate, month, setMonth, focusedDate, setFocusedDate, focusRef, min, max, disabledDates, weekStartsOn, locale }}>
      <Comp {...props} role="group" aria-label="Calendário" className={cx('few-calendar', className)}>{children}</Comp>
    </CalendarProvider>
  );
}

export interface CalendarHeaderProps extends ComponentProps<'div'> { asChild?: boolean }
function CalendarHeader({ asChild, className, ...props }: CalendarHeaderProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} className={cx('few-calendar-header', className)} />;
}

export interface CalendarNavButtonProps extends ComponentProps<'button'> { asChild?: boolean }
function CalendarPrevButton({ asChild, className, onClick, children, 'aria-label': ariaLabel, ...props }: CalendarNavButtonProps) {
  const ctx = useCalendar('Calendar.PrevButton');
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp {...props} type="button" aria-label={ariaLabel ?? 'Mês anterior'} className={cx('few-calendar-nav', className)}
      onClick={(event) => { onClick?.(event); if (event.defaultPrevented) return; ctx.setMonth(addMonths(ctx.month, -1)); }}>
      {children ?? '‹'}
    </Comp>
  );
}
function CalendarNextButton({ asChild, className, onClick, children, 'aria-label': ariaLabel, ...props }: CalendarNavButtonProps) {
  const ctx = useCalendar('Calendar.NextButton');
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp {...props} type="button" aria-label={ariaLabel ?? 'Próximo mês'} className={cx('few-calendar-nav', className)}
      onClick={(event) => { onClick?.(event); if (event.defaultPrevented) return; ctx.setMonth(addMonths(ctx.month, 1)); }}>
      {children ?? '›'}
    </Comp>
  );
}

export interface CalendarHeadingProps extends ComponentProps<'div'> { asChild?: boolean }
function CalendarHeading({ asChild, className, children, ...props }: CalendarHeadingProps) {
  const ctx = useCalendar('Calendar.Heading');
  const Comp = asChild ? Slot : 'div';
  if (asChild || children !== undefined) return <Comp {...props} id={`${ctx.baseId}-heading`} className={cx('few-calendar-heading', className)}>{children}</Comp>;
  const label = capitalize(new Intl.DateTimeFormat(ctx.locale, { month: 'long', year: 'numeric' }).format(ctx.month));
  return <div {...props} id={`${ctx.baseId}-heading`} aria-live="polite" className={cx('few-calendar-heading', className)}>{label}</div>;
}

export interface CalendarGridProps extends ComponentProps<'table'> { asChild?: boolean }
function CalendarGrid({ asChild, className, ...props }: CalendarGridProps) {
  const ctx = useCalendar('Calendar.Grid');
  const Comp = asChild ? Slot : 'table';
  return <Comp {...props} role="grid" aria-labelledby={`${ctx.baseId}-heading`} className={cx('few-calendar-grid', className)} />;
}

export interface CalendarGridHeadProps extends ComponentProps<'thead'> { asChild?: boolean }
function CalendarGridHead({ asChild, className, children, ...props }: CalendarGridHeadProps) {
  const ctx = useCalendar('Calendar.GridHead');
  const Comp = asChild ? Slot : 'thead';
  if (children !== undefined) return <Comp {...props} className={cx('few-calendar-grid-head', className)}>{children}</Comp>;
  const formatter = new Intl.DateTimeFormat(ctx.locale, { weekday: 'short' });
  const referenceSunday = new Date(2024, 0, 7);
  const labels = Array.from({ length: 7 }, (_, i) => capitalize(formatter.format(addDays(referenceSunday, (i + ctx.weekStartsOn) % 7)).replace('.', '')));
  return (
    <Comp {...props} className={cx('few-calendar-grid-head', className)}>
      <CalendarRow>{labels.map((label, i) => <CalendarHeadCell key={`${label}-${i}`}>{label}</CalendarHeadCell>)}</CalendarRow>
    </Comp>
  );
}

export interface CalendarHeadCellProps extends ComponentProps<'th'> { asChild?: boolean }
function CalendarHeadCell({ asChild, className, ...props }: CalendarHeadCellProps) {
  const Comp = asChild ? Slot : 'th';
  return <Comp {...props} scope="col" className={cx('few-calendar-head-cell', className)} />;
}

export interface CalendarGridBodyProps extends ComponentProps<'tbody'> { asChild?: boolean }
function CalendarGridBody({ asChild, className, children, ...props }: CalendarGridBodyProps) {
  const ctx = useCalendar('Calendar.GridBody');
  const Comp = asChild ? Slot : 'tbody';
  if (children !== undefined) return <Comp {...props} className={cx('few-calendar-grid-body', className)}>{children}</Comp>;
  const weeks = calendarGrid(ctx.month.getFullYear(), ctx.month.getMonth(), ctx.weekStartsOn);
  return (
    <Comp {...props} className={cx('few-calendar-grid-body', className)}>
      {weeks.map(week => (
        <CalendarRow key={week[0].toISOString()}>
          {week.map(date => <CalendarCell key={date.toISOString()}><CalendarDay date={date} /></CalendarCell>)}
        </CalendarRow>
      ))}
    </Comp>
  );
}

export interface CalendarRowProps extends ComponentProps<'tr'> { asChild?: boolean }
function CalendarRow({ asChild, className, ...props }: CalendarRowProps) {
  const Comp = asChild ? Slot : 'tr';
  return <Comp {...props} role="row" className={cx('few-calendar-row', className)} />;
}

export interface CalendarCellProps extends ComponentProps<'td'> { asChild?: boolean }
function CalendarCell({ asChild, className, ...props }: CalendarCellProps) {
  const Comp = asChild ? Slot : 'td';
  return <Comp {...props} role="gridcell" className={cx('few-calendar-cell', className)} />;
}

export interface CalendarDayProps extends ComponentProps<'button'> { asChild?: boolean; date: Date }
function CalendarDay({ asChild, date, className, disabled: disabledProp, tabIndex, onClick, onKeyDown, children, ...props }: CalendarDayProps) {
  const ctx = useCalendar('Calendar.Day');
  const today = isSameDay(date, new Date());
  const outsideMonth = date.getMonth() !== ctx.month.getMonth() || date.getFullYear() !== ctx.month.getFullYear();
  const selected = isDateSelected(ctx.mode, ctx.value, date);
  const range = ctx.mode === 'range' && ctx.value && !Array.isArray(ctx.value) ? ctx.value as DateRange : undefined;
  const rangeStart = Boolean(range?.from && isSameDay(date, range.from));
  const rangeEnd = Boolean(range?.to && isSameDay(date, range.to));
  const inRange = Boolean(range && isInRange(date, range));
  const disabled = disabledProp ?? isDateDisabled(date, { min: ctx.min, max: ctx.max, disabledDates: ctx.disabledDates });
  const focused = isSameDay(date, ctx.focusedDate);
  const ref = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (focused && ctx.focusRef.current) ref.current?.focus(); }, [ctx.focusedDate, focused, ctx.focusRef]);
  function handleKeyDown(event: KeyboardEvent<HTMLButtonElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented || disabled) return;
    if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); ctx.selectDate(date); return; }
    let next: Date | null = null;
    if (event.key === 'ArrowLeft') next = addDays(date, -1);
    else if (event.key === 'ArrowRight') next = addDays(date, 1);
    else if (event.key === 'ArrowUp') next = addDays(date, -7);
    else if (event.key === 'ArrowDown') next = addDays(date, 7);
    else if (event.key === 'Home') next = addDays(date, -((date.getDay() - ctx.weekStartsOn + 7) % 7));
    else if (event.key === 'End') next = addDays(date, 6 - ((date.getDay() - ctx.weekStartsOn + 7) % 7));
    else if (event.key === 'PageUp') next = event.shiftKey ? addYears(date, -1) : addMonths(date, -1);
    else if (event.key === 'PageDown') next = event.shiftKey ? addYears(date, 1) : addMonths(date, 1);
    if (next) {
      event.preventDefault();
      ctx.focusRef.current = true;
      ctx.setFocusedDate(next);
      if (next.getMonth() !== ctx.month.getMonth() || next.getFullYear() !== ctx.month.getFullYear()) ctx.setMonth(startOfMonth(next));
    }
  }
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp {...props} ref={ref} type="button" tabIndex={tabIndex ?? (focused ? 0 : -1)} disabled={disabled} aria-selected={selected}
      aria-current={today ? 'date' : undefined} data-today={dataAttr(today)} data-outside-month={dataAttr(outsideMonth)}
      data-in-range={dataAttr(inRange)} data-range-start={dataAttr(rangeStart)} data-range-end={dataAttr(rangeEnd)} data-disabled={dataAttr(disabled)}
      className={cx('few-calendar-day', className)}
      onClick={(event) => { onClick?.(event); if (event.defaultPrevented || disabled) return; ctx.selectDate(date); ctx.focusRef.current = true; ctx.setFocusedDate(date); }}
      onKeyDown={handleKeyDown}>
      {children ?? date.getDate()}
    </Comp>
  );
}

/** Calendar composto: <Calendar mode="single" value={date} onValueChange={setDate}><Calendar.Header><Calendar.PrevButton/><Calendar.Heading/><Calendar.NextButton/></Calendar.Header><Calendar.Grid><Calendar.GridHead/><Calendar.GridBody/></Calendar.Grid></Calendar> */
export const Calendar = Object.assign(CalendarRoot, {
  Root: CalendarRoot, Header: CalendarHeader, PrevButton: CalendarPrevButton, NextButton: CalendarNextButton, Heading: CalendarHeading,
  Grid: CalendarGrid, GridHead: CalendarGridHead, HeadCell: CalendarHeadCell, GridBody: CalendarGridBody, Row: CalendarRow, Cell: CalendarCell, Day: CalendarDay,
});
export {
  CalendarRoot, CalendarHeader, CalendarPrevButton, CalendarNextButton, CalendarHeading,
  CalendarGrid, CalendarGridHead, CalendarHeadCell, CalendarGridBody, CalendarRow, CalendarCell, CalendarDay,
};

// packages/angular/src/components/pickers/calendar.ts
// Calendar: grade de dias (role=grid) com roving tabindex (Calendar.Day) e navegação completa por teclado.
// Toda a matemática de datas vem do core (calendarGrid, isSameDay, addDays/Months/Years, isInRange,
// isDateDisabled); aqui só ligamos estado a DOM e usamos Intl para nomes de mês/dia (Intl fica no Angular,
// como no React). GridHead/GridBody renderizam sozinhos por padrão (usando o core), mas aceitam conteúdo
// projetado para composição manual. Fonte da verdade: packages/react/src/components/pickers/calendar.tsx.
// Ver docs/composition-angular.md.
import {
  Component, Directive, ElementRef, computed, effect, inject, input, model, signal,
} from '@angular/core';
import {
  addDays, addMonths, addYears, calendarGrid, isDateDisabled, isInRange, isSameDay, startOfMonth, type DateRange,
} from '@fewcompany/core';
import { fewId } from '../../lib/ids.js';
import { dataAttr } from '../../lib/attrs.js';

export type CalendarMode = 'single' | 'range' | 'multiple';
export type CalendarValue = Date | Date[] | DateRange;

function isDateSelected(mode: CalendarMode, value: CalendarValue | undefined, date: Date): boolean {
  if (!value) return false;
  if (mode === 'multiple') return Array.isArray(value) && value.some(d => isSameDay(d, date));
  if (mode === 'range') { const range = value as DateRange; return Boolean((range.from && isSameDay(range.from, date)) || (range.to && isSameDay(range.to, date))); }
  return value instanceof Date && isSameDay(value, date);
}

/** Data inicial de foco/mês, calculada uma única vez (equivalente ao `useState(initializer)` do React). */
function initialFocusFromValue(mode: CalendarMode, value: CalendarValue | undefined): Date {
  if (mode === 'multiple' && Array.isArray(value) && value[0]) return value[0];
  if (mode === 'range' && value && !Array.isArray(value) && (value as DateRange).from) return (value as DateRange).from as Date;
  if (mode === 'single' && value instanceof Date) return value;
  return new Date();
}

/** Raiz: `<div fewCalendar mode="single" [(value)]="data">`. */
@Directive({ selector: '[fewCalendar]', exportAs: 'fewCalendar', host: { class: 'few-calendar', role: 'group', 'aria-label': 'Calendário' } })
export class FewCalendar {
  readonly mode = input<CalendarMode>('single');
  readonly value = model<CalendarValue | undefined>(undefined);
  readonly min = input<Date>();
  readonly max = input<Date>();
  readonly disabledDates = input<(date: Date) => boolean>();
  /** 0 = domingo … 6 = sábado. */
  readonly weekStartsOn = input(0);
  /** Locale do Intl para nomes de mês/semana. */
  readonly locale = input('pt-BR');
  readonly month = model<Date>(startOfMonth(new Date()));
  readonly baseId = fewId('calendar');
  readonly focusedDate = signal<Date>(new Date());
  /** Equivalente ao `useRef(false)` do React: evita autofoco na primeira renderização. */
  focusOnRender = false;
  private initialized = false;

  constructor() {
    // Calcula o foco/mês inicial uma única vez, a partir dos valores já vinculados (equivalente ao
    // useState(() => initialFocusFromValue(mode, value)) do React, que também só roda na montagem).
    effect(() => {
      if (this.initialized) return;
      this.initialized = true;
      const initial = initialFocusFromValue(this.mode(), this.value());
      this.focusedDate.set(initial);
      this.month.set(startOfMonth(initial));
    });
  }

  selectDate(date: Date): void {
    if (isDateDisabled(date, { min: this.min(), max: this.max(), disabledDates: this.disabledDates() })) return;
    const mode = this.mode();
    const current = this.value();
    if (mode === 'multiple') {
      const arr = Array.isArray(current) ? current : [];
      this.value.set(arr.some(d => isSameDay(d, date)) ? arr.filter(d => !isSameDay(d, date)) : [...arr, date]);
    } else if (mode === 'range') {
      const range = current && !Array.isArray(current) ? current as DateRange : {};
      if (!range.from || range.to) this.value.set({ from: date, to: undefined });
      else this.value.set(date.getTime() < range.from.getTime() ? { from: date, to: range.from } : { from: range.from, to: date });
    } else {
      this.value.set(date);
    }
  }
  setMonth(month: Date): void { this.month.set(month); }
  setFocusedDate(date: Date): void { this.focusedDate.set(date); }
}

@Directive({ selector: '[fewCalendarHeader]', host: { class: 'few-calendar-header' } })
export class FewCalendarHeader {}

/** Sem conteúdo projetado, mostra "‹". */
@Component({
  selector: '[fewCalendarPrevButton]',
  host: { class: 'few-calendar-nav', type: 'button', '[attr.aria-label]': 'ariaLabel()', '(click)': 'onClick()' },
  template: `<ng-content />@if (noContent()) {<span>‹</span>}`,
})
export class FewCalendarPrevButton {
  private readonly calendar = inject(FewCalendar);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly ariaLabel = input('Mês anterior', { alias: 'aria-label' });
  protected readonly noContent = signal(false);
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
  protected onClick(): void { this.calendar.setMonth(addMonths(this.calendar.month(), -1)); }
}

/** Sem conteúdo projetado, mostra "›". */
@Component({
  selector: '[fewCalendarNextButton]',
  host: { class: 'few-calendar-nav', type: 'button', '[attr.aria-label]': 'ariaLabel()', '(click)': 'onClick()' },
  template: `<ng-content />@if (noContent()) {<span>›</span>}`,
})
export class FewCalendarNextButton {
  private readonly calendar = inject(FewCalendar);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly ariaLabel = input('Próximo mês', { alias: 'aria-label' });
  protected readonly noContent = signal(false);
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
  protected onClick(): void { this.calendar.setMonth(addMonths(this.calendar.month(), 1)); }
}

/** Sem conteúdo projetado, mostra "Mês de Ano" (Intl, capitalizado) com aria-live="polite". */
@Component({
  selector: '[fewCalendarHeading]',
  host: { class: 'few-calendar-heading', '[id]': 'id', '[attr.aria-live]': "noContent() ? 'polite' : null" },
  template: `<ng-content />@if (noContent()) {<span>{{ label() }}</span>}`,
})
export class FewCalendarHeading {
  private readonly calendar = inject(FewCalendar);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  protected readonly noContent = signal(false);
  protected get id(): string { return `${this.calendar.baseId}-heading`; }
  protected readonly label = computed(() => {
    const text = new Intl.DateTimeFormat(this.calendar.locale(), { month: 'long', year: 'numeric' }).format(this.calendar.month());
    return text.length ? text.charAt(0).toUpperCase() + text.slice(1) : text;
  });
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
}

@Directive({ selector: '[fewCalendarGrid]', host: { class: 'few-calendar-grid', role: 'grid', '[attr.aria-labelledby]': 'headingId' } })
export class FewCalendarGrid {
  private readonly calendar = inject(FewCalendar);
  protected get headingId(): string { return `${this.calendar.baseId}-heading`; }
}

@Directive({ selector: '[fewCalendarRow]', host: { class: 'few-calendar-row', role: 'row' } })
export class FewCalendarRow {}

@Directive({ selector: '[fewCalendarHeadCell]', host: { class: 'few-calendar-head-cell', scope: 'col' } })
export class FewCalendarHeadCell {}

@Directive({ selector: '[fewCalendarCell]', host: { class: 'few-calendar-cell', role: 'gridcell' } })
export class FewCalendarCell {}

@Directive({
  selector: '[fewCalendarDay]',
  host: {
    class: 'few-calendar-day', type: 'button',
    '[attr.tabindex]': 'tabIndexValue()', '[attr.disabled]': 'disabled() ? "" : null',
    '[attr.aria-selected]': 'selected()', '[attr.aria-current]': "today() ? 'date' : null",
    '[attr.data-today]': 'dataAttr(today())', '[attr.data-outside-month]': 'dataAttr(outsideMonth())',
    '[attr.data-in-range]': 'dataAttr(inRange())', '[attr.data-range-start]': 'dataAttr(rangeStart())', '[attr.data-range-end]': 'dataAttr(rangeEnd())',
    '[attr.data-disabled]': 'dataAttr(disabled())',
    '(click)': 'onClick()', '(keydown)': 'onKeydown($event)',
  },
})
export class FewCalendarDay {
  private readonly calendar = inject(FewCalendar);
  private readonly el = inject<ElementRef<HTMLButtonElement>>(ElementRef);
  readonly date = input.required<Date>();
  protected readonly dataAttr = dataAttr;
  protected readonly today = computed(() => isSameDay(this.date(), new Date()));
  protected readonly outsideMonth = computed(() => {
    const d = this.date(), m = this.calendar.month();
    return d.getMonth() !== m.getMonth() || d.getFullYear() !== m.getFullYear();
  });
  protected readonly selected = computed(() => isDateSelected(this.calendar.mode(), this.calendar.value(), this.date()));
  private readonly range = computed<DateRange | undefined>(() => {
    const v = this.calendar.value();
    return this.calendar.mode() === 'range' && v && !Array.isArray(v) ? v as DateRange : undefined;
  });
  protected readonly rangeStart = computed(() => { const r = this.range(); return Boolean(r?.from && isSameDay(this.date(), r.from)); });
  protected readonly rangeEnd = computed(() => { const r = this.range(); return Boolean(r?.to && isSameDay(this.date(), r.to)); });
  protected readonly inRange = computed(() => { const r = this.range(); return Boolean(r && isInRange(this.date(), r)); });
  protected readonly disabled = computed(() => isDateDisabled(this.date(), { min: this.calendar.min(), max: this.calendar.max(), disabledDates: this.calendar.disabledDates() }));
  protected readonly focused = computed(() => isSameDay(this.date(), this.calendar.focusedDate()));
  protected readonly tabIndexValue = computed(() => this.focused() ? 0 : -1);

  constructor() {
    effect(() => {
      if (this.focused() && this.calendar.focusOnRender && typeof document !== 'undefined') this.el.nativeElement.focus();
    });
  }

  protected onClick(): void {
    if (this.disabled()) return;
    this.calendar.selectDate(this.date());
    this.calendar.focusOnRender = true;
    this.calendar.setFocusedDate(this.date());
  }

  protected onKeydown(event: KeyboardEvent): void {
    if (event.defaultPrevented || this.disabled()) return;
    if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); this.calendar.selectDate(this.date()); return; }
    const date = this.date();
    let next: Date | null = null;
    if (event.key === 'ArrowLeft') next = addDays(date, -1);
    else if (event.key === 'ArrowRight') next = addDays(date, 1);
    else if (event.key === 'ArrowUp') next = addDays(date, -7);
    else if (event.key === 'ArrowDown') next = addDays(date, 7);
    else if (event.key === 'Home') next = addDays(date, -((date.getDay() - this.calendar.weekStartsOn() + 7) % 7));
    else if (event.key === 'End') next = addDays(date, 6 - ((date.getDay() - this.calendar.weekStartsOn() + 7) % 7));
    else if (event.key === 'PageUp') next = event.shiftKey ? addYears(date, -1) : addMonths(date, -1);
    else if (event.key === 'PageDown') next = event.shiftKey ? addYears(date, 1) : addMonths(date, 1);
    if (next) {
      event.preventDefault();
      this.calendar.focusOnRender = true;
      this.calendar.setFocusedDate(next);
      const m = this.calendar.month();
      if (next.getMonth() !== m.getMonth() || next.getFullYear() !== m.getFullYear()) this.calendar.setMonth(startOfMonth(next));
    }
  }
}

/** Sem conteúdo projetado, renderiza a linha de nomes dos dias da semana (Intl, a partir de `weekStartsOn`). */
@Component({
  selector: '[fewCalendarGridHead]',
  imports: [FewCalendarRow, FewCalendarHeadCell],
  host: { class: 'few-calendar-grid-head' },
  template: `
    <ng-content />
    @if (noContent()) {
      <tr fewCalendarRow>
        @for (label of labels(); track $index) {
          <th fewCalendarHeadCell>{{ label }}</th>
        }
      </tr>
    }
  `,
})
export class FewCalendarGridHead {
  private readonly calendar = inject(FewCalendar);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  protected readonly noContent = signal(false);
  protected readonly labels = computed(() => {
    const formatter = new Intl.DateTimeFormat(this.calendar.locale(), { weekday: 'short' });
    const referenceSunday = new Date(2024, 0, 7);
    return Array.from({ length: 7 }, (_, i) => {
      const text = formatter.format(addDays(referenceSunday, (i + this.calendar.weekStartsOn()) % 7)).replace('.', '');
      return text.length ? text.charAt(0).toUpperCase() + text.slice(1) : text;
    });
  });
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
}

/** Sem conteúdo projetado, renderiza as semanas do mês corrente (core `calendarGrid`) com Calendar.Day. */
@Component({
  selector: '[fewCalendarGridBody]',
  imports: [FewCalendarRow, FewCalendarCell, FewCalendarDay],
  host: { class: 'few-calendar-grid-body' },
  template: `
    <ng-content />
    @if (noContent()) {
      @for (week of weeks(); track week[0].getTime()) {
        <tr fewCalendarRow>
          @for (date of week; track date.getTime()) {
            <td fewCalendarCell><button fewCalendarDay [date]="date"></button></td>
          }
        </tr>
      }
    }
  `,
})
export class FewCalendarGridBody {
  private readonly calendar = inject(FewCalendar);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  protected readonly noContent = signal(false);
  protected readonly weeks = computed(() => calendarGrid(this.calendar.month().getFullYear(), this.calendar.month().getMonth(), this.calendar.weekStartsOn()));
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
}

/** Importe tudo de uma vez: `imports: [FEW_CALENDAR]`. */
export const FEW_CALENDAR = [
  FewCalendar, FewCalendarHeader, FewCalendarPrevButton, FewCalendarNextButton, FewCalendarHeading,
  FewCalendarGrid, FewCalendarGridHead, FewCalendarHeadCell, FewCalendarGridBody, FewCalendarRow, FewCalendarCell, FewCalendarDay,
] as const;
