// packages/react/src/components/pickers/multi-select.tsx
"use client";
// MultiSelect: Trigger abre um painel com Search (filtra via filterOptions) + Itens em checkbox visual
// (aria-selected, seleção não fecha o painel). Foco fica no Search; navegação por activedescendant,
// igual ao Combobox. Backspace no Search vazio remove o último valor. Ver docs/composition.md.
import { useCallback, useEffect, useId, useMemo, useRef, useState, type ComponentProps, type ReactNode, type RefObject } from 'react';
import { filterOptions, nextIndex } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';
import { useDismiss } from '../../lib/use-dismiss.js';
import { usePosition, type Side, type Align } from '../../lib/use-position.js';
import { useTopLayer } from '../../lib/use-top-layer.js';

interface MultiSelectItemData { value: string; label: string; disabled?: boolean }
interface MultiSelectContextValue {
  baseId: string;
  value: string[]; setValue: (value: string[]) => void; toggleValue: (value: string) => void;
  open: boolean; setOpen: (open: boolean) => void;
  disabled?: boolean;
  search: string; setSearch: (search: string) => void;
  activeValue: string | null; setActiveValue: (value: string | null) => void;
  items: MultiSelectItemData[];
  registerItem: (item: MultiSelectItemData) => void;
  unregisterItem: (value: string) => void;
  visibleValues: Set<string>;
  triggerRef: RefObject<HTMLButtonElement | null>;
  searchRef: RefObject<HTMLInputElement | null>;
  contentRef: RefObject<HTMLDivElement | null>;
}
const [MultiSelectProvider, useMultiSelect] = createContext<MultiSelectContextValue>('MultiSelect');
const [MultiSelectItemProvider, useMultiSelectItemState] = createContext<{ checked: boolean; disabled?: boolean }>('MultiSelect.Item');

export interface MultiSelectProps extends Omit<ComponentProps<'div'>, 'defaultValue' | 'onChange'> {
  asChild?: boolean;
  value?: string[]; defaultValue?: string[]; onValueChange?: (value: string[]) => void;
  open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void;
  disabled?: boolean;
}
function MultiSelectRoot({ asChild, value: valueProp, defaultValue, onValueChange, open: openProp, defaultOpen = false, onOpenChange, disabled, className, children, ...props }: MultiSelectProps) {
  const baseId = useId();
  const [value, setValue] = useControllableState<string[]>({ value: valueProp, defaultValue: defaultValue ?? [], onChange: onValueChange });
  const [open, setOpen] = useControllableState({ value: openProp, defaultValue: defaultOpen, onChange: onOpenChange });
  const [search, setSearch] = useState('');
  const [activeValue, setActiveValue] = useState<string | null>(null);
  const [items, setItems] = useState<MultiSelectItemData[]>([]);
  const registerItem = useCallback((item: MultiSelectItemData) => setItems(prev => [...prev.filter(i => i.value !== item.value), item]), []);
  const unregisterItem = useCallback((itemValue: string) => setItems(prev => prev.filter(i => i.value !== itemValue)), []);
  const toggleValue = useCallback((v: string) => setValue(prev => prev.includes(v) ? prev.filter(x => x !== v) : [...prev, v]), [setValue]);
  const triggerRef = useRef<HTMLButtonElement>(null);
  const searchRef = useRef<HTMLInputElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);
  const visibleValues = useMemo(() => new Set(filterOptions(items, search, item => item.label).map(item => item.value)), [items, search]);
  const Comp = asChild ? Slot : 'div';
  return (
    <MultiSelectProvider value={{ baseId, value, setValue, toggleValue, open, setOpen, disabled, search, setSearch, activeValue, setActiveValue, items, registerItem, unregisterItem, visibleValues, triggerRef, searchRef, contentRef }}>
      <Comp {...props} className={cx('few-multi-select', className)} data-disabled={dataAttr(disabled)}>{children}</Comp>
    </MultiSelectProvider>
  );
}

export interface MultiSelectTriggerProps extends ComponentProps<'button'> { asChild?: boolean }
function MultiSelectTrigger({ asChild, className, disabled: disabledProp, onClick, ...props }: MultiSelectTriggerProps) {
  const ctx = useMultiSelect('MultiSelect.Trigger');
  const disabled = disabledProp ?? ctx.disabled;
  const Comp = asChild ? Slot : 'button';
  return (
    <Comp {...props} ref={ctx.triggerRef} type="button" aria-haspopup="listbox" aria-expanded={ctx.open} aria-controls={`${ctx.baseId}-content`}
      disabled={disabled} data-state={ctx.open ? 'open' : 'closed'} data-disabled={dataAttr(disabled)} className={cx('few-multi-select-trigger', className)}
      onClick={(event) => { onClick?.(event); if (event.defaultPrevented || disabled) return; ctx.setOpen(!ctx.open); }} />
  );
}

export interface MultiSelectValueProps extends ComponentProps<'div'> { asChild?: boolean; placeholder?: ReactNode; maxDisplay?: number }
function MultiSelectValue({ asChild, placeholder, maxDisplay = Infinity, className, children, ...props }: MultiSelectValueProps) {
  const ctx = useMultiSelect('MultiSelect.Value');
  const Comp = asChild ? Slot : 'div';
  if (asChild || children !== undefined) return <Comp {...props} className={cx('few-multi-select-value', className)}>{children}</Comp>;
  const selected = ctx.value.map(v => ctx.items.find(item => item.value === v)).filter((item): item is MultiSelectItemData => Boolean(item));
  if (selected.length === 0) return <div {...props} className={cx('few-multi-select-value', className)} data-placeholder="">{placeholder}</div>;
  const visible = selected.slice(0, maxDisplay);
  const overflow = selected.length - visible.length;
  return (
    <div {...props} className={cx('few-multi-select-value', className)}>
      {visible.map(item => (
        <span key={item.value} className="few-multi-select-chip">
          {item.label}
          <button type="button" className="few-multi-select-chip-remove" aria-label={`Remover ${item.label}`}
            onClick={(event) => { event.stopPropagation(); ctx.toggleValue(item.value); }}>×</button>
        </span>
      ))}
      {overflow > 0 && <span className="few-multi-select-chip few-multi-select-chip--overflow">+{overflow}</span>}
    </div>
  );
}

export interface MultiSelectContentProps extends ComponentProps<'div'> { asChild?: boolean; side?: Side; align?: Align }
function MultiSelectContent({ asChild, side = 'bottom', align = 'start', className, style, ...props }: MultiSelectContentProps) {
  const ctx = useMultiSelect('MultiSelect.Content');
  const position = usePosition(ctx.triggerRef, ctx.contentRef, { side, align, matchWidth: true, open: ctx.open });
  useTopLayer(ctx.contentRef, ctx.open);
  useDismiss(ctx.open, () => { ctx.setOpen(false); ctx.triggerRef.current?.focus(); }, [ctx.triggerRef, ctx.contentRef]);
  useEffect(() => { if (ctx.open) ctx.searchRef.current?.focus(); }, [ctx.open, ctx.searchRef]);
  const Comp = asChild ? Slot : 'div';
  return (
    <Comp {...props} ref={ctx.contentRef} popover="manual" role="listbox" aria-multiselectable="true" id={`${ctx.baseId}-content`}
      data-state={ctx.open ? 'open' : 'closed'} data-side={position.side} className={cx('few-multi-select-content', className)}
      style={{ ...position.style, ...style }} />
  );
}

export interface MultiSelectSearchProps extends Omit<ComponentProps<'input'>, 'value' | 'defaultValue'> { asChild?: boolean }
function MultiSelectSearch({ asChild, className, onChange, onKeyDown, 'aria-label': ariaLabel, ...props }: MultiSelectSearchProps) {
  const ctx = useMultiSelect('MultiSelect.Search');
  const Comp = asChild ? Slot : 'input';
  return (
    <Comp {...props} ref={ctx.searchRef} type="text" role="searchbox" aria-label={ariaLabel ?? 'Buscar opções'} autoComplete="off"
      aria-activedescendant={ctx.activeValue ? `${ctx.baseId}-item-${ctx.activeValue}` : undefined}
      value={ctx.search} className={cx('few-multi-select-search', className)}
      onChange={(event) => { onChange?.(event); if (event.defaultPrevented) return; ctx.setSearch(event.target.value); ctx.setActiveValue(null); }}
      onKeyDown={(event) => {
        onKeyDown?.(event);
        if (event.defaultPrevented) return;
        const navigable = ctx.items.filter(item => ctx.visibleValues.has(item.value) && !item.disabled);
        const currentIndex = navigable.findIndex(item => item.value === ctx.activeValue);
        if (event.key === 'ArrowDown' || event.key === 'ArrowUp' || event.key === 'Home' || event.key === 'End') {
          event.preventDefault();
          const idx = nextIndex(event.key, currentIndex, navigable.length, { orientation: 'vertical', loop: false });
          if (idx !== null && navigable[idx]) ctx.setActiveValue(navigable[idx].value);
          return;
        }
        if (event.key === 'Enter' || event.key === ' ') {
          if (ctx.activeValue) { event.preventDefault(); ctx.toggleValue(ctx.activeValue); }
          return;
        }
        if (event.key === 'Backspace' && ctx.search === '' && ctx.value.length > 0) {
          ctx.setValue(ctx.value.slice(0, -1));
        }
      }} />
  );
}

export interface MultiSelectItemProps extends ComponentProps<'div'> { asChild?: boolean; value: string; disabled?: boolean; textValue?: string }
function MultiSelectItem({ asChild, value, disabled, textValue, className, children, onClick, onPointerMove, ...props }: MultiSelectItemProps) {
  const ctx = useMultiSelect('MultiSelect.Item');
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    ctx.registerItem({ value, label: textValue ?? ref.current?.textContent ?? value, disabled });
    return () => ctx.unregisterItem(value);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value, textValue, disabled]);
  const visible = ctx.visibleValues.has(value);
  const checked = ctx.value.includes(value);
  const highlighted = ctx.activeValue === value;
  const Comp = asChild ? Slot : 'div';
  if (!visible) return null;
  return (
    <MultiSelectItemProvider value={{ checked, disabled }}>
      <Comp {...props} ref={ref} role="option" id={`${ctx.baseId}-item-${value}`} aria-selected={checked} aria-disabled={disabled}
        data-state={checked ? 'checked' : 'unchecked'} data-highlighted={dataAttr(highlighted)} data-disabled={dataAttr(disabled)} data-value={value}
        className={cx('few-multi-select-item', className)}
        onPointerMove={(event) => { onPointerMove?.(event); if (!disabled) ctx.setActiveValue(value); }}
        onClick={(event) => { onClick?.(event); if (event.defaultPrevented || disabled) return; ctx.toggleValue(value); }}>
        {children}
      </Comp>
    </MultiSelectItemProvider>
  );
}

export interface MultiSelectItemIndicatorProps extends ComponentProps<'span'> { asChild?: boolean; forceMount?: boolean }
function MultiSelectItemIndicator({ asChild, forceMount, className, children, ...props }: MultiSelectItemIndicatorProps) {
  const item = useMultiSelectItemState('MultiSelect.ItemIndicator');
  const Comp = asChild ? Slot : 'span';
  if (!item.checked && !forceMount) return null;
  return <Comp {...props} aria-hidden="true" className={cx('few-multi-select-item-indicator', className)}>{children ?? '✓'}</Comp>;
}

export interface MultiSelectEmptyProps extends ComponentProps<'div'> { asChild?: boolean }
function MultiSelectEmpty({ asChild, className, ...props }: MultiSelectEmptyProps) {
  const ctx = useMultiSelect('MultiSelect.Empty');
  const Comp = asChild ? Slot : 'div';
  if (ctx.items.length > 0 && ctx.visibleValues.size > 0) return null;
  return <Comp {...props} role="status" className={cx('few-multi-select-empty', className)} />;
}

/** Parte opcional (fora da lista mínima de partes): alterna todos os itens visíveis de uma vez. */
export interface MultiSelectSelectAllProps extends ComponentProps<'div'> { asChild?: boolean }
function MultiSelectSelectAll({ asChild, className, children, onClick, ...props }: MultiSelectSelectAllProps) {
  const ctx = useMultiSelect('MultiSelect.SelectAll');
  const visibleItems = ctx.items.filter(item => ctx.visibleValues.has(item.value) && !item.disabled);
  const allSelected = visibleItems.length > 0 && visibleItems.every(item => ctx.value.includes(item.value));
  const Comp = asChild ? Slot : 'div';
  return (
    <Comp {...props} role="option" aria-selected={allSelected} data-state={allSelected ? 'checked' : 'unchecked'}
      className={cx('few-multi-select-item few-multi-select-select-all', className)}
      onClick={(event) => {
        onClick?.(event);
        if (event.defaultPrevented) return;
        const visibleValuesArr = visibleItems.map(item => item.value);
        ctx.setValue(allSelected ? ctx.value.filter(v => !visibleValuesArr.includes(v)) : Array.from(new Set([...ctx.value, ...visibleValuesArr])));
      }}>
      {children ?? (allSelected ? 'Limpar seleção' : 'Selecionar todos')}
    </Comp>
  );
}

/** MultiSelect composto: <MultiSelect value={[]} onValueChange={...}><MultiSelect.Trigger><MultiSelect.Value placeholder="…"/></MultiSelect.Trigger><MultiSelect.Content><MultiSelect.Search/><MultiSelect.Item value="a">A</MultiSelect.Item></MultiSelect.Content></MultiSelect> */
export const MultiSelect = Object.assign(MultiSelectRoot, {
  Root: MultiSelectRoot, Trigger: MultiSelectTrigger, Value: MultiSelectValue, Content: MultiSelectContent, Search: MultiSelectSearch,
  Item: MultiSelectItem, ItemIndicator: MultiSelectItemIndicator, Empty: MultiSelectEmpty, SelectAll: MultiSelectSelectAll,
});
export {
  MultiSelectRoot, MultiSelectTrigger, MultiSelectValue, MultiSelectContent, MultiSelectSearch,
  MultiSelectItem, MultiSelectItemIndicator, MultiSelectEmpty, MultiSelectSelectAll,
};

// packages/angular/src/components/pickers/multi-select.ts
// MultiSelect: Trigger abre um painel com Search (filtra via filterOptions) + Itens em checkbox visual
// (aria-selected, seleção não fecha o painel). Foco fica no Search; navegação por activedescendant,
// igual ao Combobox. Backspace no Search vazio remove o último valor.
// Fonte da verdade: packages/react/src/components/pickers/multi-select.tsx. Ver docs/composition-angular.md.
import {
  Component, Directive, DestroyRef, ElementRef, afterNextRender, booleanAttribute, computed, effect, inject, input, model, signal,
} from '@angular/core';
import { filterOptions, nextIndex, type FloatingAlign, type FloatingSide } from '@fewcompany/core';
import { fewId } from '../../lib/ids.js';
import { setupDismiss } from '../../lib/dismiss.js';
import { setupPosition } from '../../lib/position.js';
import { setupTopLayer } from '../../lib/top-layer.js';
import { dataAttr, dataState } from '../../lib/attrs.js';

interface MultiSelectItemData { value: string; label: string; disabled?: boolean }

/** Raiz: `<div fewMultiSelect [(value)]="valores">`. */
@Directive({ selector: '[fewMultiSelect]', exportAs: 'fewMultiSelect', host: { class: 'few-multi-select', '[attr.data-disabled]': 'dataAttr(disabled())' } })
export class FewMultiSelect {
  readonly value = model<string[]>([]);
  readonly open = model(false);
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly baseId = fewId('multi-select');
  protected readonly dataAttr = dataAttr;

  private readonly searchState = signal('');
  readonly search = this.searchState.asReadonly();
  private readonly activeValueState = signal<string | null>(null);
  readonly activeValue = this.activeValueState.asReadonly();
  private readonly itemsState = signal<MultiSelectItemData[]>([]);
  readonly items = this.itemsState.asReadonly();
  private readonly triggerElementState = signal<HTMLElement | null>(null);
  private readonly searchElementState = signal<HTMLInputElement | null>(null);
  readonly visibleValues = computed(() => new Set(filterOptions(this.items(), this.searchState(), item => item.label).map(item => item.value)));

  get contentId(): string { return `${this.baseId}-content`; }
  setOpen(open: boolean): void { this.open.set(open); }
  setValue(value: string[]): void { this.value.set(value); }
  toggleValue(value: string): void { this.value.update(prev => prev.includes(value) ? prev.filter(v => v !== value) : [...prev, value]); }
  setSearch(search: string): void { this.searchState.set(search); }
  setActiveValue(value: string | null): void { this.activeValueState.set(value); }
  registerItem(item: MultiSelectItemData): void { this.itemsState.update(prev => [...prev.filter(i => i.value !== item.value), item]); }
  unregisterItem(value: string): void { this.itemsState.update(prev => prev.filter(i => i.value !== value)); }
  setTriggerElement(element: HTMLElement): void { this.triggerElementState.set(element); }
  triggerElement(): HTMLElement | null { return this.triggerElementState(); }
  focusTrigger(): void { this.triggerElementState()?.focus(); }
  setSearchElement(element: HTMLInputElement): void { this.searchElementState.set(element); }
  focusSearch(): void { this.searchElementState()?.focus(); }
}

@Directive({
  selector: '[fewMultiSelectTrigger]',
  host: {
    class: 'few-multi-select-trigger', type: 'button',
    '[attr.aria-haspopup]': "'listbox'", '[attr.aria-expanded]': 'multiSelect.open()', '[attr.aria-controls]': 'multiSelect.contentId',
    '[attr.disabled]': 'isDisabled() ? "" : null', '[attr.data-state]': 'dataState(multiSelect.open())', '[attr.data-disabled]': 'dataAttr(isDisabled())',
    '(click)': 'onClick()',
  },
})
export class FewMultiSelectTrigger {
  protected readonly multiSelect = inject(FewMultiSelect);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  /** Sobrepõe o `disabled` do Root quando definido. */
  readonly disabled = input<boolean>();
  protected readonly dataState = dataState;
  protected readonly dataAttr = dataAttr;
  protected readonly isDisabled = computed(() => this.disabled() ?? this.multiSelect.disabled());
  constructor() { this.multiSelect.setTriggerElement(this.el.nativeElement); }
  protected onClick(): void { if (!this.isDisabled()) this.multiSelect.setOpen(!this.multiSelect.open()); }
}

/** Mostra os valores selecionados como chips removíveis (até `maxDisplay`, com "+N" de sobra) ou o `placeholder`. */
@Component({
  selector: '[fewMultiSelectValue]',
  host: { class: 'few-multi-select-value', '[attr.data-placeholder]': 'dataAttr(selected().length === 0)' },
  template: `
    @if (selected().length === 0) {
      <ng-content />
      @if (noContent()) { <span>{{ placeholder() }}</span> }
    } @else {
      @for (item of visible(); track item.value) {
        <span class="few-multi-select-chip">
          {{ item.label }}
          <button type="button" class="few-multi-select-chip-remove" [attr.aria-label]="'Remover ' + item.label" (click)="remove($event, item.value)">×</button>
        </span>
      }
      @if (overflow() > 0) { <span class="few-multi-select-chip few-multi-select-chip--overflow">+{{ overflow() }}</span> }
    }
  `,
})
export class FewMultiSelectValue {
  private readonly multiSelect = inject(FewMultiSelect);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly placeholder = input<string>('');
  readonly maxDisplay = input<number>(Infinity);
  protected readonly dataAttr = dataAttr;
  protected readonly noContent = signal(false);
  protected readonly selected = computed(() => this.multiSelect.value()
    .map(v => this.multiSelect.items().find(item => item.value === v))
    .filter((item): item is MultiSelectItemData => Boolean(item)));
  protected readonly visible = computed(() => this.selected().slice(0, this.maxDisplay()));
  protected readonly overflow = computed(() => this.selected().length - this.visible().length);
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
  protected remove(event: Event, value: string): void { event.stopPropagation(); this.multiSelect.toggleValue(value); }
}

@Directive({
  selector: '[fewMultiSelectContent]',
  host: {
    class: 'few-multi-select-content', role: 'listbox', popover: 'manual', 'aria-multiselectable': 'true',
    '[id]': 'multiSelect.contentId', '[attr.data-state]': 'dataState(multiSelect.open())', '[attr.data-side]': 'position().side',
    '[style.position]': "'fixed'", '[style.top.px]': 'position().top', '[style.left.px]': 'position().left', '[style.width.px]': 'position().width',
  },
})
export class FewMultiSelectContent {
  protected readonly multiSelect = inject(FewMultiSelect);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly side = input<FloatingSide>('bottom');
  readonly align = input<FloatingAlign>('start');
  protected readonly dataState = dataState;
  protected readonly position = setupPosition(
    this.multiSelect.open, () => this.multiSelect.triggerElement(), () => this.el.nativeElement,
    () => ({ side: this.side(), align: this.align(), matchWidth: true }),
  );
  constructor() {
    setupTopLayer(this.multiSelect.open, () => this.el.nativeElement);
    setupDismiss(this.multiSelect.open, () => { this.multiSelect.setOpen(false); this.multiSelect.focusTrigger(); }, () => [this.multiSelect.triggerElement(), this.el.nativeElement]);
    effect(() => { if (this.multiSelect.open()) this.multiSelect.focusSearch(); });
  }
}

@Directive({
  selector: 'input[fewMultiSelectSearch]',
  host: {
    class: 'few-multi-select-search', type: 'text', role: 'searchbox', autocomplete: 'off',
    '[attr.aria-label]': 'ariaLabel()', '[attr.aria-activedescendant]': 'activeDescendant()', '[value]': 'multiSelect.search()',
    '(input)': 'onInput($event)', '(keydown)': 'onKeydown($event)',
  },
})
export class FewMultiSelectSearch {
  protected readonly multiSelect = inject(FewMultiSelect);
  private readonly el = inject<ElementRef<HTMLInputElement>>(ElementRef);
  readonly ariaLabel = input('Buscar opções', { alias: 'aria-label' });
  protected readonly activeDescendant = computed(() => {
    const active = this.multiSelect.activeValue();
    return active ? `${this.multiSelect.baseId}-item-${active}` : null;
  });
  constructor() { this.multiSelect.setSearchElement(this.el.nativeElement); }
  protected onInput(event: Event): void { this.multiSelect.setSearch((event.target as HTMLInputElement).value); this.multiSelect.setActiveValue(null); }
  protected onKeydown(event: KeyboardEvent): void {
    if (event.defaultPrevented) return;
    const navigable = this.multiSelect.items().filter(item => this.multiSelect.visibleValues().has(item.value) && !item.disabled);
    const currentIndex = navigable.findIndex(item => item.value === this.multiSelect.activeValue());
    if (event.key === 'ArrowDown' || event.key === 'ArrowUp' || event.key === 'Home' || event.key === 'End') {
      event.preventDefault();
      const idx = nextIndex(event.key, currentIndex, navigable.length, { orientation: 'vertical', loop: false });
      if (idx !== null && navigable[idx]) this.multiSelect.setActiveValue(navigable[idx].value);
      return;
    }
    if (event.key === 'Enter' || event.key === ' ') {
      const active = this.multiSelect.activeValue();
      if (active) { event.preventDefault(); this.multiSelect.toggleValue(active); }
      return;
    }
    if (event.key === 'Backspace' && this.multiSelect.search() === '' && this.multiSelect.value().length > 0) {
      this.multiSelect.setValue(this.multiSelect.value().slice(0, -1));
    }
  }
}

@Directive({
  selector: '[fewMultiSelectItem]',
  host: {
    class: 'few-multi-select-item', role: 'option',
    '[id]': 'id', '[hidden]': '!visible()',
    '[attr.aria-selected]': 'checked()', '[attr.aria-disabled]': 'disabled() ? "true" : null',
    '[attr.data-state]': 'checked() ? "checked" : "unchecked"', '[attr.data-highlighted]': 'dataAttr(highlighted())', '[attr.data-disabled]': 'dataAttr(disabled())', '[attr.data-value]': 'value()',
    '(pointermove)': 'onPointerMove()', '(click)': 'onClick()',
  },
})
export class FewMultiSelectItem {
  private readonly multiSelect = inject(FewMultiSelect);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly value = input.required<string>();
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly textValue = input<string>();
  protected readonly dataAttr = dataAttr;
  readonly checked = computed(() => this.multiSelect.value().includes(this.value()));
  protected readonly visible = computed(() => this.multiSelect.visibleValues().has(this.value()));
  protected readonly highlighted = computed(() => this.multiSelect.activeValue() === this.value());
  protected get id(): string { return `${this.multiSelect.baseId}-item-${this.value()}`; }

  constructor() {
    afterNextRender(() => this.multiSelect.registerItem({ value: this.value(), label: this.textValue() ?? this.el.nativeElement.textContent ?? this.value(), disabled: this.disabled() }));
    inject(DestroyRef).onDestroy(() => this.multiSelect.unregisterItem(this.value()));
  }

  protected onPointerMove(): void { if (!this.disabled()) this.multiSelect.setActiveValue(this.value()); }
  protected onClick(): void { if (!this.disabled()) this.multiSelect.toggleValue(this.value()); }
}

/** Só visível quando o Item pai está marcado, salvo `forceMount`. Sem conteúdo projetado, mostra "✓". */
@Component({
  selector: '[fewMultiSelectItemIndicator]',
  host: { class: 'few-multi-select-item-indicator', 'aria-hidden': 'true', '[hidden]': '!item.checked() && !forceMount()' },
  template: `<ng-content />@if (noContent()) {<span>✓</span>}`,
})
export class FewMultiSelectItemIndicator {
  protected readonly item = inject(FewMultiSelectItem);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly forceMount = input(false, { transform: booleanAttribute });
  protected readonly noContent = signal(false);
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
}

/** Mensagem de nenhum resultado; fica oculta enquanto houver itens registrados e algum visível. */
@Directive({ selector: '[fewMultiSelectEmpty]', host: { class: 'few-multi-select-empty', role: 'status', '[hidden]': 'hasVisibleItems()' } })
export class FewMultiSelectEmpty {
  private readonly multiSelect = inject(FewMultiSelect);
  protected readonly hasVisibleItems = computed(() => this.multiSelect.items().length > 0 && this.multiSelect.visibleValues().size > 0);
}

/** Alterna todos os itens visíveis de uma vez; sem conteúdo projetado, mostra "Selecionar todos" / "Limpar seleção". */
@Component({
  selector: '[fewMultiSelectSelectAll]',
  host: {
    class: 'few-multi-select-item few-multi-select-select-all', role: 'option',
    '[attr.aria-selected]': 'allSelected()', '[attr.data-state]': 'allSelected() ? "checked" : "unchecked"',
    '(click)': 'onClick()',
  },
  template: `<ng-content />@if (noContent()) {<span>{{ allSelected() ? 'Limpar seleção' : 'Selecionar todos' }}</span>}`,
})
export class FewMultiSelectSelectAll {
  private readonly multiSelect = inject(FewMultiSelect);
  private readonly el = inject<ElementRef<HTMLElement>>(ElementRef);
  protected readonly noContent = signal(false);
  private readonly visibleItems = computed(() => this.multiSelect.items().filter(item => this.multiSelect.visibleValues().has(item.value) && !item.disabled));
  protected readonly allSelected = computed(() => {
    const items = this.visibleItems();
    return items.length > 0 && items.every(item => this.multiSelect.value().includes(item.value));
  });
  ngAfterContentInit(): void { this.noContent.set(!this.el.nativeElement.textContent?.trim()); }
  protected onClick(): void {
    const visibleValuesArr = this.visibleItems().map(item => item.value);
    const allSelected = this.allSelected();
    const current = this.multiSelect.value();
    this.multiSelect.setValue(allSelected ? current.filter(v => !visibleValuesArr.includes(v)) : Array.from(new Set([...current, ...visibleValuesArr])));
  }
}

/** Importe tudo de uma vez: `imports: [FEW_MULTI_SELECT]`. */
export const FEW_MULTI_SELECT = [
  FewMultiSelect, FewMultiSelectTrigger, FewMultiSelectValue, FewMultiSelectContent, FewMultiSelectSearch,
  FewMultiSelectItem, FewMultiSelectItemIndicator, FewMultiSelectEmpty, FewMultiSelectSelectAll,
] as const;
