// packages/react/src/components/feedback/badge.tsx
"use client";
import type { ComponentProps } from 'react';
import type { Tone } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { cx } from '../../lib/cx.js';

export type BadgeVariant = 'solid' | 'soft' | 'outline';
export type BadgeSize = 'sm' | 'md';

export interface BadgeProps extends ComponentProps<'span'> {
  asChild?: boolean;
  tone?: Tone;
  variant?: BadgeVariant;
  size?: BadgeSize;
  /** Bolinha antes do conteúdo (padrão dos badges de status do Caraminholas/iFIGHT). */
  dot?: boolean;
}
/** Componente simples (sem partes), como Radix Badge/Kbd: só asChild + className + data-*. */
export function Badge({ asChild, tone = 'neutral', variant = 'soft', size = 'md', dot = false, className, children, ...props }: BadgeProps) {
  const Comp = asChild ? Slot : 'span';
  return (
    <Comp
      {...props}
      className={cx('few-badge', `few-tone--${tone}`, `few-badge--${variant}`, `few-badge--${size}`, className)}
      data-tone={tone}
      data-variant={variant}
    >
      {dot && <span className="few-dot" aria-hidden="true" />}
      {children}
    </Comp>
  );
}

// packages/angular/src/components/feedback/badge.ts
// Badge (ver docs/composition-angular.md). Fonte da verdade: packages/react/src/components/feedback/badge.tsx.
import { Component, booleanAttribute, computed, input } from '@angular/core';
import type { Tone } from '@fewcompany/core';

export type BadgeVariant = 'solid' | 'soft' | 'outline';
export type BadgeSize = 'sm' | 'md';

/** Componente simples (sem partes): `<span fewBadge tone="success" dot>Ativo</span>`. */
@Component({
  selector: '[fewBadge]',
  host: {
    '[class]': 'classes()',
    '[attr.data-tone]': 'tone()',
    '[attr.data-variant]': 'variant()',
  },
  template: `@if (dot()) { <span class="few-dot" aria-hidden="true"></span> }<ng-content></ng-content>`,
})
export class FewBadge {
  readonly tone = input<Tone>('neutral');
  readonly variant = input<BadgeVariant>('soft');
  readonly size = input<BadgeSize>('md');
  /** Bolinha antes do conteúdo. */
  readonly dot = input(false, { transform: booleanAttribute });
  protected readonly classes = computed(() => `few-badge few-tone--${this.tone()} few-badge--${this.variant()} few-badge--${this.size()}`);
}

export const FEW_BADGE = [FewBadge] as const;
