// packages/angular/src/demos/feedback.ts
// Hosts de demonstração/teste da categoria "Feedback" (pasta components/feedback). Um @Component por id do registry,
// selector few-demo-<id>. Textos e exemplos espelham apps/catalog/demos/feedback.tsx (React) quando fazem sentido.
import { Component, signal, type Type } from '@angular/core';
import { FEW_ALERT } from '../components/feedback/alert.js';
import { FEW_BADGE } from '../components/feedback/badge.js';
import { FEW_TAG } from '../components/feedback/tag.js';
import { FEW_PROGRESS } from '../components/feedback/progress.js';
import { FEW_PROGRESS_CIRCLE } from '../components/feedback/progress-circle.js';
import { FEW_SPINNER } from '../components/feedback/spinner.js';
import { FEW_SKELETON } from '../components/feedback/skeleton.js';
import { FEW_EMPTY_STATE } from '../components/feedback/empty-state.js';

@Component({
  selector: 'few-demo-alert',
  imports: [FEW_ALERT],
  template: `
    <div class="demo-stack demo-narrow">
      @if (soft()) {
        <div fewAlert tone="success" variant="soft">
          <span fewAlertIcon></span>
          <strong fewAlertTitle>Salvo</strong>
          <div fewAlertDescription>Suas alterações foram salvas com sucesso.</div>
          <button fewAlertClose aria-label="Fechar aviso" (dismiss)="soft.set(false)"></button>
        </div>
      }
      @if (outline()) {
        <div fewAlert tone="danger" variant="outline">
          <span fewAlertIcon></span>
          <strong fewAlertTitle>Falha ao publicar</strong>
          <div fewAlertDescription>Verifique sua conexão e tente novamente.</div>
          <div fewAlertAction><button type="button" class="few-button few-button--secondary">Tentar de novo</button></div>
          <button fewAlertClose aria-label="Fechar aviso" (dismiss)="outline.set(false)"></button>
        </div>
      }
      @if (!soft() && !outline()) {
        <p class="few-muted">Os dois avisos foram fechados.</p>
      }
    </div>
  `,
})
export class DemoAlert {
  readonly soft = signal(true);
  readonly outline = signal(true);
}

@Component({
  selector: 'few-demo-badge',
  imports: [FEW_BADGE],
  template: `
    <div class="demo-stack">
      <div class="demo-row">
        <span fewBadge tone="neutral">Rascunho</span>
        <span fewBadge tone="success" dot>Ativo</span>
        <span fewBadge tone="warning">Pendente</span>
        <span fewBadge tone="danger">Bloqueado</span>
        <span fewBadge tone="info">Novo</span>
      </div>
      <div class="demo-row">
        <span fewBadge tone="success" variant="solid">Solid</span>
        <span fewBadge tone="success" variant="soft">Soft</span>
        <span fewBadge tone="success" variant="outline">Outline</span>
        <span fewBadge tone="info" size="sm">Pequeno</span>
      </div>
    </div>
  `,
})
export class DemoBadge {}

@Component({
  selector: 'few-demo-tag',
  imports: [FEW_TAG],
  template: `
    <div class="demo-stack">
      <div class="demo-row">
        @for (tag of tags(); track tag) {
          <span fewTag tone="info" variant="soft">
            <span fewTagLabel>{{ tag }}</span>
            <button fewTagClose [label]="tag" (remove)="remove(tag)"></button>
          </span>
        }
        @if (tags().length === 0) {
          <p class="few-muted">Todas as tags foram removidas.</p>
        }
      </div>
      <span fewTag tone="neutral" variant="outline" interactive (select)="restore()">
        <span fewTagLabel>Restaurar tags</span>
      </span>
    </div>
  `,
})
export class DemoTag {
  readonly tags = signal(['React', 'TypeScript', 'Acessibilidade']);
  remove(tag: string) { this.tags.update(current => current.filter(item => item !== tag)); }
  restore() { this.tags.set(['React', 'TypeScript', 'Acessibilidade']); }
}

@Component({
  selector: 'few-demo-progress',
  imports: [FEW_PROGRESS],
  template: `
    <div class="demo-stack demo-narrow">
      <div fewProgress [value]="indeterminate() ? null : value()" tone="info">
        <span fewProgressLabel>Importação de dados</span>
        <span fewProgressValue></span>
        <div fewProgressTrack><div fewProgressIndicator></div></div>
      </div>
      <div class="demo-row">
        <button type="button" class="few-button few-button--secondary" [disabled]="indeterminate()" (click)="value.set(Math.min(100, value() + 10))">+10%</button>
        <button type="button" class="few-button few-button--secondary" [disabled]="indeterminate()" (click)="value.set(Math.max(0, value() - 10))">-10%</button>
        <label class="few-muted"><input type="checkbox" [checked]="indeterminate()" (change)="indeterminate.set(!indeterminate())" /> Indeterminado</label>
      </div>
    </div>
  `,
})
export class DemoProgress {
  readonly value = signal(30);
  readonly indeterminate = signal(false);
  protected readonly Math = Math;
}

@Component({
  selector: 'few-demo-progress-circle',
  imports: [FEW_PROGRESS_CIRCLE],
  template: `
    <div class="demo-row">
      <div fewProgressCircle [value]="value()" tone="success" size="md">
        <svg fewProgressCircleCircle></svg>
        <span fewProgressCircleLabel></span>
      </div>
      <div fewProgressCircle [value]="null" tone="info" size="md">
        <svg fewProgressCircleCircle></svg>
      </div>
      <div class="demo-stack">
        <button type="button" class="few-button few-button--secondary" (click)="value.set(Math.min(100, value() + 15))">+15%</button>
        <button type="button" class="few-button few-button--secondary" (click)="value.set(Math.max(0, value() - 15))">-15%</button>
      </div>
    </div>
  `,
})
export class DemoProgressCircle {
  readonly value = signal(65);
  protected readonly Math = Math;
}

@Component({
  selector: 'few-demo-spinner',
  imports: [FEW_SPINNER],
  template: `
    <div class="demo-row">
      <span fewSpinner size="sm" label="Carregando"></span>
      <span fewSpinner size="md" tone="info" label="Carregando pedidos"></span>
      <span fewSpinner size="lg" tone="success" label="Enviando"></span>
    </div>
  `,
})
export class DemoSpinner {}

@Component({
  selector: 'few-demo-skeleton',
  imports: [FEW_SKELETON],
  template: `
    <div class="demo-stack demo-narrow">
      <label class="few-muted"><input type="checkbox" [checked]="loading()" (change)="loading.set(!loading())" /> Carregando</label>
      @if (loading()) {
        <div class="demo-row" style="align-items:flex-start">
          <span fewSkeleton variant="circle"></span>
          <span fewSkeleton variant="text" [lines]="3"></span>
        </div>
      } @else {
        <div class="demo-row" style="align-items:flex-start">
          <span aria-hidden="true" class="few-empty-icon" style="width:40px;height:40px;font-size:18px">VN</span>
          <p class="few-muted">Vinícius Negrão publicou 3 novos componentes no catálogo Few UI.</p>
        </div>
      }
    </div>
  `,
})
export class DemoSkeleton {
  readonly loading = signal(true);
}

@Component({
  selector: 'few-demo-empty-state',
  imports: [FEW_EMPTY_STATE],
  template: `
    <div class="demo-narrow">
      <div fewEmptyState size="sm">
        <span fewEmptyStateIcon></span>
        <h3 fewEmptyStateTitle>Nenhum projeto ainda</h3>
        <p fewEmptyStateDescription>Crie o primeiro projeto para começar a organizar seu trabalho.</p>
        <div fewEmptyStateActions>
          <button type="button" class="few-button" (click)="created.set(true)">+ Novo projeto</button>
        </div>
      </div>
      @if (created()) {
        <p class="few-muted">Projeto criado.</p>
      }
    </div>
  `,
})
export class DemoEmptyState {
  readonly created = signal(false);
}

export const FEEDBACK_DEMOS: Record<string, Type<unknown>> = {
  alert: DemoAlert,
  badge: DemoBadge,
  tag: DemoTag,
  progress: DemoProgress,
  'progress-circle': DemoProgressCircle,
  spinner: DemoSpinner,
  skeleton: DemoSkeleton,
  'empty-state': DemoEmptyState,
};

// apps/catalog/demos/feedback.tsx
"use client";
import { useState } from 'react';
import { Alert, Badge, Button, EmptyState, Progress, ProgressCircle, Skeleton, Spinner, Tag } from '@fewcompany/ui';
import type { DemoMap } from './types';
// Demos da categoria "Feedback". Chave = id do registry. Cada demo é um componente React interativo.

function AlertDemo() {
  const [visible, setVisible] = useState({ soft: true, outline: true });
  return (
    <div className="demo-stack demo-narrow">
      {visible.soft && (
        <Alert tone="success" variant="soft">
          <Alert.Icon />
          <Alert.Title>Salvo</Alert.Title>
          <Alert.Description>Suas alterações foram salvas com sucesso.</Alert.Description>
          <Alert.Close aria-label="Fechar aviso" onDismiss={() => setVisible(v => ({ ...v, soft: false }))} />
        </Alert>
      )}
      {visible.outline && (
        <Alert tone="danger" variant="outline">
          <Alert.Icon />
          <Alert.Title>Falha ao publicar</Alert.Title>
          <Alert.Description>Verifique sua conexão e tente novamente.</Alert.Description>
          <Alert.Action><button type="button" className="few-button few-button--secondary">Tentar de novo</button></Alert.Action>
          <Alert.Close aria-label="Fechar aviso" onDismiss={() => setVisible(v => ({ ...v, outline: false }))} />
        </Alert>
      )}
      {!visible.soft && !visible.outline && <p className="few-muted">Os dois avisos foram fechados. Recarregue a página para vê-los de novo.</p>}
    </div>
  );
}

function BadgeDemo() {
  return (
    <div className="demo-stack">
      <div className="demo-row">
        <Badge tone="neutral">Rascunho</Badge>
        <Badge tone="success" dot>Ativo</Badge>
        <Badge tone="warning">Pendente</Badge>
        <Badge tone="danger">Bloqueado</Badge>
        <Badge tone="info">Novo</Badge>
      </div>
      <div className="demo-row">
        <Badge tone="success" variant="solid">Solid</Badge>
        <Badge tone="success" variant="soft">Soft</Badge>
        <Badge tone="success" variant="outline">Outline</Badge>
        <Badge tone="info" size="sm">Pequeno</Badge>
      </div>
    </div>
  );
}

function TagDemo() {
  const [tags, setTags] = useState(['React', 'TypeScript', 'Acessibilidade']);
  return (
    <div className="demo-stack">
      <div className="demo-row">
        {tags.map(tag => (
          <Tag key={tag} tone="info" variant="soft">
            <Tag.Label>{tag}</Tag.Label>
            <Tag.Close label={tag} onRemove={() => setTags(current => current.filter(item => item !== tag))} />
          </Tag>
        ))}
        {tags.length === 0 && <p className="few-muted">Todas as tags foram removidas.</p>}
      </div>
      <Tag tone="neutral" variant="outline" onClick={() => setTags(['React', 'TypeScript', 'Acessibilidade'])}>
        <Tag.Label>Restaurar tags</Tag.Label>
      </Tag>
    </div>
  );
}

function ProgressDemo() {
  const [value, setValue] = useState(30);
  const [indeterminate, setIndeterminate] = useState(false);
  return (
    <div className="demo-stack demo-narrow">
      <Progress value={indeterminate ? null : value} tone="info">
        <Progress.Label>Importação de dados</Progress.Label>
        <Progress.Value />
        <Progress.Track><Progress.Indicator /></Progress.Track>
      </Progress>
      <div className="demo-row">
        <button type="button" className="few-button few-button--secondary" disabled={indeterminate} onClick={() => setValue(v => Math.min(100, v + 10))}>+10%</button>
        <button type="button" className="few-button few-button--secondary" disabled={indeterminate} onClick={() => setValue(v => Math.max(0, v - 10))}>-10%</button>
        <label className="few-muted"><input type="checkbox" checked={indeterminate} onChange={e => setIndeterminate(e.target.checked)} /> Indeterminado</label>
      </div>
    </div>
  );
}

function ProgressCircleDemo() {
  const [value, setValue] = useState(65);
  return (
    <div className="demo-row">
      <ProgressCircle value={value} tone="success" size="md">
        <ProgressCircle.Circle />
        <ProgressCircle.Label />
      </ProgressCircle>
      <ProgressCircle value={null} tone="info" size="md">
        <ProgressCircle.Circle />
      </ProgressCircle>
      <div className="demo-stack">
        <button type="button" className="few-button few-button--secondary" onClick={() => setValue(v => Math.min(100, v + 15))}>+15%</button>
        <button type="button" className="few-button few-button--secondary" onClick={() => setValue(v => Math.max(0, v - 15))}>-15%</button>
      </div>
    </div>
  );
}

function SpinnerDemo() {
  return (
    <div className="demo-row">
      <Spinner size="sm" label="Carregando" />
      <Spinner size="md" tone="info" label="Carregando pedidos" />
      <Spinner size="lg" tone="success" label="Enviando" />
    </div>
  );
}

function SkeletonDemo() {
  const [loading, setLoading] = useState(true);
  return (
    <div className="demo-stack demo-narrow">
      <label className="few-muted"><input type="checkbox" checked={loading} onChange={e => setLoading(e.target.checked)} /> Carregando</label>
      {loading ? (
        <div className="demo-row" style={{ alignItems: 'flex-start' }}>
          <Skeleton variant="circle" />
          <Skeleton variant="text" lines={3} />
        </div>
      ) : (
        <div className="demo-row" style={{ alignItems: 'flex-start' }}>
          <span aria-hidden="true" className="few-empty-icon" style={{ width: 40, height: 40, fontSize: 18 }}>VN</span>
          <p className="few-muted">Vinícius Negrão publicou 3 novos componentes no catálogo Few UI.</p>
        </div>
      )}
    </div>
  );
}

function EmptyStateDemo() {
  const [status, setStatus] = useState<'empty' | 'success'>('empty');
  if (status === 'success') {
    return (
      <div className="demo-narrow">
        <Alert tone="success" variant="soft">
          <Alert.Icon />
          <Alert.Title>Projeto criado</Alert.Title>
          <Alert.Description>O projeto foi adicionado à sua lista.</Alert.Description>
          <Alert.Close aria-label="Fechar aviso" onDismiss={() => setStatus('empty')} />
        </Alert>
      </div>
    );
  }
  return (
    <div className="demo-narrow">
      <EmptyState size="sm">
        <EmptyState.Icon />
        <EmptyState.Title>Nenhum projeto ainda</EmptyState.Title>
        <EmptyState.Description>Crie o primeiro projeto para começar a organizar seu trabalho.</EmptyState.Description>
        <EmptyState.Actions>
          <Button onClick={() => setStatus('success')}>+ Novo projeto</Button>
        </EmptyState.Actions>
      </EmptyState>
    </div>
  );
}

export const feedbackDemos: DemoMap = {
  alert: AlertDemo,
  badge: BadgeDemo,
  tag: TagDemo,
  progress: ProgressDemo,
  'progress-circle': ProgressCircleDemo,
  spinner: SpinnerDemo,
  skeleton: SkeletonDemo,
  'empty-state': EmptyStateDemo,
};
