// packages/angular/src/components/navigation/command-menu.ts
// Ver docs/composition-angular.md. Fonte da verdade: packages/react/src/components/navigation/command-menu.tsx.
import { Component, Directive, DestroyRef, ElementRef, booleanAttribute, computed, effect, inject, input, model, output, signal } from '@angular/core';
import { commandScore, nextIndex, normalizeText } from '@fewcompany/core';
import { fewId } from '../../lib/ids.js';
import { dataAttr } from '../../lib/attrs.js';

/** Raiz: `<dialog fewCommandMenu [(open)]="open" shortcut>`. `showModal()/close()` em efeito sobre `open()`. Foco volta ao elemento que abriu o diálogo ao fechar. */
@Component({
  selector: 'dialog[fewCommandMenu]',
  exportAs: 'fewCommandMenu',
  host: { class: 'few-command', '[attr.aria-label]': 'label()', '(close)': 'onClose()' },
  template: `<ng-content />`,
})
export class FewCommandMenu {
  private readonly elementRef = inject<ElementRef<HTMLDialogElement>>(ElementRef);
  readonly open = model(false);
  /** Ativa o atalho global Ctrl/Cmd+K para abrir e fechar. */
  readonly shortcut = input(false, { transform: booleanAttribute });
  /** Rótulo acessível do diálogo. */
  readonly label = input('Comandos');
  readonly baseId = fewId('command');
  readonly query = signal('');
  readonly activeId = signal<string | null>(null);
  readonly empty = signal(false);
  /** Elemento da lista, preenchido por FewCommandList; usado para varrer as opções visíveis. */
  listElement: HTMLElement | null = null;
  private previouslyFocused: HTMLElement | null = null;

  constructor() {
    effect(() => {
      if (typeof document === 'undefined') return;
      const dialog = this.elementRef.nativeElement;
      if (this.open()) {
        if (!dialog.open) {
          this.previouslyFocused = document.activeElement as HTMLElement | null;
          dialog.showModal();
          this.query.set('');
          this.activeId.set(null);
        }
      } else if (dialog.open) {
        dialog.close();
        this.previouslyFocused?.focus();
      }
    });

    effect(() => {
      if (typeof document === 'undefined') return;
      this.query(); this.open();
      const container = this.listElement;
      if (!container) return;
      const options = Array.from(container.querySelectorAll<HTMLElement>('[role="option"]:not([hidden])'));
      this.empty.set(options.length === 0);
      const current = this.activeId();
      this.activeId.set(current && options.some(option => option.id === current) ? current : (options[0]?.id ?? null));
    });

    effect((onCleanup) => {
      if (typeof document === 'undefined' || !this.shortcut()) return;
      const onKeyDown = (event: KeyboardEvent) => {
        if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); this.open.set(!this.open()); }
      };
      document.addEventListener('keydown', onKeyDown);
      onCleanup(() => document.removeEventListener('keydown', onKeyDown));
    });
  }

  setOpen(value: boolean) { this.open.set(value); }
  setQuery(query: string) { this.query.set(query); }
  setActiveId(id: string | null) { this.activeId.set(id); }
  protected onClose() { this.open.set(false); }
}

@Directive({
  selector: 'input[fewCommandInput]',
  host: {
    class: 'few-command-input', type: 'text', role: 'combobox', 'aria-expanded': 'true', autocomplete: 'off', spellcheck: 'false',
    '[attr.aria-controls]': 'listId', '[attr.aria-activedescendant]': 'command.activeId()',
    '[value]': 'command.query()', '(input)': 'onInput($event)', '(keydown)': 'onKeydown($event)',
  },
})
export class FewCommandInput {
  protected readonly command = inject(FewCommandMenu);
  protected get listId() { return `${this.command.baseId}-list`; }
  protected onInput(event: Event) { this.command.setQuery((event.target as HTMLInputElement).value); }
  protected onKeydown(event: KeyboardEvent) {
    if (event.defaultPrevented) return;
    if (event.key === 'Enter') {
      event.preventDefault();
      const id = this.command.activeId();
      (id ? document.getElementById(id) : null)?.click();
      return;
    }
    const options = Array.from(this.command.listElement?.querySelectorAll<HTMLElement>('[role="option"]:not([hidden])') ?? []);
    if (!options.length) return;
    const activeId = this.command.activeId();
    const current = activeId ? options.findIndex(option => option.id === activeId) : -1;
    const next = nextIndex(event.key, current < 0 ? 0 : current, options.length, { orientation: 'vertical', loop: false });
    if (next === null) return;
    event.preventDefault();
    const target = options[next];
    this.command.setActiveId(target.id);
    target.scrollIntoView({ block: 'nearest' });
  }
}

@Directive({ selector: '[fewCommandList]', host: { class: 'few-command-list', role: 'listbox', '[id]': 'id' } })
export class FewCommandList {
  private readonly command = inject(FewCommandMenu);
  private readonly elementRef = inject<ElementRef<HTMLElement>>(ElementRef);
  protected get id() { return `${this.command.baseId}-list`; }
  constructor() {
    const el = this.elementRef.nativeElement;
    this.command.listElement = el;
    inject(DestroyRef).onDestroy(() => { if (this.command.listElement === el) this.command.listElement = null; });
  }
}

@Directive({ selector: '[fewCommandGroup]', host: { class: 'few-command-group', role: 'group' } })
export class FewCommandGroup {}

@Directive({ selector: '[fewCommandGroupHeading]', host: { class: 'few-command-group-heading' } })
export class FewCommandGroupHeading {}

/** Item pesquisável. `value` é o texto pesquisável (sem acento) e identificador entregue a `select`. Some do DOM (via `hidden`) quando não corresponde à busca. */
@Component({
  selector: '[fewCommandItem]',
  host: {
    class: 'few-command-item', role: 'option',
    '[id]': 'id()', '[hidden]': '!matches()',
    '[attr.aria-selected]': 'active()', '[attr.aria-disabled]': 'disabled() ? "true" : null', '[attr.data-disabled]': 'dataAttr(disabled())',
    '[attr.data-state]': 'active() ? "active" : null',
    '(click)': 'onClick()', '(mouseenter)': 'onMouseEnter()',
  },
  template: `<ng-content />`,
})
export class FewCommandItem {
  protected readonly command = inject(FewCommandMenu);
  readonly value = input.required<string>();
  readonly keywords = input<string[]>();
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly select = output<string>();
  protected readonly dataAttr = dataAttr;
  protected readonly matches = computed(() => commandScore(this.value(), this.command.query(), this.keywords() ?? []) !== null);
  protected readonly id = computed(() => `${this.command.baseId}-item-${normalizeText(this.value()).replace(/\s+/g, '-')}`);
  protected readonly active = computed(() => this.command.activeId() === this.id());
  protected onClick() { if (!this.disabled() && this.matches()) this.select.emit(this.value()); }
  protected onMouseEnter() { if (!this.disabled() && this.matches()) this.command.setActiveId(this.id()); }
}

/** Mensagem de nenhum resultado. Fica oculta (`hidden`) enquanto houver opções visíveis. Sem conteúdo projetado, mostra "Nada encontrado.". */
@Component({
  selector: '[fewCommandEmpty]',
  host: { class: 'few-command-empty', role: 'status', '[hidden]': '!command.empty()' },
  template: `<ng-content />@if (noContent()) {<span>Nada encontrado.</span>}`,
})
export class FewCommandEmpty {
  protected readonly command = inject(FewCommandMenu);
  private readonly elementRef = inject<ElementRef<HTMLElement>>(ElementRef);
  protected readonly noContent = signal(false);
  ngAfterContentInit() { this.noContent.set(!this.elementRef.nativeElement.textContent?.trim()); }
}

@Directive({ selector: '[fewCommandSeparator]', host: { class: 'few-command-separator', role: 'separator', 'aria-orientation': 'horizontal' } })
export class FewCommandSeparator {}

@Directive({ selector: '[fewCommandShortcut]', host: { class: 'few-command-shortcut' } })
export class FewCommandShortcut {}

/** Importe tudo de uma vez: `imports: [FEW_COMMAND_MENU]`. */
export const FEW_COMMAND_MENU = [
  FewCommandMenu, FewCommandInput, FewCommandList, FewCommandGroup, FewCommandGroupHeading, FewCommandItem, FewCommandEmpty, FewCommandSeparator, FewCommandShortcut,
] as const;

// packages/react/src/components/navigation/command-menu.tsx
"use client";
import { useEffect, useId, useLayoutEffect, useRef, useState, type ComponentProps, type KeyboardEvent, type MouseEvent, type RefObject, type SyntheticEvent } from 'react';
import { commandScore, nextIndex, normalizeText } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';

interface CommandContextValue {
  baseId: string;
  query: string; setQuery: (query: string) => void;
  activeId: string | null; setActiveId: (id: string | null) => void;
  listRef: RefObject<HTMLDivElement | null>;
  empty: boolean;
}
const [CommandProvider, useCommand] = createContext<CommandContextValue>('CommandMenu');

export interface CommandMenuProps extends Omit<ComponentProps<'dialog'>, 'open'> {
  asChild?: boolean;
  open?: boolean; defaultOpen?: boolean; onOpenChange?: (open: boolean) => void;
  /** Ativa o atalho global Ctrl/Cmd+K para abrir e fechar. */
  shortcut?: boolean;
  /** Rótulo acessível do diálogo. */
  label?: string;
}
function CommandMenuRoot({ asChild, open: openProp, defaultOpen = false, onOpenChange, shortcut = false, label = 'Comandos', className, onClose, onCancel, ...props }: CommandMenuProps) {
  const baseId = useId();
  const [open, setOpen] = useControllableState({ value: openProp, defaultValue: defaultOpen, onChange: onOpenChange });
  const [query, setQuery] = useState('');
  const [activeId, setActiveId] = useState<string | null>(null);
  const [empty, setEmpty] = useState(false);
  const dialogRef = useRef<HTMLDialogElement>(null);
  const listRef = useRef<HTMLDivElement>(null);
  const previouslyFocused = useRef<HTMLElement | null>(null);

  useEffect(() => {
    if (!shortcut) return;
    function onKeyDown(event: globalThis.KeyboardEvent) {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setOpen(current => !current); }
    }
    document.addEventListener('keydown', onKeyDown);
    return () => document.removeEventListener('keydown', onKeyDown);
  }, [shortcut, setOpen]);

  useLayoutEffect(() => {
    const dialog = dialogRef.current;
    if (!dialog) return;
    if (open) { previouslyFocused.current = document.activeElement as HTMLElement | null; if (!dialog.open) dialog.showModal(); }
    else if (dialog.open) { dialog.close(); previouslyFocused.current?.focus(); }
  }, [open]);

  useLayoutEffect(() => { if (open) { setQuery(''); setActiveId(null); } }, [open]);

  useLayoutEffect(() => {
    const container = listRef.current;
    if (!container) return;
    const options = Array.from(container.querySelectorAll<HTMLElement>('[role="option"]'));
    setEmpty(options.length === 0);
    setActiveId(current => (current && options.some(option => option.id === current)) ? current : (options[0]?.id ?? null));
  }, [query, open]);

  function handleClose(event: SyntheticEvent<HTMLDialogElement>) { onClose?.(event); setOpen(false); }

  const Comp = asChild ? Slot : 'dialog';
  return <CommandProvider value={{ baseId, query, setQuery, activeId, setActiveId, listRef, empty }}>
    <Comp {...props} ref={dialogRef} aria-label={label} className={cx('few-command', className)} onClose={handleClose} onCancel={onCancel} />
  </CommandProvider>;
}

export interface CommandInputProps extends Omit<ComponentProps<'input'>, 'value' | 'onChange'> { asChild?: boolean }
function CommandInput({ asChild, className, onKeyDown, ...props }: CommandInputProps) {
  const { baseId, query, setQuery, activeId, setActiveId, listRef } = useCommand('CommandMenu.Input');
  const Comp = asChild ? Slot : 'input';
  function handleKeyDown(event: KeyboardEvent<HTMLInputElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented) return;
    if (event.key === 'Enter') { event.preventDefault(); (activeId ? document.getElementById(activeId) : null)?.click(); return; }
    const options = Array.from(listRef.current?.querySelectorAll<HTMLElement>('[role="option"]') ?? []);
    if (!options.length) return;
    const current = activeId ? options.findIndex(option => option.id === activeId) : -1;
    const next = nextIndex(event.key, current < 0 ? 0 : current, options.length, { orientation: 'vertical', loop: false });
    if (next === null) return;
    event.preventDefault();
    const target = options[next];
    setActiveId(target.id);
    target.scrollIntoView({ block: 'nearest' });
  }
  return <Comp {...props} type="text" role="combobox" aria-expanded="true" aria-controls={`${baseId}-list`} aria-autocomplete="list"
    aria-activedescendant={activeId ?? undefined} autoComplete="off" spellCheck={false}
    value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={handleKeyDown} className={cx('few-command-input', className)} />;
}

export interface CommandListProps extends ComponentProps<'div'> { asChild?: boolean }
function CommandList({ asChild, className, ...props }: CommandListProps) {
  const { baseId, listRef } = useCommand('CommandMenu.List');
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} ref={listRef} id={`${baseId}-list`} role="listbox" className={cx('few-command-list', className)} />;
}

export interface CommandGroupProps extends ComponentProps<'div'> { asChild?: boolean }
function CommandGroup({ asChild, className, ...props }: CommandGroupProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} role="group" className={cx('few-command-group', className)} />;
}

export interface CommandGroupHeadingProps extends ComponentProps<'div'> { asChild?: boolean }
function CommandGroupHeading({ asChild, className, ...props }: CommandGroupHeadingProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} className={cx('few-command-group-heading', className)} />;
}

export interface CommandItemProps extends Omit<ComponentProps<'div'>, 'onSelect'> {
  asChild?: boolean;
  /** Texto pesquisável (sem acento) e identificador entregue a onSelect. */
  value: string;
  keywords?: string[];
  disabled?: boolean;
  onSelect?: (value: string) => void;
}
function CommandItem({ asChild, value, keywords, disabled, onSelect, className, id: idProp, onClick, onMouseEnter, ...props }: CommandItemProps) {
  const { baseId, query, activeId, setActiveId } = useCommand('CommandMenu.Item');
  const matches = commandScore(value, query, keywords) !== null;
  if (!matches) return null;
  const id = idProp ?? `${baseId}-item-${normalizeText(value).replace(/\s+/g, '-')}`;
  const active = activeId === id;
  const Comp = asChild ? Slot : 'div';
  function handleClick(event: MouseEvent<HTMLDivElement>) {
    onClick?.(event);
    if (event.defaultPrevented || disabled) return;
    onSelect?.(value);
  }
  function handleMouseEnter(event: MouseEvent<HTMLDivElement>) {
    onMouseEnter?.(event);
    if (!disabled) setActiveId(id);
  }
  return <Comp {...props} id={id} role="option" aria-selected={active} aria-disabled={disabled ? true : undefined} data-disabled={dataAttr(disabled)}
    data-state={active ? 'active' : undefined} className={cx('few-command-item', className)} onClick={handleClick} onMouseEnter={handleMouseEnter} />;
}

export interface CommandEmptyProps extends ComponentProps<'div'> { asChild?: boolean }
function CommandEmpty({ asChild, className, children, ...props }: CommandEmptyProps) {
  const { empty } = useCommand('CommandMenu.Empty');
  if (!empty) return null;
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} role="status" className={cx('few-command-empty', className)}>{children ?? 'Nada encontrado.'}</Comp>;
}

export interface CommandSeparatorProps extends ComponentProps<'div'> { asChild?: boolean }
function CommandSeparator({ asChild, className, ...props }: CommandSeparatorProps) {
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} role="separator" aria-orientation="horizontal" className={cx('few-command-separator', className)} />;
}

export interface CommandShortcutProps extends ComponentProps<'kbd'> { asChild?: boolean }
function CommandShortcut({ asChild, className, ...props }: CommandShortcutProps) {
  const Comp = asChild ? Slot : 'kbd';
  return <Comp {...props} className={cx('few-command-shortcut', className)} />;
}

/** CommandMenu composto: <CommandMenu open={open} onOpenChange={setOpen} shortcut><CommandMenu.Input /><CommandMenu.List><CommandMenu.Empty>Nada encontrado.</CommandMenu.Empty><CommandMenu.Group><CommandMenu.GroupHeading>Ações</CommandMenu.GroupHeading><CommandMenu.Item value="Novo projeto" onSelect={run}>Novo projeto</CommandMenu.Item></CommandMenu.Group></CommandMenu.List></CommandMenu> */
export const CommandMenu = Object.assign(CommandMenuRoot, {
  Root: CommandMenuRoot, Input: CommandInput, List: CommandList, Group: CommandGroup, GroupHeading: CommandGroupHeading,
  Item: CommandItem, Empty: CommandEmpty, Separator: CommandSeparator, Shortcut: CommandShortcut,
});
export { CommandMenuRoot, CommandInput, CommandList, CommandGroup, CommandGroupHeading, CommandItem, CommandEmpty, CommandSeparator, CommandShortcut };
