// packages/angular/src/components/navigation/navigation-menu.ts
// Ver docs/composition-angular.md. Fonte da verdade: packages/react/src/components/navigation/navigation-menu.tsx.
import { Component, Directive, DestroyRef, ElementRef, booleanAttribute, computed, effect, inject, input, model, signal } from '@angular/core';
import { fewId } from '../../lib/ids.js';
import { moveFocus } from '../../lib/roving.js';
import { setupDismiss } from '../../lib/dismiss.js';
import { setupPosition } from '../../lib/position.js';
import { setupTopLayer } from '../../lib/top-layer.js';
import { dataAttr } from '../../lib/attrs.js';

/** Raiz: `<nav fewNavigationMenu [(value)]="open">`. Sem binding, `value` é interno (não controlado). */
@Directive({
  selector: '[fewNavigationMenu]',
  exportAs: 'fewNavigationMenu',
  host: { class: 'few-navigation-menu', '[attr.aria-label]': 'ariaLabel()' },
})
export class FewNavigationMenu {
  readonly value = model<string | null>(null);
  readonly ariaLabel = input('Menu principal', { alias: 'aria-label' });
  readonly baseId = fewId('navmenu');
  /** Triggers registrados por valor (usado pelo Indicator para medir posição). Não reativo, uso interno. */
  readonly triggers = new Map<string, HTMLElement>();
  setValue(value: string | null) { this.value.set(value); }
}

/** Lista dos triggers, com roving horizontal (setas/Home/End) entre eles. */
@Directive({
  selector: '[fewNavigationMenuList]',
  host: { class: 'few-navigation-menu-list', '(keydown)': 'onKeydown($event)' },
})
export class FewNavigationMenuList {
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  protected onKeydown(event: KeyboardEvent) {
    if (event.defaultPrevented) return;
    const target = moveFocus(this.host.nativeElement, '[data-few-navmenu-trigger]', event.key, { orientation: 'horizontal' });
    if (target) event.preventDefault();
  }
}

/** Item: `<li fewNavigationMenuItem value="produtos">`. Publica {value, open, ids} para Trigger/Content. */
@Directive({
  selector: '[fewNavigationMenuItem]',
  exportAs: 'fewNavigationMenuItem',
  host: { class: 'few-navigation-menu-item', '[attr.data-state]': 'open() ? "open" : "closed"' },
})
export class FewNavigationMenuItem {
  protected readonly menu = inject(FewNavigationMenu);
  readonly value = input.required<string>();
  /** Público: lido por FewNavigationMenuTrigger/Content, que só têm o item injetado (não herdam). */
  readonly open = computed(() => this.menu.value() === this.value());
  /** Referência ao elemento do trigger, preenchida por FewNavigationMenuTrigger; usada como âncora pelo Content. */
  triggerEl: HTMLElement | null = null;
  get triggerId() { return `${this.menu.baseId}-trigger-${this.value()}`; }
  get contentId() { return `${this.menu.baseId}-content-${this.value()}`; }
}

/** Abre no hover, foco ou Enter/ArrowDown; fecha com Escape ou ao abrir outro item. */
@Directive({
  selector: '[fewNavigationMenuTrigger]',
  host: {
    class: 'few-navigation-menu-trigger', type: 'button', 'data-few-navmenu-trigger': '',
    '[id]': 'item.triggerId', '[attr.data-state]': 'item.open() ? "open" : "closed"',
    '[attr.aria-expanded]': 'item.open()', '[attr.aria-controls]': 'item.contentId',
    '(click)': 'onClick()', '(keydown)': 'onKeydown($event)', '(focus)': 'onFocus()', '(mouseenter)': 'onFocus()',
  },
})
export class FewNavigationMenuTrigger {
  private readonly menu = inject(FewNavigationMenu);
  protected readonly item = inject(FewNavigationMenuItem);
  private readonly elementRef = inject<ElementRef<HTMLElement>>(ElementRef);
  constructor() {
    const el = this.elementRef.nativeElement;
    this.item.triggerEl = el;
    this.menu.triggers.set(this.item.value(), el);
    inject(DestroyRef).onDestroy(() => {
      this.menu.triggers.delete(this.item.value());
      if (this.item.triggerEl === el) this.item.triggerEl = null;
    });
  }
  protected onClick() { this.menu.setValue(this.item.open() ? null : this.item.value()); }
  protected onKeydown(event: KeyboardEvent) {
    if (event.defaultPrevented) return;
    if (event.key === 'Escape' && this.item.open()) { event.preventDefault(); this.menu.setValue(null); }
    else if (event.key === 'ArrowDown' && !this.item.open()) { event.preventDefault(); this.menu.setValue(this.item.value()); }
  }
  protected onFocus() { this.menu.setValue(this.item.value()); }
}

/** Flyout posicionado com setupPosition + top layer nativo (popover="manual"); fecha com Escape e clique fora. */
@Component({
  selector: '[fewNavigationMenuContent]',
  host: {
    class: 'few-navigation-menu-content', popover: 'manual', role: 'group',
    '[id]': 'item.contentId', '[attr.aria-labelledby]': 'item.triggerId',
    '[attr.data-state]': 'item.open() ? "open" : "closed"',
    '[style.position]': '"fixed"', '[style.top.px]': 'position().top', '[style.left.px]': 'position().left',
    '[attr.data-side]': 'position().side',
    '(keydown)': 'onKeydown($event)',
  },
  template: `<ng-content />`,
})
export class FewNavigationMenuContent {
  private readonly menu = inject(FewNavigationMenu);
  protected readonly item = inject(FewNavigationMenuItem);
  private readonly elementRef = inject<ElementRef<HTMLElement>>(ElementRef);
  protected readonly position = setupPosition(this.item.open, () => this.item.triggerEl, () => this.elementRef.nativeElement, () => ({ side: 'bottom', align: 'start' }));
  constructor() {
    setupTopLayer(this.item.open, () => this.elementRef.nativeElement);
    setupDismiss(this.item.open, () => this.menu.setValue(null), () => [this.item.triggerEl, this.elementRef.nativeElement]);
  }
  protected onKeydown(event: KeyboardEvent) {
    if (event.defaultPrevented) return;
    if (event.key === 'Escape') { event.preventDefault(); this.menu.setValue(null); }
  }
}

@Directive({
  selector: '[fewNavigationMenuLink]',
  host: { class: 'few-navigation-menu-link', '[attr.aria-current]': 'active() ? "page" : null', '[attr.data-active]': 'dataAttr(active())' },
})
export class FewNavigationMenuLink {
  readonly active = input(false, { transform: booleanAttribute });
  protected readonly dataAttr = dataAttr;
}

/** Indicador que acompanha a posição do trigger aberto (renderize dentro de List). */
@Component({
  selector: '[fewNavigationMenuIndicator]',
  host: {
    class: 'few-navigation-menu-indicator', 'aria-hidden': 'true',
    '[attr.data-state]': 'rect() ? "visible" : null',
    '[style.display]': 'rect() ? null : "none"',
    '[style.transform]': 'rect() ? "translateX(" + rect()!.left + "px)" : null',
    '[style.width.px]': 'rect()?.width',
  },
  template: ``,
})
export class FewNavigationMenuIndicator {
  private readonly menu = inject(FewNavigationMenu);
  protected readonly rect = signal<{ left: number; width: number } | null>(null);
  constructor() {
    effect(() => {
      const value = this.menu.value();
      if (typeof window === 'undefined') { this.rect.set(null); return; }
      const trigger = value ? this.menu.triggers.get(value) : undefined;
      this.rect.set(trigger ? { left: trigger.offsetLeft, width: trigger.offsetWidth } : null);
    });
  }
}

/** Importe tudo de uma vez: `imports: [FEW_NAVIGATION_MENU]`. */
export const FEW_NAVIGATION_MENU = [
  FewNavigationMenu, FewNavigationMenuList, FewNavigationMenuItem, FewNavigationMenuTrigger, FewNavigationMenuContent, FewNavigationMenuLink, FewNavigationMenuIndicator,
] as const;

// packages/react/src/components/navigation/navigation-menu.tsx
"use client";
import { useId, useLayoutEffect, useRef, useState, type ComponentProps, type FocusEvent, type KeyboardEvent, type MouseEvent, type RefObject } from 'react';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';
import { moveFocus } from '../../lib/roving.js';
import { useDismiss } from '../../lib/use-dismiss.js';
import { usePosition } from '../../lib/use-position.js';
import { useTopLayer } from '../../lib/use-top-layer.js';

interface NavigationMenuContextValue {
  baseId: string;
  value: string | null;
  setValue: (value: string | null) => void;
  triggers: Map<string, HTMLElement>;
}
const [NavigationMenuProvider, useNavigationMenu] = createContext<NavigationMenuContextValue>('NavigationMenu');

interface NavigationMenuItemContextValue { value: string; open: boolean; triggerId: string; contentId: string; triggerRef: RefObject<HTMLElement | null> }
const [NavigationMenuItemProvider, useNavigationMenuItem] = createContext<NavigationMenuItemContextValue>('NavigationMenu.Item');

export interface NavigationMenuProps extends Omit<ComponentProps<'nav'>, 'defaultValue'> {
  asChild?: boolean;
  value?: string | null; defaultValue?: string | null; onValueChange?: (value: string | null) => void;
}
function NavigationMenuRoot({ asChild, value: valueProp, defaultValue = null, onValueChange, className, 'aria-label': ariaLabel = 'Menu principal', ...props }: NavigationMenuProps) {
  const baseId = useId();
  const [value, setValue] = useControllableState<string | null>({ value: valueProp, defaultValue, onChange: onValueChange });
  const triggers = useRef(new Map<string, HTMLElement>()).current;
  const Comp = asChild ? Slot : 'nav';
  return <NavigationMenuProvider value={{ baseId, value, setValue, triggers }}>
    <Comp {...props} aria-label={ariaLabel} className={cx('few-navigation-menu', className)} />
  </NavigationMenuProvider>;
}

/** Lista dos triggers, com roving horizontal (setas/Home/End) entre eles. */
export interface NavigationMenuListProps extends ComponentProps<'ul'> { asChild?: boolean }
function NavigationMenuList({ asChild, className, onKeyDown, ...props }: NavigationMenuListProps) {
  const ref = useRef<HTMLUListElement>(null);
  const Comp = asChild ? Slot : 'ul';
  function handleKeyDown(event: KeyboardEvent<HTMLUListElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented) return;
    const target = moveFocus(ref.current, '[data-few-navmenu-trigger]', event.key, { orientation: 'horizontal' });
    if (target) event.preventDefault();
  }
  return <Comp {...props} ref={ref} className={cx('few-navigation-menu-list', className)} onKeyDown={handleKeyDown} />;
}

export interface NavigationMenuItemProps extends ComponentProps<'li'> { asChild?: boolean; value: string }
function NavigationMenuItem({ asChild, value, className, ...props }: NavigationMenuItemProps) {
  const { baseId, value: openValue } = useNavigationMenu('NavigationMenu.Item');
  const triggerRef = useRef<HTMLElement>(null);
  const open = openValue === value;
  const triggerId = `${baseId}-trigger-${value}`;
  const contentId = `${baseId}-content-${value}`;
  const Comp = asChild ? Slot : 'li';
  return <NavigationMenuItemProvider value={{ value, open, triggerId, contentId, triggerRef }}>
    <Comp {...props} data-state={open ? 'open' : 'closed'} className={cx('few-navigation-menu-item', className)} />
  </NavigationMenuItemProvider>;
}

/** Abre no hover, foco ou Enter/ArrowDown; fecha com Escape ou ao abrir outro item. */
export interface NavigationMenuTriggerProps extends ComponentProps<'button'> { asChild?: boolean }
function NavigationMenuTrigger({ asChild, className, onClick, onKeyDown, onFocus, onMouseEnter, ...props }: NavigationMenuTriggerProps) {
  const { setValue, triggers } = useNavigationMenu('NavigationMenu.Trigger');
  const { value, open, triggerId, contentId, triggerRef } = useNavigationMenuItem('NavigationMenu.Trigger');
  const Comp = asChild ? Slot : 'button';
  function refCallback(node: HTMLElement | null) {
    triggerRef.current = node;
    if (node) triggers.set(value, node); else triggers.delete(value);
  }
  function handleClick(event: MouseEvent<HTMLButtonElement>) {
    onClick?.(event);
    if (event.defaultPrevented) return;
    setValue(open ? null : value);
  }
  function handleKeyDown(event: KeyboardEvent<HTMLButtonElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented) return;
    if (event.key === 'Escape' && open) { event.preventDefault(); setValue(null); }
    else if (event.key === 'ArrowDown' && !open) { event.preventDefault(); setValue(value); }
  }
  function handleFocus(event: FocusEvent<HTMLButtonElement>) { onFocus?.(event); setValue(value); }
  function handleMouseEnter(event: MouseEvent<HTMLButtonElement>) { onMouseEnter?.(event); setValue(value); }
  return <Comp {...props} ref={refCallback} type="button" id={triggerId} data-few-navmenu-trigger="" data-state={open ? 'open' : 'closed'}
    aria-expanded={open} aria-controls={contentId}
    className={cx('few-navigation-menu-trigger', className)}
    onClick={handleClick} onKeyDown={handleKeyDown} onFocus={handleFocus} onMouseEnter={handleMouseEnter} />;
}

/** Flyout posicionado com usePosition + top layer nativo (popover="manual"); fecha com Escape e clique fora. */
export interface NavigationMenuContentProps extends ComponentProps<'div'> { asChild?: boolean }
function NavigationMenuContent({ asChild, className, onKeyDown, style, ...props }: NavigationMenuContentProps) {
  const { setValue } = useNavigationMenu('NavigationMenu.Content');
  const { open, contentId, triggerId, triggerRef } = useNavigationMenuItem('NavigationMenu.Content');
  const ref = useRef<HTMLDivElement>(null);
  useTopLayer(ref, open);
  const position = usePosition(triggerRef, ref, { side: 'bottom', align: 'start', open });
  useDismiss(open, () => setValue(null), [triggerRef, ref]);
  function handleKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented) return;
    if (event.key === 'Escape') { event.preventDefault(); setValue(null); }
  }
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} ref={ref} popover="manual" id={contentId} role="group" aria-labelledby={triggerId}
    data-state={open ? 'open' : 'closed'} style={{ ...position.style, ...style }}
    className={cx('few-navigation-menu-content', className)} onKeyDown={handleKeyDown} />;
}

export interface NavigationMenuLinkProps extends ComponentProps<'a'> { asChild?: boolean; active?: boolean }
function NavigationMenuLink({ asChild, active, className, ...props }: NavigationMenuLinkProps) {
  const Comp = asChild ? Slot : 'a';
  return <Comp {...props} aria-current={active ? 'page' : undefined} data-active={dataAttr(active)} className={cx('few-navigation-menu-link', className)} />;
}

/** Indicador que acompanha a posição do trigger aberto (renderize dentro de List). */
export interface NavigationMenuIndicatorProps extends ComponentProps<'div'> { asChild?: boolean }
function NavigationMenuIndicator({ asChild, className, style, ...props }: NavigationMenuIndicatorProps) {
  const { value, triggers } = useNavigationMenu('NavigationMenu.Indicator');
  const [rect, setRect] = useState<{ left: number; width: number } | null>(null);
  useLayoutEffect(() => {
    const trigger = value ? triggers.get(value) : undefined;
    if (trigger) setRect({ left: trigger.offsetLeft, width: trigger.offsetWidth });
  }, [value, triggers]);
  if (!value || !rect) return null;
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} aria-hidden="true" data-state="visible" style={{ ...style, transform: `translateX(${rect.left}px)`, width: `${rect.width}px` }} className={cx('few-navigation-menu-indicator', className)} />;
}

/** NavigationMenu composto: <NavigationMenu><NavigationMenu.List><NavigationMenu.Item value="produtos"><NavigationMenu.Trigger>Produtos</NavigationMenu.Trigger><NavigationMenu.Content><NavigationMenu.Link href="/a">Produto A</NavigationMenu.Link></NavigationMenu.Content></NavigationMenu.Item></NavigationMenu.List></NavigationMenu> */
export const NavigationMenu = Object.assign(NavigationMenuRoot, { Root: NavigationMenuRoot, List: NavigationMenuList, Item: NavigationMenuItem, Trigger: NavigationMenuTrigger, Content: NavigationMenuContent, Link: NavigationMenuLink, Indicator: NavigationMenuIndicator });
export { NavigationMenuRoot, NavigationMenuList, NavigationMenuItem, NavigationMenuTrigger, NavigationMenuContent, NavigationMenuLink, NavigationMenuIndicator };
