// packages/angular/src/components/navigation/tabs.ts
// Implementação de referência do padrão composto em Angular (ver docs/composition-angular.md).
import { Directive, ElementRef, booleanAttribute, computed, inject, input, model } from '@angular/core';
import type { Orientation } from '@fewcompany/core';
import { fewId } from '../../lib/ids.js';
import { moveFocus } from '../../lib/roving.js';
import { dataAttr } from '../../lib/attrs.js';

/** Raiz: `<div fewTabs [(value)]="tab">`. Sem binding, o estado é interno (não controlado). */
@Directive({
  selector: '[fewTabs]',
  exportAs: 'fewTabs',
  host: { class: 'few-tabs', '[attr.data-orientation]': 'orientation()' },
})
export class FewTabs {
  readonly value = model<string>('');
  readonly orientation = input<Orientation>('horizontal');
  /** automatic: seta seleciona; manual: seta só move o foco, Enter/Espaço seleciona. */
  readonly activation = input<'automatic' | 'manual'>('automatic');
  readonly baseId = fewId('tabs');
  select(value: string) { this.value.set(value); }
}

@Directive({
  selector: '[fewTabsList]',
  host: { class: 'few-tabs-list', role: 'tablist', '[attr.aria-orientation]': 'tabs.orientation()', '[attr.data-orientation]': 'tabs.orientation()', '(keydown)': 'onKeydown($event)' },
})
export class FewTabsList {
  protected readonly tabs = inject(FewTabs);
  private readonly host = inject<ElementRef<HTMLElement>>(ElementRef);
  readonly loop = input(true, { transform: booleanAttribute });
  protected onKeydown(event: KeyboardEvent) {
    if (event.defaultPrevented) return;
    const target = moveFocus(this.host.nativeElement, '[role="tab"]', event.key, { orientation: this.tabs.orientation(), loop: this.loop() });
    if (!target) return;
    event.preventDefault();
    if (this.tabs.activation() === 'automatic' && target.dataset['value'] !== undefined) this.tabs.select(target.dataset['value']);
  }
}

@Directive({
  selector: '[fewTabsTrigger]',
  host: {
    class: 'few-tabs-trigger', role: 'tab', type: 'button',
    '[id]': 'id', '[attr.aria-selected]': 'active()', '[attr.aria-controls]': 'panelId', '[attr.tabindex]': 'active() ? 0 : -1',
    '[attr.disabled]': 'disabled() ? "" : null', '[attr.data-state]': 'active() ? "active" : "inactive"', '[attr.data-value]': 'value()', '[attr.data-disabled]': 'dataAttr(disabled())',
    '(click)': 'select()',
  },
})
export class FewTabsTrigger {
  private readonly tabs = inject(FewTabs);
  readonly value = input.required<string>();
  readonly disabled = input(false, { transform: booleanAttribute });
  protected readonly active = computed(() => this.tabs.value() === this.value());
  protected readonly dataAttr = dataAttr;
  protected get id() { return `${this.tabs.baseId}-tab-${this.value()}`; }
  protected get panelId() { return `${this.tabs.baseId}-panel-${this.value()}`; }
  protected select() { if (!this.disabled()) this.tabs.select(this.value()); }
}

/** Painel: fica no DOM com `hidden` quando inativo (equivale a forceMount). Use `@if` para desmontar. */
@Directive({
  selector: '[fewTabsContent]',
  host: {
    class: 'few-tabs-content', role: 'tabpanel', tabindex: '0',
    '[id]': 'id', '[attr.aria-labelledby]': 'tabId', '[hidden]': '!active()', '[attr.data-state]': 'active() ? "active" : "inactive"',
  },
})
export class FewTabsContent {
  private readonly tabs = inject(FewTabs);
  readonly value = input.required<string>();
  protected readonly active = computed(() => this.tabs.value() === this.value());
  protected get id() { return `${this.tabs.baseId}-panel-${this.value()}`; }
  protected get tabId() { return `${this.tabs.baseId}-tab-${this.value()}`; }
}

/** Importe tudo de uma vez: `imports: [FEW_TABS]`. */
export const FEW_TABS = [FewTabs, FewTabsList, FewTabsTrigger, FewTabsContent] as const;

// packages/react/src/components/navigation/tabs.tsx
"use client";
// Implementação de referência do padrão composto (ver docs/composition.md).
import { useId, useRef, type ComponentProps, type KeyboardEvent } from 'react';
import type { Orientation } from '@fewcompany/core';
import { Slot } from '../../lib/slot.js';
import { createContext } from '../../lib/context.js';
import { useControllableState } from '../../lib/use-controllable-state.js';
import { cx, dataAttr } from '../../lib/cx.js';
import { moveFocus } from '../../lib/roving.js';

interface TabsContextValue { baseId: string; value: string; setValue: (value: string) => void; orientation: Orientation; activation: 'automatic' | 'manual' }
const [TabsProvider, useTabs] = createContext<TabsContextValue>('Tabs');

export interface TabsProps extends Omit<ComponentProps<'div'>, 'defaultValue' | 'dir'> {
  asChild?: boolean;
  value?: string; defaultValue?: string; onValueChange?: (value: string) => void;
  orientation?: Orientation;
  /** automatic: seta seleciona; manual: seta só move o foco, Enter/Espaço seleciona. */
  activation?: 'automatic' | 'manual';
}
function TabsRoot({ asChild, value: valueProp, defaultValue = '', onValueChange, orientation = 'horizontal', activation = 'automatic', className, ...props }: TabsProps) {
  const baseId = useId();
  const [value, setValue] = useControllableState({ value: valueProp, defaultValue, onChange: onValueChange });
  const Comp = asChild ? Slot : 'div';
  return <TabsProvider value={{ baseId, value, setValue, orientation, activation }}><Comp {...props} className={cx('few-tabs', className)} data-orientation={orientation} /></TabsProvider>;
}

export interface TabsListProps extends ComponentProps<'div'> { asChild?: boolean; loop?: boolean }
function TabsList({ asChild, loop = true, className, onKeyDown, ...props }: TabsListProps) {
  const { orientation, activation, setValue } = useTabs('Tabs.List');
  const ref = useRef<HTMLDivElement>(null);
  const Comp = asChild ? Slot : 'div';
  function handleKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    onKeyDown?.(event);
    if (event.defaultPrevented) return;
    const target = moveFocus(ref.current, '[role="tab"]', event.key, { orientation, loop });
    if (!target) return;
    event.preventDefault();
    if (activation === 'automatic' && target.dataset.value !== undefined) setValue(target.dataset.value);
  }
  return <Comp {...props} ref={ref} role="tablist" aria-orientation={orientation} className={cx('few-tabs-list', className)} data-orientation={orientation} onKeyDown={handleKeyDown} />;
}

export interface TabsTriggerProps extends ComponentProps<'button'> { asChild?: boolean; value: string }
function TabsTrigger({ asChild, value, className, disabled, onClick, ...props }: TabsTriggerProps) {
  const { baseId, value: selected, setValue } = useTabs('Tabs.Trigger');
  const active = selected === value;
  const Comp = asChild ? Slot : 'button';
  return <Comp {...props} type="button" role="tab" id={`${baseId}-tab-${value}`} aria-selected={active} aria-controls={`${baseId}-panel-${value}`} tabIndex={active ? 0 : -1} disabled={disabled}
    data-state={active ? 'active' : 'inactive'} data-value={value} data-disabled={dataAttr(disabled)} className={cx('few-tabs-trigger', className)}
    onClick={(event) => { onClick?.(event); if (!event.defaultPrevented && !disabled) setValue(value); }} />;
}

export interface TabsContentProps extends ComponentProps<'div'> { asChild?: boolean; value: string; /** Mantém o painel montado quando inativo (hidden). */ forceMount?: boolean }
function TabsContent({ asChild, value, forceMount, className, children, ...props }: TabsContentProps) {
  const { baseId, value: selected } = useTabs('Tabs.Content');
  const active = selected === value;
  if (!active && !forceMount) return null;
  const Comp = asChild ? Slot : 'div';
  return <Comp {...props} role="tabpanel" id={`${baseId}-panel-${value}`} aria-labelledby={`${baseId}-tab-${value}`} hidden={!active} tabIndex={0} data-state={active ? 'active' : 'inactive'} className={cx('few-tabs-content', className)}>{children}</Comp>;
}

/** Tabs composto: <Tabs defaultValue="a"><Tabs.List><Tabs.Trigger value="a" /></Tabs.List><Tabs.Content value="a" /></Tabs> */
export const Tabs = Object.assign(TabsRoot, { Root: TabsRoot, List: TabsList, Trigger: TabsTrigger, Content: TabsContent });
export { TabsRoot, TabsList, TabsTrigger, TabsContent };
